  INFO root [2019-09-04 20:33:04,725] - 
  INFO root [2019-09-04 20:33:04,725] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:33:04,726] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:33:04,727] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:33:04,727] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:33:04,747] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56214 )
  INFO root [2019-09-04 20:33:04,748] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56214, SOMAXCONN=5.
  INFO root [2019-09-04 20:33:04,748] - server-configs:
  INFO root [2019-09-04 20:33:04,748] - 	internalTcpAddr : 192.168.56.1:56214
  INFO root [2019-09-04 20:33:04,748] - 	componentID : 5000
  WARN root [2019-09-04 20:33:04,758] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-04 20:33:04,912] - Components::findLogger: found logger, addr:192.168.56.1:56212
  INFO root [2019-09-04 20:33:05,004] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:33:05,004] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:33:05,234] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 6836 ----
  INFO root [2019-09-04 20:33:05,234] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:33:05,235] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:33:05,235] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:33:05,758] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:33:05,759] - Components::process(): Request for the process of identity...
  WARN root [2019-09-04 20:33:12,417] - Forwarding logs to logger[192.168.56.1:56212/0/0/0]...
 ERROR root [2019-09-04 20:33:33,064] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456491959550, lastReceivedTime=456429168217, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-04 20:33:33,116] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:33:33,127] - ==> [2019-09-04 20:33:33 063] TCPPacketReceiver::processPendingEvents(192.168.56.1:56212): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:33:33,128] - ==> [2019-09-04 20:33:33 065] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456491959550, lastReceivedTime=456429168217, inactivityExceptionPeriod=134887500)
  WARN root [2019-09-04 20:33:33,154] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56213): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:33:33,157] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456492168194, lastReceivedTime=456472078145, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-04 20:33:33,193] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:33:33,193] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:33:33,193] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:33:33,217] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-04 20:33:34,753] - 
  INFO root [2019-09-04 20:33:34,754] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:33:34,756] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:33:34,756] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:33:34,756] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:33:34,802] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56256 )
  INFO root [2019-09-04 20:33:34,802] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56256, SOMAXCONN=5.
  INFO root [2019-09-04 20:33:34,802] - server-configs:
  INFO root [2019-09-04 20:33:34,802] - 	internalTcpAddr : 192.168.56.1:56256
  INFO root [2019-09-04 20:33:34,802] - 	componentID : 5000
  WARN root [2019-09-04 20:33:34,805] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-04 20:33:36,313] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 12112 ----
  INFO root [2019-09-04 20:33:36,314] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:33:36,314] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:33:36,314] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:33:36,715] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:33:36,715] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:33:43,857] - Components::findComponents: find logger(1)...
  INFO root [2019-09-04 20:33:43,896] - Components::findComponents: found logger, addr:192.168.56.1:56261
  INFO root [2019-09-04 20:33:43,896] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:33:43,897] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:33:43,898] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-04 20:33:44,002] - Components::findComponents: found dbmgr, addr:192.168.56.1:56263
  INFO root [2019-09-04 20:33:44,003] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:33:44,003] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:33:44,003] - Components::findComponents: found dbmgr, addr:192.168.56.1:56263
  WARN root [2019-09-04 20:33:45,005] - Forwarding logs to logger[192.168.56.1:56261/0/0/0]...
 ERROR root [2019-09-04 20:34:29,779] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456619568246, lastReceivedTime=456563505398, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:34:29,783] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:34:29,784] - ==> [2019-09-04 20:34:29 777] TCPPacketReceiver::processPendingEvents(192.168.56.1:56261): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:34:29,784] - ==> [2019-09-04 20:34:29 780] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456619568246, lastReceivedTime=456563505398, inactivityExceptionPeriod=134887628)
  WARN root [2019-09-04 20:34:29,881] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56263): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:34:29,888] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456619812475, lastReceivedTime=456563641516, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:34:29,892] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:34:29,893] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:34:29,893] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:34:29,894] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-04 20:34:31,547] - 
  INFO root [2019-09-04 20:34:31,554] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:34:31,555] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:34:31,555] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:34:31,555] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:34:31,579] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56310 )
  INFO root [2019-09-04 20:34:31,579] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56310, SOMAXCONN=5.
  INFO root [2019-09-04 20:34:31,579] - server-configs:
  INFO root [2019-09-04 20:34:31,579] - 	internalTcpAddr : 192.168.56.1:56310
  INFO root [2019-09-04 20:34:31,579] - 	componentID : 5000
  WARN root [2019-09-04 20:34:31,581] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-04 20:34:33,086] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 1928 ----
  INFO root [2019-09-04 20:34:33,087] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:34:33,087] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:34:33,088] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:34:33,494] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:34:33,510] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:34:40,650] - Components::findComponents: find logger(1)...
  INFO root [2019-09-04 20:34:40,686] - Components::findComponents: found logger, addr:192.168.56.1:56314
  INFO root [2019-09-04 20:34:40,686] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:34:40,686] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:34:40,688] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-04 20:34:40,691] - Components::findComponents: found dbmgr, addr:192.168.56.1:56312
  INFO root [2019-09-04 20:34:40,691] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:34:40,691] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:34:40,793] - Components::findComponents: found dbmgr, addr:192.168.56.1:56312
  WARN root [2019-09-04 20:34:41,795] - Forwarding logs to logger[192.168.56.1:56314/0/0/0]...
 ERROR root [2019-09-04 20:34:56,326] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456679298917, lastReceivedTime=456644112908, inactivityExceptionPeriod=134887676)
  INFO root [2019-09-04 20:34:56,328] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:34:56,329] - ==> [2019-09-04 20:34:56 324] TCPPacketReceiver::processPendingEvents(192.168.56.1:56314): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:34:56,329] - ==> [2019-09-04 20:34:56 327] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456679298917, lastReceivedTime=456644112908, inactivityExceptionPeriod=134887676)
  WARN root [2019-09-04 20:34:56,425] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56312): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:34:56,429] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456679531653, lastReceivedTime=456656674447, inactivityExceptionPeriod=134887676)
  INFO root [2019-09-04 20:34:56,437] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:34:56,438] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:34:56,439] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:34:56,439] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-04 20:34:58,195] - 
  INFO root [2019-09-04 20:34:58,195] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:34:58,197] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:34:58,197] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:34:58,197] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:34:58,218] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56360 )
  INFO root [2019-09-04 20:34:58,218] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56360, SOMAXCONN=5.
  INFO root [2019-09-04 20:34:58,219] - server-configs:
  INFO root [2019-09-04 20:34:58,219] - 	internalTcpAddr : 192.168.56.1:56360
  INFO root [2019-09-04 20:34:58,219] - 	componentID : 5000
  WARN root [2019-09-04 20:34:58,219] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  WARN root [2019-09-04 20:34:58,560] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20081, errorno=10048
  INFO root [2019-09-04 20:34:58,564] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 19004 ----
  INFO root [2019-09-04 20:34:58,565] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:34:58,565] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:34:58,565] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:34:58,973] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:34:58,973] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:35:06,102] - Components::findComponents: find logger(1)...
  INFO root [2019-09-04 20:35:06,192] - Components::findComponents: found logger, addr:192.168.56.1:56356
  INFO root [2019-09-04 20:35:06,192] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:35:06,193] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:35:06,194] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-04 20:35:06,296] - Components::findComponents: found dbmgr, addr:192.168.56.1:56359
  INFO root [2019-09-04 20:35:06,297] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:35:06,297] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:35:06,297] - Components::findComponents: found dbmgr, addr:192.168.56.1:56359
  WARN root [2019-09-04 20:35:07,298] - Forwarding logs to logger[192.168.56.1:56356/0/0/0]...
 ERROR root [2019-09-04 20:35:50,941] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456802183077, lastReceivedTime=456750926923, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:35:50,945] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:35:50,945] - ==> [2019-09-04 20:35:50 940] TCPPacketReceiver::processPendingEvents(192.168.56.1:56356): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:35:50,945] - ==> [2019-09-04 20:35:50 942] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456802183077, lastReceivedTime=456750926923, inactivityExceptionPeriod=134887628)
  WARN root [2019-09-04 20:35:51,042] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56359): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:35:51,046] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=456802419054, lastReceivedTime=456751061629, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:35:51,059] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:35:51,060] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:35:51,061] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:35:51,061] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-04 20:56:08,591] - 
  INFO root [2019-09-04 20:56:08,599] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:56:08,600] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:56:08,600] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:56:08,600] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:56:08,636] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56635 )
  INFO root [2019-09-04 20:56:08,636] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56635, SOMAXCONN=5.
  INFO root [2019-09-04 20:56:08,636] - server-configs:
  INFO root [2019-09-04 20:56:08,636] - 	internalTcpAddr : 192.168.56.1:56635
  INFO root [2019-09-04 20:56:08,636] - 	componentID : 5000
  WARN root [2019-09-04 20:56:08,638] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-04 20:56:10,149] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 17424 ----
  INFO root [2019-09-04 20:56:10,150] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:56:10,150] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:56:10,150] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:56:10,579] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:56:10,581] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:56:17,752] - Components::findComponents: find logger(1)...
  INFO root [2019-09-04 20:56:17,838] - Components::findComponents: found logger, addr:192.168.56.1:56634
  INFO root [2019-09-04 20:56:17,838] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:56:17,838] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:56:17,839] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-04 20:56:17,941] - Components::findComponents: found dbmgr, addr:192.168.56.1:56632
  INFO root [2019-09-04 20:56:17,942] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:56:17,942] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:56:17,942] - Components::findComponents: found dbmgr, addr:192.168.56.1:56632
  WARN root [2019-09-04 20:56:18,943] - Forwarding logs to logger[192.168.56.1:56634/0/0/0]...
 ERROR root [2019-09-04 20:56:50,180] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459635473593, lastReceivedTime=459609469251, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-04 20:56:50,182] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:56:50,183] - ==> [2019-09-04 20:56:50 180] TCPPacketReceiver::processPendingEvents(192.168.56.1:56634): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:56:50,183] - ==> [2019-09-04 20:56:50 181] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459635473593, lastReceivedTime=459609469251, inactivityExceptionPeriod=134887500)
  WARN root [2019-09-04 20:56:50,288] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56632): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:56:50,295] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459635733092, lastReceivedTime=459609320152, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-04 20:56:50,298] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:56:50,298] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:56:50,299] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:56:50,299] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-04 20:57:33,801] - 
  INFO root [2019-09-04 20:57:33,802] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:57:33,804] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:57:33,804] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:57:33,804] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:57:33,821] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56688 )
  INFO root [2019-09-04 20:57:33,821] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56688, SOMAXCONN=5.
  INFO root [2019-09-04 20:57:33,821] - server-configs:
  INFO root [2019-09-04 20:57:33,822] - 	internalTcpAddr : 192.168.56.1:56688
  INFO root [2019-09-04 20:57:33,822] - 	componentID : 5000
  WARN root [2019-09-04 20:57:33,840] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  WARN root [2019-09-04 20:57:34,185] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20302, errorno=10048
  INFO root [2019-09-04 20:57:34,189] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 17912 ----
  INFO root [2019-09-04 20:57:34,189] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:57:34,190] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:57:34,190] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:57:34,591] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:57:34,592] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:57:39,400] - 
  INFO root [2019-09-04 20:57:39,422] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-04 20:57:39,423] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-04 20:57:39,424] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-04 20:57:39,424] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-04 20:57:39,456] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:56707 )
  INFO root [2019-09-04 20:57:39,456] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:56707, SOMAXCONN=5.
  INFO root [2019-09-04 20:57:39,456] - server-configs:
  INFO root [2019-09-04 20:57:39,456] - 	internalTcpAddr : 192.168.56.1:56707
  INFO root [2019-09-04 20:57:39,457] - 	componentID : 5000
  WARN root [2019-09-04 20:57:39,458] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-04 20:57:40,963] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 2082. PID: 13432 ----
  INFO root [2019-09-04 20:57:40,964] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-04 20:57:40,964] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-04 20:57:40,964] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-04 20:57:41,364] - ---- baseappmgr is running ----
 DEBUG root [2019-09-04 20:57:41,365] - Components::process(): Request for the process of identity...
  INFO root [2019-09-04 20:57:48,486] - Components::findComponents: find logger(1)...
  INFO root [2019-09-04 20:57:48,558] - Components::findComponents: found logger, addr:192.168.56.1:56705
  INFO root [2019-09-04 20:57:48,558] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:57:48,558] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:57:48,559] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-04 20:57:48,662] - Components::findComponents: found dbmgr, addr:192.168.56.1:56710
  INFO root [2019-09-04 20:57:48,662] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-04 20:57:48,663] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-04 20:57:48,663] - Components::findComponents: found dbmgr, addr:192.168.56.1:56710
  WARN root [2019-09-04 20:57:49,663] - Forwarding logs to logger[192.168.56.1:56705/0/0/0]...
 ERROR root [2019-09-04 20:58:31,944] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459864442311, lastReceivedTime=459813778502, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:58:31,946] - The following logs sent to logger failed:
  WARN root [2019-09-04 20:58:31,946] - ==> [2019-09-04 20:58:31 942] TCPPacketReceiver::processPendingEvents(192.168.56.1:56705): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:58:31,947] - ==> [2019-09-04 20:58:31 945] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459864442311, lastReceivedTime=459813778502, inactivityExceptionPeriod=134887628)
  WARN root [2019-09-04 20:58:32,042] - TCPPacketReceiver::processPendingEvents(192.168.56.1:56710): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-04 20:58:32,044] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=459864667648, lastReceivedTime=459813967012, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-04 20:58:32,057] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-04 20:58:32,064] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-04 20:58:32,064] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-04 20:58:32,065] - ThreadPool::destroy(): starting size 2.
