  INFO root [2019-05-08 10:03:38,868] - 
  INFO root [2019-05-08 10:03:38,868] - -----------------------------------------------------------------------------------------


  INFO root [2019-05-08 10:03:38,874] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-05-08 10:03:38,874] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/server_assets/;D:/kbengine/server_assets/scripts/;D:/kbengine/server_assets/res/
  INFO root [2019-05-08 10:03:38,874] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-05-08 10:03:38,886] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:64900 )
  INFO root [2019-05-08 10:03:38,926] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:64900, SOMAXCONN=5.
  INFO root [2019-05-08 10:03:38,926] - server-configs:
  INFO root [2019-05-08 10:03:38,926] - 	internalTcpAddr : 192.168.56.1:64900
  INFO root [2019-05-08 10:03:38,926] - 	componentID : 5000
  WARN root [2019-05-08 10:03:38,926] - invalid UID(0) <= 0, please check UID for environment! automatically set to 3960.
  INFO root [2019-05-08 10:03:38,995] - Components::findLogger: found logger, addr:192.168.56.1:64886
  INFO root [2019-05-08 10:03:38,995] - Components::addComponent: reset orderLog, uid=3960!
  INFO root [2019-05-08 10:03:38,995] - Components::addComponent[logger], uid=3960, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-05-08 10:03:38,995] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 3960. PID: 13128 ----
  INFO root [2019-05-08 10:03:38,995] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-05-08 10:03:38,995] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-05-08 10:03:38,995] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-05-08 10:03:39,423] - ---- baseappmgr is running ----
 DEBUG root [2019-05-08 10:03:39,423] - Components::process(): Request for the process of identity...
  WARN root [2019-05-08 10:03:45,628] - Forwarding logs to logger[192.168.56.1:64886/0/0/0]...
 ERROR root [2019-05-08 10:05:17,628] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317863974514, lastReceivedTime=317852845745, inactivityExceptionPeriod=134887804)
  INFO root [2019-05-08 10:05:17,634] - The following logs sent to logger failed:
  WARN root [2019-05-08 10:05:17,634] - ==> [2019-05-08 10:05:17 630] TCPPacketReceiver::processPendingEvents(192.168.56.1:64886): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-05-08 10:05:17,634] - ==> [2019-05-08 10:05:17 631] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317863974514, lastReceivedTime=317852845745, inactivityExceptionPeriod=134887804)
  WARN root [2019-05-08 10:05:17,728] - TCPPacketReceiver::processPendingEvents(192.168.56.1:64889): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-05-08 10:05:17,728] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317864205279, lastReceivedTime=317823055194, inactivityExceptionPeriod=134887804)
  INFO root [2019-05-08 10:05:17,748] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-05-08 10:05:17,764] - Shutdowner::onShutdown: shutting down
  INFO root [2019-05-08 10:05:17,764] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-05-08 10:05:17,764] - ThreadPool::destroy(): starting size 2.
