  INFO root [2019-09-20 14:29:51,055] - 
  INFO root [2019-09-20 14:29:51,055] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 14:29:51,056] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 14:29:51,057] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 14:29:51,057] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 14:29:51,067] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:64944 )
  INFO root [2019-09-20 14:29:51,068] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:64944, SOMAXCONN=5.
  INFO root [2019-09-20 14:29:51,068] - server-configs:
  INFO root [2019-09-20 14:29:51,068] - 	internalTcpAddr : 192.168.43.114:64944
  INFO root [2019-09-20 14:29:51,068] - 	componentID : 5000
  WARN root [2019-09-20 14:29:51,068] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 14:29:52,574] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 13240 ----
  INFO root [2019-09-20 14:29:52,574] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 14:29:52,574] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 14:29:52,575] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 14:29:52,994] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 14:29:52,994] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 14:30:00,156] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 14:30:00,196] - Components::findComponents: found logger, addr:192.168.43.114:64943
  INFO root [2019-09-20 14:30:00,197] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:30:00,197] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:30:00,198] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 14:30:00,301] - Components::findComponents: found dbmgr, addr:192.168.43.114:64939
  INFO root [2019-09-20 14:30:00,301] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:30:00,302] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:30:00,302] - Components::findComponents: found dbmgr, addr:192.168.43.114:64939
  WARN root [2019-09-20 14:30:01,303] - Forwarding logs to logger[192.168.43.114:64943/0/0/0]...
 ERROR root [2019-09-20 14:32:08,395] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525853284492, lastReceivedTime=1525677832278, inactivityExceptionPeriod=599500512)
  INFO root [2019-09-20 14:32:08,404] - The following logs sent to logger failed:
  WARN root [2019-09-20 14:32:08,404] - ==> [2019-09-20 14:32:08 394] TCPPacketReceiver::processPendingEvents(192.168.43.114:64943): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:32:08,404] - ==> [2019-09-20 14:32:08 397] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525853284492, lastReceivedTime=1525677832278, inactivityExceptionPeriod=599500512)
  WARN root [2019-09-20 14:32:08,488] - TCPPacketReceiver::processPendingEvents(192.168.43.114:64939): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:32:08,493] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525854258982, lastReceivedTime=1525676428976, inactivityExceptionPeriod=599500512)
  INFO root [2019-09-20 14:32:08,499] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 14:32:08,500] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 14:32:08,501] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 14:32:08,501] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 14:32:32,207] - 
  INFO root [2019-09-20 14:32:32,207] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 14:32:32,209] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 14:32:32,209] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 14:32:32,209] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 14:32:32,221] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65019 )
  INFO root [2019-09-20 14:32:32,221] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65019, SOMAXCONN=5.
  INFO root [2019-09-20 14:32:32,223] - server-configs:
  INFO root [2019-09-20 14:32:32,223] - 	internalTcpAddr : 192.168.43.114:65019
  INFO root [2019-09-20 14:32:32,223] - 	componentID : 5000
  WARN root [2019-09-20 14:32:32,224] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-20 14:32:32,639] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20735, errorno=10048
  INFO root [2019-09-20 14:32:32,643] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 15176 ----
  INFO root [2019-09-20 14:32:32,644] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 14:32:32,644] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 14:32:32,644] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 14:32:33,094] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 14:32:33,096] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 14:32:40,225] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 14:32:40,306] - Components::findComponents: found logger, addr:192.168.43.114:65015
  INFO root [2019-09-20 14:32:40,307] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:32:40,307] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:32:40,308] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 14:32:40,411] - Components::findComponents: found dbmgr, addr:192.168.43.114:65017
  INFO root [2019-09-20 14:32:40,411] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:32:40,412] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:32:40,412] - Components::findComponents: found dbmgr, addr:192.168.43.114:65017
  WARN root [2019-09-20 14:32:41,413] - Forwarding logs to logger[192.168.43.114:65015/0/0/0]...
 ERROR root [2019-09-20 14:34:43,100] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527400324726, lastReceivedTime=1527290315344, inactivityExceptionPeriod=599508825)
  INFO root [2019-09-20 14:34:43,101] - The following logs sent to logger failed:
  WARN root [2019-09-20 14:34:43,101] - ==> [2019-09-20 14:34:43 096] TCPPacketReceiver::processPendingEvents(192.168.43.114:65015): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:34:43,101] - ==> [2019-09-20 14:34:43 101] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527400324726, lastReceivedTime=1527290315344, inactivityExceptionPeriod=599508825)
  WARN root [2019-09-20 14:34:43,183] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65017): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:34:43,183] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527401161684, lastReceivedTime=1527291477502, inactivityExceptionPeriod=599508825)
  INFO root [2019-09-20 14:34:43,192] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 14:34:43,194] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 14:34:43,194] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 14:34:43,194] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 14:36:23,263] - 
  INFO root [2019-09-20 14:36:23,269] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 14:36:23,270] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 14:36:23,270] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 14:36:23,271] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 14:36:23,329] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65106 )
  INFO root [2019-09-20 14:36:23,329] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65106, SOMAXCONN=5.
  INFO root [2019-09-20 14:36:23,331] - server-configs:
  INFO root [2019-09-20 14:36:23,331] - 	internalTcpAddr : 192.168.43.114:65106
  INFO root [2019-09-20 14:36:23,331] - 	componentID : 5000
  WARN root [2019-09-20 14:36:23,332] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-20 14:36:23,708] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20775, errorno=10048
  INFO root [2019-09-20 14:36:23,711] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 3648 ----
  INFO root [2019-09-20 14:36:23,712] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 14:36:23,712] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 14:36:23,713] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 14:36:24,125] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 14:36:24,125] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 14:36:31,234] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 14:36:31,272] - Components::findComponents: found logger, addr:192.168.43.114:65104
  INFO root [2019-09-20 14:36:31,272] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:36:31,272] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:36:31,273] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 14:36:31,375] - Components::findComponents: found dbmgr, addr:192.168.43.114:65103
  INFO root [2019-09-20 14:36:31,375] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:36:31,375] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:36:31,376] - Components::findComponents: found dbmgr, addr:192.168.43.114:65103
  WARN root [2019-09-20 14:36:32,377] - Forwarding logs to logger[192.168.43.114:65104/0/0/0]...
 ERROR root [2019-09-20 14:39:17,859] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530147919337, lastReceivedTime=1529902272641, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-20 14:39:17,864] - The following logs sent to logger failed:
  WARN root [2019-09-20 14:39:17,864] - ==> [2019-09-20 14:39:17 858] TCPPacketReceiver::processPendingEvents(192.168.43.114:65104): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:39:17,864] - ==> [2019-09-20 14:39:17 860] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530147919337, lastReceivedTime=1529902272641, inactivityExceptionPeriod=599500192)
  WARN root [2019-09-20 14:39:17,937] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65103): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:39:17,939] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530148716276, lastReceivedTime=1529902337822, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-20 14:39:17,943] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 14:39:17,944] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 14:39:17,944] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 14:39:17,945] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 14:39:19,572] - 
  INFO root [2019-09-20 14:39:19,573] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 14:39:19,574] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 14:39:19,574] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 14:39:19,575] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 14:39:19,609] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65170 )
  INFO root [2019-09-20 14:39:19,610] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65170, SOMAXCONN=5.
  INFO root [2019-09-20 14:39:19,610] - server-configs:
  INFO root [2019-09-20 14:39:19,610] - 	internalTcpAddr : 192.168.43.114:65170
  INFO root [2019-09-20 14:39:19,610] - 	componentID : 5000
  WARN root [2019-09-20 14:39:19,615] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 14:39:19,991] - Components::findLogger: found logger, addr:192.168.43.114:65166
  INFO root [2019-09-20 14:39:19,991] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:39:19,991] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:39:19,996] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 18428 ----
  INFO root [2019-09-20 14:39:19,997] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 14:39:19,997] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 14:39:19,997] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 14:39:20,446] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 14:39:20,455] - Components::process(): Request for the process of identity...
  WARN root [2019-09-20 14:39:26,563] - Forwarding logs to logger[192.168.43.114:65166/0/0/0]...
 ERROR root [2019-09-20 14:45:28,038] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533849713415, lastReceivedTime=1533764494413, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 14:45:28,043] - The following logs sent to logger failed:
  WARN root [2019-09-20 14:45:28,043] - ==> [2019-09-20 14:45:28 038] TCPPacketReceiver::processPendingEvents(192.168.43.114:65166): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:45:28,043] - ==> [2019-09-20 14:45:28 040] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533849713415, lastReceivedTime=1533764494413, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-20 14:45:28,118] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65163): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:45:28,119] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533850519632, lastReceivedTime=1533763552010, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 14:45:28,121] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 14:45:28,121] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 14:45:28,122] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 14:45:28,122] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 14:58:07,745] - 
  INFO root [2019-09-20 14:58:07,746] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 14:58:07,747] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 14:58:07,748] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 14:58:07,748] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 14:58:07,758] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49573 )
  INFO root [2019-09-20 14:58:07,758] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49573, SOMAXCONN=5.
  INFO root [2019-09-20 14:58:07,758] - server-configs:
  INFO root [2019-09-20 14:58:07,759] - 	internalTcpAddr : 192.168.43.114:49573
  INFO root [2019-09-20 14:58:07,759] - 	componentID : 5000
  WARN root [2019-09-20 14:58:07,759] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 14:58:09,263] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 9616 ----
  INFO root [2019-09-20 14:58:09,264] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 14:58:09,265] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 14:58:09,265] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 14:58:09,686] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 14:58:09,687] - Components::process(): Request for the process of identity...
  WARN root [2019-09-20 14:58:13,125] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20110, errorno=10048
  INFO root [2019-09-20 14:58:17,167] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 14:58:17,220] - Components::findComponents: found logger, addr:192.168.43.114:49572
  INFO root [2019-09-20 14:58:17,220] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:58:17,220] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:58:17,221] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 14:58:17,327] - Components::findComponents: found dbmgr, addr:192.168.43.114:49574
  INFO root [2019-09-20 14:58:17,327] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 14:58:17,327] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 14:58:17,327] - Components::findComponents: found dbmgr, addr:192.168.43.114:49574
  WARN root [2019-09-20 14:58:18,327] - Forwarding logs to logger[192.168.43.114:49572/0/0/0]...
 ERROR root [2019-09-20 14:59:44,606] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542415393791, lastReceivedTime=1542346605610, inactivityExceptionPeriod=599502111)
  INFO root [2019-09-20 14:59:44,614] - The following logs sent to logger failed:
  WARN root [2019-09-20 14:59:44,615] - ==> [2019-09-20 14:59:44 601] TCPPacketReceiver::processPendingEvents(192.168.43.114:49572): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:59:44,616] - ==> [2019-09-20 14:59:44 608] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542415393791, lastReceivedTime=1542346605610, inactivityExceptionPeriod=599502111)
  WARN root [2019-09-20 14:59:44,730] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49574): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 14:59:44,735] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542416675297, lastReceivedTime=1542347334668, inactivityExceptionPeriod=599502111)
  INFO root [2019-09-20 14:59:44,744] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 14:59:44,745] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 14:59:44,746] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 14:59:44,746] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:04:19,892] - 
  INFO root [2019-09-20 15:04:19,910] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:04:19,911] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:04:19,911] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:04:19,911] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:04:19,958] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49742 )
  INFO root [2019-09-20 15:04:19,958] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49742, SOMAXCONN=5.
  INFO root [2019-09-20 15:04:19,959] - server-configs:
  INFO root [2019-09-20 15:04:19,959] - 	internalTcpAddr : 192.168.43.114:49742
  INFO root [2019-09-20 15:04:19,959] - 	componentID : 5000
  WARN root [2019-09-20 15:04:19,965] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-20 15:04:20,434] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20723, errorno=10048
  INFO root [2019-09-20 15:04:20,438] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 17840 ----
  INFO root [2019-09-20 15:04:20,439] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:04:20,439] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:04:20,440] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:04:20,929] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:04:20,931] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:04:28,101] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:04:28,112] - Components::findComponents: found logger, addr:192.168.43.114:49738
  INFO root [2019-09-20 15:04:28,113] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:04:28,113] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:04:28,114] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:04:28,221] - Components::findComponents: found dbmgr, addr:192.168.43.114:49740
  INFO root [2019-09-20 15:04:28,222] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:04:28,222] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:04:28,224] - Components::findComponents: found dbmgr, addr:192.168.43.114:49740
  WARN root [2019-09-20 15:04:29,224] - Forwarding logs to logger[192.168.43.114:49738/0/0/0]...
 ERROR root [2019-09-20 15:05:38,564] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545954974320, lastReceivedTime=1545768408663, inactivityExceptionPeriod=599499489)
  INFO root [2019-09-20 15:05:38,578] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:05:38,579] - ==> [2019-09-20 15:05:38 564] TCPPacketReceiver::processPendingEvents(192.168.43.114:49738): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:05:38,579] - ==> [2019-09-20 15:05:38 566] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545954974320, lastReceivedTime=1545768408663, inactivityExceptionPeriod=599499489)
  WARN root [2019-09-20 15:05:38,693] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49740): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:05:38,696] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545956291512, lastReceivedTime=1545769022869, inactivityExceptionPeriod=599499489)
  INFO root [2019-09-20 15:05:38,702] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:05:38,704] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:05:38,704] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:05:38,705] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:06:35,932] - 
  INFO root [2019-09-20 15:06:35,933] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:06:35,934] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:06:35,934] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:06:35,934] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:06:35,961] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49798 )
  INFO root [2019-09-20 15:06:35,962] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49798, SOMAXCONN=5.
  INFO root [2019-09-20 15:06:35,962] - server-configs:
  INFO root [2019-09-20 15:06:35,962] - 	internalTcpAddr : 192.168.43.114:49798
  INFO root [2019-09-20 15:06:35,962] - 	componentID : 5000
  WARN root [2019-09-20 15:06:35,963] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:06:37,472] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 9568 ----
  INFO root [2019-09-20 15:06:37,472] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:06:37,473] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:06:37,473] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:06:37,896] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:06:37,896] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:06:45,035] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:06:45,091] - Components::findComponents: found logger, addr:192.168.43.114:49800
  INFO root [2019-09-20 15:06:45,091] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:06:45,091] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:06:45,092] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:06:45,093] - Components::findComponents: found logger, addr:192.168.43.114:49800
  INFO root [2019-09-20 15:06:45,096] - Components::findComponents: found dbmgr, addr:192.168.43.114:49796
  INFO root [2019-09-20 15:06:45,096] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:06:45,097] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:06:45,198] - Components::findComponents: found dbmgr, addr:192.168.43.114:49796
  WARN root [2019-09-20 15:06:46,199] - Forwarding logs to logger[192.168.43.114:49800/0/0/0]...
 ERROR root [2019-09-20 15:10:30,479] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548874111348, lastReceivedTime=1548629027200, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-20 15:10:30,482] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:10:30,482] - ==> [2019-09-20 15:10:30 478] TCPPacketReceiver::processPendingEvents(192.168.43.114:49800): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:10:30,483] - ==> [2019-09-20 15:10:30 479] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548874111348, lastReceivedTime=1548629027200, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-20 15:10:30,566] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49796): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:10:30,567] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548874998426, lastReceivedTime=1548628429809, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-20 15:10:30,575] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:10:30,581] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:10:30,581] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:10:30,581] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:10:32,323] - 
  INFO root [2019-09-20 15:10:32,323] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:10:32,324] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:10:32,324] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:10:32,324] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:10:32,335] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49904 )
  INFO root [2019-09-20 15:10:32,335] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49904, SOMAXCONN=5.
  INFO root [2019-09-20 15:10:32,335] - server-configs:
  INFO root [2019-09-20 15:10:32,336] - 	internalTcpAddr : 192.168.43.114:49904
  INFO root [2019-09-20 15:10:32,336] - 	componentID : 5000
  WARN root [2019-09-20 15:10:32,337] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:10:33,846] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 14780 ----
  INFO root [2019-09-20 15:10:33,846] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:10:33,847] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:10:33,847] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:10:34,301] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:10:34,302] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:10:41,449] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:10:41,492] - Components::findComponents: found logger, addr:192.168.43.114:49900
  INFO root [2019-09-20 15:10:41,492] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:10:41,492] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:10:41,493] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:10:41,596] - Components::findComponents: found dbmgr, addr:192.168.43.114:49901
  INFO root [2019-09-20 15:10:41,597] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:10:41,597] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:10:41,598] - Components::findComponents: found dbmgr, addr:192.168.43.114:49901
  WARN root [2019-09-20 15:10:42,599] - Forwarding logs to logger[192.168.43.114:49900/0/0/0]...
 ERROR root [2019-09-20 15:21:40,263] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555571960986, lastReceivedTime=1555491729677, inactivityExceptionPeriod=599498466)
  INFO root [2019-09-20 15:21:40,265] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:21:40,265] - ==> [2019-09-20 15:21:40 262] TCPPacketReceiver::processPendingEvents(192.168.43.114:49900): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:21:40,266] - ==> [2019-09-20 15:21:40 264] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555571960986, lastReceivedTime=1555491729677, inactivityExceptionPeriod=599498466)
  WARN root [2019-09-20 15:21:40,349] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49901): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:21:40,350] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555572834261, lastReceivedTime=1555491499992, inactivityExceptionPeriod=599498466)
  INFO root [2019-09-20 15:21:40,355] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:21:40,357] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:21:40,357] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:21:40,358] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:28:51,046] - 
  INFO root [2019-09-20 15:28:51,048] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:28:51,049] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:28:51,049] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:28:51,049] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:28:51,074] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50512 )
  INFO root [2019-09-20 15:28:51,076] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50512, SOMAXCONN=5.
  INFO root [2019-09-20 15:28:51,076] - server-configs:
  INFO root [2019-09-20 15:28:51,076] - 	internalTcpAddr : 192.168.43.114:50512
  INFO root [2019-09-20 15:28:51,076] - 	componentID : 5000
  WARN root [2019-09-20 15:28:51,080] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:28:52,593] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 1276 ----
  INFO root [2019-09-20 15:28:52,593] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:28:52,594] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:28:52,594] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:28:53,089] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:28:53,090] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:29:00,216] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:29:00,317] - Components::findComponents: found logger, addr:192.168.43.114:50510
  INFO root [2019-09-20 15:29:00,317] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:29:00,318] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:29:00,319] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:29:00,423] - Components::findComponents: found dbmgr, addr:192.168.43.114:50507
  INFO root [2019-09-20 15:29:00,423] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:29:00,423] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:29:00,423] - Components::findComponents: found dbmgr, addr:192.168.43.114:50507
  WARN root [2019-09-20 15:29:01,424] - Forwarding logs to logger[192.168.43.114:50510/0/0/0]...
 ERROR root [2019-09-20 15:31:29,540] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561464727720, lastReceivedTime=1561379211585, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 15:31:29,548] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:31:29,548] - ==> [2019-09-20 15:31:29 539] TCPPacketReceiver::processPendingEvents(192.168.43.114:50510): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:31:29,548] - ==> [2019-09-20 15:31:29 541] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561464727720, lastReceivedTime=1561379211585, inactivityExceptionPeriod=599498785)
  WARN root [2019-09-20 15:31:29,635] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50507): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:31:29,638] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561465709151, lastReceivedTime=1561378078093, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 15:31:29,647] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:31:29,652] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:31:29,652] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:31:29,652] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:31:31,519] - 
  INFO root [2019-09-20 15:31:31,527] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:31:31,528] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:31:31,528] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:31:31,528] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:31:31,583] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50583 )
  INFO root [2019-09-20 15:31:31,584] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50583, SOMAXCONN=5.
  INFO root [2019-09-20 15:31:31,587] - server-configs:
  INFO root [2019-09-20 15:31:31,587] - 	internalTcpAddr : 192.168.43.114:50583
  INFO root [2019-09-20 15:31:31,587] - 	componentID : 5000
  WARN root [2019-09-20 15:31:31,591] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-20 15:31:32,043] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20508, errorno=10048
  INFO root [2019-09-20 15:31:32,047] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 11076 ----
  INFO root [2019-09-20 15:31:32,047] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:31:32,047] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:31:32,048] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:31:32,554] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:31:32,555] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:31:39,729] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:31:39,764] - Components::findComponents: found logger, addr:192.168.43.114:50579
  INFO root [2019-09-20 15:31:39,765] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:31:39,765] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:31:39,766] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:31:39,868] - Components::findComponents: found dbmgr, addr:192.168.43.114:50580
  INFO root [2019-09-20 15:31:39,868] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:31:39,869] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:31:39,869] - Components::findComponents: found dbmgr, addr:192.168.43.114:50580
  WARN root [2019-09-20 15:31:40,869] - Forwarding logs to logger[192.168.43.114:50579/0/0/0]...
 ERROR root [2019-09-20 15:38:37,830] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565747620552, lastReceivedTime=1565683799397, inactivityExceptionPeriod=599499617)
  INFO root [2019-09-20 15:38:37,836] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:38:37,836] - ==> [2019-09-20 15:38:37 827] TCPPacketReceiver::processPendingEvents(192.168.43.114:50579): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:38:37,837] - ==> [2019-09-20 15:38:37 831] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565747620552, lastReceivedTime=1565683799397, inactivityExceptionPeriod=599499617)
  WARN root [2019-09-20 15:38:37,950] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50580): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:38:37,951] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565748840593, lastReceivedTime=1565684964668, inactivityExceptionPeriod=599499617)
  INFO root [2019-09-20 15:38:37,953] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:38:37,953] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:38:37,954] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:38:37,954] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:42:10,034] - 
  INFO root [2019-09-20 15:42:10,041] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:42:10,043] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:42:10,044] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:42:10,045] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:42:10,090] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50886 )
  INFO root [2019-09-20 15:42:10,091] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50886, SOMAXCONN=5.
  INFO root [2019-09-20 15:42:10,091] - server-configs:
  INFO root [2019-09-20 15:42:10,091] - 	internalTcpAddr : 192.168.43.114:50886
  INFO root [2019-09-20 15:42:10,091] - 	componentID : 5000
  WARN root [2019-09-20 15:42:10,098] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:42:11,603] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 10124 ----
  INFO root [2019-09-20 15:42:11,605] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:42:11,606] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:42:11,606] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:42:12,090] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:42:12,091] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:42:19,248] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:42:19,313] - Components::findComponents: found logger, addr:192.168.43.114:50887
  INFO root [2019-09-20 15:42:19,313] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:42:19,314] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:42:19,315] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:42:19,418] - Components::findComponents: found dbmgr, addr:192.168.43.114:50882
  INFO root [2019-09-20 15:42:19,418] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:42:19,418] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:42:19,418] - Components::findComponents: found dbmgr, addr:192.168.43.114:50882
  WARN root [2019-09-20 15:42:20,418] - Forwarding logs to logger[192.168.43.114:50887/0/0/0]...
 ERROR root [2019-09-20 15:44:43,769] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407011215, lastReceivedTime=1569370190572, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-20 15:44:43,775] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:44:43,775] - ==> [2019-09-20 15:44:43 767] TCPPacketReceiver::processPendingEvents(192.168.43.114:50887): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:44:43,775] - ==> [2019-09-20 15:44:43 769] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407011215, lastReceivedTime=1569370190572, inactivityExceptionPeriod=599500064)
  WARN root [2019-09-20 15:44:43,858] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50882): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:44:43,860] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407929967, lastReceivedTime=1569369858660, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-20 15:44:43,866] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:44:43,868] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:44:43,868] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:44:43,868] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:48:39,362] - 
  INFO root [2019-09-20 15:48:39,364] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:48:39,365] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:48:39,366] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:48:39,366] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:48:39,376] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51002 )
  INFO root [2019-09-20 15:48:39,376] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51002, SOMAXCONN=5.
  INFO root [2019-09-20 15:48:39,376] - server-configs:
  INFO root [2019-09-20 15:48:39,376] - 	internalTcpAddr : 192.168.43.114:51002
  INFO root [2019-09-20 15:48:39,377] - 	componentID : 5000
  WARN root [2019-09-20 15:48:39,378] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:48:40,884] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 15640 ----
  INFO root [2019-09-20 15:48:40,885] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:48:40,885] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:48:40,886] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:48:41,438] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:48:41,439] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: found logger, addr:192.168.43.114:51005
  INFO root [2019-09-20 15:48:48,654] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:48:48,654] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: found logger, addr:192.168.43.114:51005
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: found dbmgr, addr:192.168.43.114:51004
  INFO root [2019-09-20 15:48:48,654] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:48:48,654] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:48:48,654] - Components::findComponents: found dbmgr, addr:192.168.43.114:51004
  WARN root [2019-09-20 15:48:49,852] - Forwarding logs to logger[192.168.43.114:51005/0/0/0]...
 ERROR root [2019-09-20 15:54:33,682] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575306143302, lastReceivedTime=1575063869146, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 15:54:33,682] - The following logs sent to logger failed:
  WARN root [2019-09-20 15:54:33,682] - ==> [2019-09-20 15:54:33 682] TCPPacketReceiver::processPendingEvents(192.168.43.114:51005): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:54:33,682] - ==> [2019-09-20 15:54:33 682] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575306143302, lastReceivedTime=1575063869146, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-20 15:54:33,682] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 15:54:33,682] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575307445507, lastReceivedTime=1575063916581, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 15:54:33,682] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 15:54:33,682] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 15:54:33,682] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 15:54:33,682] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 15:58:28,443] - 
  INFO root [2019-09-20 15:58:28,443] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 15:58:28,444] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 15:58:28,444] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 15:58:28,444] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 15:58:28,454] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51256 )
  INFO root [2019-09-20 15:58:28,454] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51256, SOMAXCONN=5.
  INFO root [2019-09-20 15:58:28,455] - server-configs:
  INFO root [2019-09-20 15:58:28,455] - 	internalTcpAddr : 192.168.43.114:51256
  INFO root [2019-09-20 15:58:28,455] - 	componentID : 5000
  WARN root [2019-09-20 15:58:28,459] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 15:58:29,964] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 524 ----
  INFO root [2019-09-20 15:58:29,965] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 15:58:29,965] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 15:58:29,966] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 15:58:30,393] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 15:58:30,393] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 15:58:37,527] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 15:58:37,541] - Components::findComponents: found logger, addr:192.168.43.114:51259
  INFO root [2019-09-20 15:58:37,541] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:58:37,541] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:58:37,542] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 15:58:37,645] - Components::findComponents: found dbmgr, addr:192.168.43.114:51260
  INFO root [2019-09-20 15:58:37,645] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 15:58:37,645] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 15:58:37,645] - Components::findComponents: found dbmgr, addr:192.168.43.114:51260
  WARN root [2019-09-20 15:58:38,645] - Forwarding logs to logger[192.168.43.114:51259/0/0/0]...
 ERROR root [2019-09-20 16:00:55,592] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579125246442, lastReceivedTime=1578854553040, inactivityExceptionPeriod=599520080)
  INFO root [2019-09-20 16:00:55,599] - The following logs sent to logger failed:
  WARN root [2019-09-20 16:00:55,599] - ==> [2019-09-20 16:00:55 589] TCPPacketReceiver::processPendingEvents(192.168.43.114:51259): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 16:00:55,599] - ==> [2019-09-20 16:00:55 593] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579125246442, lastReceivedTime=1578854553040, inactivityExceptionPeriod=599520080)
  WARN root [2019-09-20 16:00:55,701] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51260): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 16:00:55,715] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579126474356, lastReceivedTime=1578854651224, inactivityExceptionPeriod=599520080)
  INFO root [2019-09-20 16:00:55,733] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 16:00:55,734] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 16:00:55,734] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 16:00:55,734] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 16:01:37,095] - 
  INFO root [2019-09-20 16:01:37,112] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 16:01:37,113] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 16:01:37,113] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 16:01:37,114] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 16:01:37,158] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51355 )
  INFO root [2019-09-20 16:01:37,158] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51355, SOMAXCONN=5.
  INFO root [2019-09-20 16:01:37,158] - server-configs:
  INFO root [2019-09-20 16:01:37,159] - 	internalTcpAddr : 192.168.43.114:51355
  INFO root [2019-09-20 16:01:37,159] - 	componentID : 5000
  WARN root [2019-09-20 16:01:37,161] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 16:01:38,680] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 3332 ----
  INFO root [2019-09-20 16:01:38,681] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 16:01:38,682] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 16:01:38,682] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 16:01:39,111] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 16:01:39,112] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 16:01:46,236] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 16:01:46,316] - Components::findComponents: found logger, addr:192.168.43.114:51352
  INFO root [2019-09-20 16:01:46,316] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 16:01:46,316] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 16:01:46,317] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 16:01:46,420] - Components::findComponents: found dbmgr, addr:192.168.43.114:51359
  INFO root [2019-09-20 16:01:46,421] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 16:01:46,421] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 16:01:46,421] - Components::findComponents: found dbmgr, addr:192.168.43.114:51359
  WARN root [2019-09-20 16:01:47,422] - Forwarding logs to logger[192.168.43.114:51352/0/0/0]...
 ERROR root [2019-09-20 16:08:58,691] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583956235825, lastReceivedTime=1583740586918, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 16:08:58,698] - The following logs sent to logger failed:
  WARN root [2019-09-20 16:08:58,698] - ==> [2019-09-20 16:08:58 689] TCPPacketReceiver::processPendingEvents(192.168.43.114:51352): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 16:08:58,698] - ==> [2019-09-20 16:08:58 692] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583956235825, lastReceivedTime=1583740586918, inactivityExceptionPeriod=599498785)
  WARN root [2019-09-20 16:08:58,772] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51359): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 16:08:58,775] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583957078749, lastReceivedTime=1583741152480, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 16:08:58,779] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 16:08:58,781] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 16:08:58,781] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 16:08:58,781] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 17:04:57,346] - 
  INFO root [2019-09-20 17:04:57,347] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 17:04:57,348] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 17:04:57,348] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 17:04:57,348] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 17:04:57,358] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52507 )
  INFO root [2019-09-20 17:04:57,358] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52507, SOMAXCONN=5.
  INFO root [2019-09-20 17:04:57,359] - server-configs:
  INFO root [2019-09-20 17:04:57,359] - 	internalTcpAddr : 192.168.43.114:52507
  INFO root [2019-09-20 17:04:57,359] - 	componentID : 5000
  WARN root [2019-09-20 17:04:57,359] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 17:04:58,864] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 15860 ----
  INFO root [2019-09-20 17:04:58,865] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 17:04:58,865] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 17:04:58,866] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 17:04:59,296] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 17:04:59,325] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 17:05:06,468] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 17:05:06,506] - Components::findComponents: found logger, addr:192.168.43.114:52513
  INFO root [2019-09-20 17:05:06,506] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:05:06,506] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:05:06,507] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 17:05:06,611] - Components::findComponents: found dbmgr, addr:192.168.43.114:52509
  INFO root [2019-09-20 17:05:06,611] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:05:06,611] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:05:06,616] - Components::findComponents: found dbmgr, addr:192.168.43.114:52509
  WARN root [2019-09-20 17:05:07,617] - Forwarding logs to logger[192.168.43.114:52513/0/0/0]...
 ERROR root [2019-09-20 17:06:31,353] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618482848732, lastReceivedTime=1618444232090, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 17:06:31,361] - The following logs sent to logger failed:
  WARN root [2019-09-20 17:06:31,361] - ==> [2019-09-20 17:06:31 351] TCPPacketReceiver::processPendingEvents(192.168.43.114:52513): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:06:31,361] - ==> [2019-09-20 17:06:31 353] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618482848732, lastReceivedTime=1618444232090, inactivityExceptionPeriod=599498785)
  WARN root [2019-09-20 17:06:31,444] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52509): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:06:31,455] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618483875890, lastReceivedTime=1618443908401, inactivityExceptionPeriod=599498785)
  INFO root [2019-09-20 17:06:31,472] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 17:06:31,473] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 17:06:31,473] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 17:06:31,474] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 17:06:33,111] - 
  INFO root [2019-09-20 17:06:33,114] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 17:06:33,115] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 17:06:33,116] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 17:06:33,116] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 17:06:33,136] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52565 )
  INFO root [2019-09-20 17:06:33,136] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52565, SOMAXCONN=5.
  INFO root [2019-09-20 17:06:33,137] - server-configs:
  INFO root [2019-09-20 17:06:33,137] - 	internalTcpAddr : 192.168.43.114:52565
  INFO root [2019-09-20 17:06:33,137] - 	componentID : 5000
  WARN root [2019-09-20 17:06:33,137] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 17:06:34,642] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 12668 ----
  INFO root [2019-09-20 17:06:34,643] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 17:06:34,643] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 17:06:34,644] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 17:06:35,098] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 17:06:35,099] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 17:06:42,226] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 17:06:42,284] - Components::findComponents: found logger, addr:192.168.43.114:52567
  INFO root [2019-09-20 17:06:42,284] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:06:42,284] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:06:42,286] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 17:06:42,290] - Components::findComponents: found logger, addr:192.168.43.114:52567
  INFO root [2019-09-20 17:06:42,293] - Components::findComponents: found dbmgr, addr:192.168.43.114:52560
  INFO root [2019-09-20 17:06:42,293] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:06:42,294] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:06:42,394] - Components::findComponents: found dbmgr, addr:192.168.43.114:52560
  WARN root [2019-09-20 17:06:43,396] - Forwarding logs to logger[192.168.43.114:52567/0/0/0]...
 ERROR root [2019-09-20 17:09:05,623] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620025557894, lastReceivedTime=1620000618632, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 17:09:05,626] - The following logs sent to logger failed:
  WARN root [2019-09-20 17:09:05,627] - ==> [2019-09-20 17:09:05 619] TCPPacketReceiver::processPendingEvents(192.168.43.114:52567): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:09:05,627] - ==> [2019-09-20 17:09:05 624] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620025557894, lastReceivedTime=1620000618632, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-20 17:09:05,718] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52560): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:09:05,725] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620026579029, lastReceivedTime=1619999586626, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 17:09:05,736] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 17:09:05,739] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 17:09:05,739] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 17:09:05,740] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 17:09:07,365] - 
  INFO root [2019-09-20 17:09:07,378] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 17:09:07,379] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 17:09:07,379] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 17:09:07,379] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 17:09:07,444] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52615 )
  INFO root [2019-09-20 17:09:07,445] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52615, SOMAXCONN=5.
  INFO root [2019-09-20 17:09:07,445] - server-configs:
  INFO root [2019-09-20 17:09:07,445] - 	internalTcpAddr : 192.168.43.114:52615
  INFO root [2019-09-20 17:09:07,445] - 	componentID : 5000
  WARN root [2019-09-20 17:09:07,449] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-20 17:09:07,833] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20767, errorno=10048
  INFO root [2019-09-20 17:09:07,836] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 11992 ----
  INFO root [2019-09-20 17:09:07,837] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 17:09:07,837] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 17:09:07,837] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 17:09:08,295] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 17:09:08,315] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 17:09:15,479] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 17:09:15,534] - Components::findComponents: found logger, addr:192.168.43.114:52620
  INFO root [2019-09-20 17:09:15,534] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:09:15,534] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:09:15,536] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 17:09:15,540] - Components::findComponents: found logger, addr:192.168.43.114:52620
  INFO root [2019-09-20 17:09:15,544] - Components::findComponents: found dbmgr, addr:192.168.43.114:52617
  INFO root [2019-09-20 17:09:15,544] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 17:09:15,545] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 17:09:15,647] - Components::findComponents: found dbmgr, addr:192.168.43.114:52617
  WARN root [2019-09-20 17:09:16,647] - Forwarding logs to logger[192.168.43.114:52620/0/0/0]...
 ERROR root [2019-09-20 17:10:33,172] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620901041519, lastReceivedTime=1620644054246, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-20 17:10:33,175] - The following logs sent to logger failed:
  WARN root [2019-09-20 17:10:33,175] - ==> [2019-09-20 17:10:33 171] TCPPacketReceiver::processPendingEvents(192.168.43.114:52620): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:10:33,175] - ==> [2019-09-20 17:10:33 172] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620901041519, lastReceivedTime=1620644054246, inactivityExceptionPeriod=599500192)
  WARN root [2019-09-20 17:10:33,264] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52617): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 17:10:33,271] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620902033696, lastReceivedTime=1620643861773, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-20 17:10:33,276] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 17:10:33,288] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 17:10:33,288] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 17:10:33,289] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 19:33:31,836] - 
  INFO root [2019-09-20 19:33:31,845] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 19:33:31,846] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 19:33:31,846] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 19:33:31,847] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 19:33:31,856] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53607 )
  INFO root [2019-09-20 19:33:31,857] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53607, SOMAXCONN=5.
  INFO root [2019-09-20 19:33:31,857] - server-configs:
  INFO root [2019-09-20 19:33:31,857] - 	internalTcpAddr : 10.12.231.110:53607
  INFO root [2019-09-20 19:33:31,857] - 	componentID : 5000
  WARN root [2019-09-20 19:33:31,857] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 19:33:33,362] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 76 ----
  INFO root [2019-09-20 19:33:33,362] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 19:33:33,362] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 19:33:33,363] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 19:33:33,794] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 19:33:33,794] - Components::process(): Request for the process of identity...
  WARN root [2019-09-20 19:33:37,203] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20900, errorno=10048
  INFO root [2019-09-20 19:33:41,245] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 19:33:41,326] - Components::findComponents: found logger, addr:10.12.231.110:53610
  INFO root [2019-09-20 19:33:41,326] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:33:41,326] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:33:41,328] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 19:33:41,332] - Components::findComponents: found logger, addr:10.12.231.110:53610
  INFO root [2019-09-20 19:33:41,334] - Components::findComponents: found dbmgr, addr:10.12.231.110:53604
  INFO root [2019-09-20 19:33:41,334] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:33:41,335] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:33:41,436] - Components::findComponents: found dbmgr, addr:10.12.231.110:53604
  WARN root [2019-09-20 19:33:42,436] - Forwarding logs to logger[10.12.231.110:53610/0/0/0]...
 ERROR root [2019-09-20 19:36:00,518] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708226529185, lastReceivedTime=1707942321111, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 19:36:00,523] - The following logs sent to logger failed:
  WARN root [2019-09-20 19:36:00,523] - ==> [2019-09-20 19:36:00 516] TCPPacketReceiver::processPendingEvents(10.12.231.110:53610): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:36:00,523] - ==> [2019-09-20 19:36:00 520] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708226529185, lastReceivedTime=1707942321111, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-20 19:36:00,595] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53604): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:36:00,596] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708227301996, lastReceivedTime=1707938183258, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-20 19:36:00,606] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 19:36:00,617] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 19:36:00,617] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 19:36:00,617] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 19:36:02,105] - 
  INFO root [2019-09-20 19:36:02,106] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 19:36:02,107] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 19:36:02,107] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 19:36:02,108] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 19:36:02,117] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53673 )
  INFO root [2019-09-20 19:36:02,117] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53673, SOMAXCONN=5.
  INFO root [2019-09-20 19:36:02,117] - server-configs:
  INFO root [2019-09-20 19:36:02,118] - 	internalTcpAddr : 10.12.231.110:53673
  INFO root [2019-09-20 19:36:02,118] - 	componentID : 5000
  WARN root [2019-09-20 19:36:02,125] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 19:36:03,629] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 13148 ----
  INFO root [2019-09-20 19:36:03,630] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 19:36:03,630] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 19:36:03,630] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 19:36:04,050] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 19:36:04,055] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 19:36:11,192] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 19:36:11,241] - Components::findComponents: found logger, addr:10.12.231.110:53678
  INFO root [2019-09-20 19:36:11,242] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:36:11,242] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:36:11,243] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 19:36:11,345] - Components::findComponents: found dbmgr, addr:10.12.231.110:53675
  INFO root [2019-09-20 19:36:11,345] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:36:11,345] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:36:11,345] - Components::findComponents: found dbmgr, addr:10.12.231.110:53675
  WARN root [2019-09-20 19:36:12,346] - Forwarding logs to logger[10.12.231.110:53678/0/0/0]...
 ERROR root [2019-09-20 19:37:43,242] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709253765568, lastReceivedTime=1709143074091, inactivityExceptionPeriod=599480433)
  INFO root [2019-09-20 19:37:43,245] - The following logs sent to logger failed:
  WARN root [2019-09-20 19:37:43,246] - ==> [2019-09-20 19:37:43 241] TCPPacketReceiver::processPendingEvents(10.12.231.110:53678): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:37:43,246] - ==> [2019-09-20 19:37:43 243] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709253765568, lastReceivedTime=1709143074091, inactivityExceptionPeriod=599480433)
  WARN root [2019-09-20 19:37:43,329] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53675): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:37:43,330] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709254651813, lastReceivedTime=1709143009197, inactivityExceptionPeriod=599480433)
  INFO root [2019-09-20 19:37:43,338] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 19:37:43,340] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 19:37:43,341] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 19:37:43,341] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 19:39:08,114] - 
  INFO root [2019-09-20 19:39:08,115] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 19:39:08,116] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 19:39:08,116] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 19:39:08,116] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 19:39:08,131] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53725 )
  INFO root [2019-09-20 19:39:08,131] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53725, SOMAXCONN=5.
  INFO root [2019-09-20 19:39:08,131] - server-configs:
  INFO root [2019-09-20 19:39:08,131] - 	internalTcpAddr : 10.12.231.110:53725
  INFO root [2019-09-20 19:39:08,131] - 	componentID : 5000
  WARN root [2019-09-20 19:39:08,132] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 19:39:09,636] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 9496 ----
  INFO root [2019-09-20 19:39:09,637] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 19:39:09,637] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 19:39:09,638] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 19:39:10,079] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 19:39:10,080] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 19:39:17,220] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 19:39:17,325] - Components::findComponents: found logger, addr:10.12.231.110:53727
  INFO root [2019-09-20 19:39:17,325] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:39:17,325] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:39:17,327] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 19:39:17,430] - Components::findComponents: found dbmgr, addr:10.12.231.110:53729
  INFO root [2019-09-20 19:39:17,431] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 19:39:17,431] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 19:39:17,432] - Components::findComponents: found dbmgr, addr:10.12.231.110:53729
  WARN root [2019-09-20 19:39:18,432] - Forwarding logs to logger[10.12.231.110:53727/0/0/0]...
 ERROR root [2019-09-20 19:42:05,949] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711880841550, lastReceivedTime=1711603093773, inactivityExceptionPeriod=599501471)
  INFO root [2019-09-20 19:42:05,957] - The following logs sent to logger failed:
  WARN root [2019-09-20 19:42:05,957] - ==> [2019-09-20 19:42:05 949] TCPPacketReceiver::processPendingEvents(10.12.231.110:53727): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:42:05,957] - ==> [2019-09-20 19:42:05 950] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711880841550, lastReceivedTime=1711603093773, inactivityExceptionPeriod=599501471)
  WARN root [2019-09-20 19:42:06,030] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53729): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 19:42:06,032] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711881661888, lastReceivedTime=1711603373741, inactivityExceptionPeriod=599501471)
  INFO root [2019-09-20 19:42:06,046] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 19:42:06,047] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 19:42:06,047] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 19:42:06,048] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 20:40:03,636] - 
  INFO root [2019-09-20 20:40:03,637] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:40:03,638] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:40:03,638] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:40:03,638] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:40:03,648] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53799 )
  INFO root [2019-09-20 20:40:03,649] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53799, SOMAXCONN=5.
  INFO root [2019-09-20 20:40:03,649] - server-configs:
  INFO root [2019-09-20 20:40:03,649] - 	internalTcpAddr : 127.0.0.1:53799
  INFO root [2019-09-20 20:40:03,649] - 	componentID : 5000
  WARN root [2019-09-20 20:40:03,649] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:40:05,155] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 11528 ----
  INFO root [2019-09-20 20:40:05,156] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:40:05,156] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:40:05,157] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:40:05,563] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:40:05,564] - Components::process(): Request for the process of identity...
  WARN root [2019-09-20 20:40:08,970] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20664, errorno=10048
  INFO root [2019-09-20 20:40:13,038] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:40:14,538] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:14,539] - Components::findComponents: receive error!
  WARN root [2019-09-20 20:40:14,540] - Components::findComponents: not found logger!
  INFO root [2019-09-20 20:40:15,558] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-09-20 20:40:17,059] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:17,060] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:18,079] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-09-20 20:40:19,580] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:19,581] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:20,598] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-09-20 20:40:22,100] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:22,101] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:23,118] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-09-20 20:40:24,620] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:24,622] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:25,638] - Components::findComponents: find dbmgr(5)...
  INFO root [2019-09-20 20:40:27,484] - 
  INFO root [2019-09-20 20:40:27,485] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:40:27,486] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:40:27,486] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:40:27,486] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:40:27,498] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53818 )
  INFO root [2019-09-20 20:40:27,498] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53818, SOMAXCONN=5.
  INFO root [2019-09-20 20:40:27,498] - server-configs:
  INFO root [2019-09-20 20:40:27,499] - 	internalTcpAddr : 127.0.0.1:53818
  INFO root [2019-09-20 20:40:27,499] - 	componentID : 5000
  WARN root [2019-09-20 20:40:27,499] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:40:29,005] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 6932 ----
  INFO root [2019-09-20 20:40:29,005] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:40:29,006] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:40:29,006] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:40:29,431] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:40:29,432] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:40:36,566] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:40:38,068] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:38,069] - Components::findComponents: receive error!
  WARN root [2019-09-20 20:40:38,069] - Components::findComponents: not found logger!
  INFO root [2019-09-20 20:40:39,087] - Components::findComponents: find dbmgr(1)...
  WARN root [2019-09-20 20:40:39,416] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20754, errorno=10048
  INFO root [2019-09-20 20:40:40,427] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-09-20 20:40:41,928] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:41,929] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:42,947] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-09-20 20:40:44,447] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:44,449] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:45,467] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-09-20 20:40:46,969] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:40:46,970] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:40:47,987] - Components::findComponents: find dbmgr(5)...
  INFO root [2019-09-20 20:40:50,055] - 
  INFO root [2019-09-20 20:40:50,055] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:40:50,056] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:40:50,056] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:40:50,056] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:40:50,074] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53837 )
  INFO root [2019-09-20 20:40:50,074] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53837, SOMAXCONN=5.
  INFO root [2019-09-20 20:40:50,074] - server-configs:
  INFO root [2019-09-20 20:40:50,074] - 	internalTcpAddr : 127.0.0.1:53837
  INFO root [2019-09-20 20:40:50,074] - 	componentID : 5000
  WARN root [2019-09-20 20:40:50,075] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:40:51,580] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 17960 ----
  INFO root [2019-09-20 20:40:51,581] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:40:51,581] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:40:51,581] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:40:52,022] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:40:52,024] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:40:59,163] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:41:00,665] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
  INFO root [2019-09-20 20:41:48,709] - 
  INFO root [2019-09-20 20:41:48,710] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:41:48,711] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:41:48,712] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:41:48,712] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:41:48,722] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53852 )
  INFO root [2019-09-20 20:41:48,722] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53852, SOMAXCONN=5.
  INFO root [2019-09-20 20:41:48,722] - server-configs:
  INFO root [2019-09-20 20:41:48,722] - 	internalTcpAddr : 127.0.0.1:53852
  INFO root [2019-09-20 20:41:48,722] - 	componentID : 5000
  WARN root [2019-09-20 20:41:48,723] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:41:50,230] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 18452 ----
  INFO root [2019-09-20 20:41:50,230] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:41:50,231] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:41:50,231] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:41:50,657] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:41:50,659] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:41:57,773] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:41:59,275] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:41:59,277] - Components::findComponents: receive error!
  WARN root [2019-09-20 20:41:59,278] - Components::findComponents: not found logger!
  INFO root [2019-09-20 20:42:00,293] - Components::findComponents: find dbmgr(1)...
  INFO root [2019-09-20 20:49:19,689] - 
  INFO root [2019-09-20 20:49:19,735] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:49:19,735] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:49:19,735] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:49:19,735] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:49:19,751] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49688 )
  INFO root [2019-09-20 20:49:19,751] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49688, SOMAXCONN=5.
  INFO root [2019-09-20 20:49:19,751] - server-configs:
  INFO root [2019-09-20 20:49:19,751] - 	internalTcpAddr : 127.0.0.1:49688
  INFO root [2019-09-20 20:49:19,751] - 	componentID : 5000
  WARN root [2019-09-20 20:49:19,751] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:49:21,266] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 8980 ----
  INFO root [2019-09-20 20:49:21,266] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:49:21,266] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:49:21,266] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:49:21,688] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:49:21,688] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:49:29,090] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:49:30,605] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:49:30,652] - Components::findComponents: receive error!
  WARN root [2019-09-20 20:49:30,668] - Components::findComponents: not found logger!
  INFO root [2019-09-20 20:50:47,331] - 
  INFO root [2019-09-20 20:50:47,331] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:50:47,331] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:50:47,331] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:50:47,331] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:50:47,331] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49723 )
  INFO root [2019-09-20 20:50:47,331] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49723, SOMAXCONN=5.
  INFO root [2019-09-20 20:50:47,331] - server-configs:
  INFO root [2019-09-20 20:50:47,331] - 	internalTcpAddr : 127.0.0.1:49723
  INFO root [2019-09-20 20:50:47,331] - 	componentID : 5000
  WARN root [2019-09-20 20:50:47,331] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:50:48,846] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 7640 ----
  INFO root [2019-09-20 20:50:48,846] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:50:48,846] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:50:48,846] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:50:49,268] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:50:49,283] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:50:56,538] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-20 20:50:58,053] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:50:58,053] - Components::findComponents: receive error!
  WARN root [2019-09-20 20:50:58,053] - Components::findComponents: not found logger!
  INFO root [2019-09-20 20:50:59,069] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-09-20 20:51:00,584] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:00,584] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:01,599] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-09-20 20:51:03,115] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:03,115] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:04,130] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-09-20 20:51:05,645] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:05,645] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:06,661] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-09-20 20:51:08,176] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:08,176] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:09,207] - Components::findComponents: find dbmgr(5)...
 ERROR root [2019-09-20 20:51:10,722] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:10,722] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:11,738] - Components::findComponents: find dbmgr(6)...
 ERROR root [2019-09-20 20:51:13,253] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:13,253] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:14,268] - Components::findComponents: find dbmgr(7)...
 ERROR root [2019-09-20 20:51:15,783] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:15,783] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:16,799] - Components::findComponents: find dbmgr(8)...
 ERROR root [2019-09-20 20:51:18,314] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-20 20:51:18,314] - Components::findComponents: receive error!
  INFO root [2019-09-20 20:51:19,329] - Components::findComponents: find dbmgr(9)...
  INFO root [2019-09-20 20:55:49,117] - 
  INFO root [2019-09-20 20:55:49,117] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 20:55:49,133] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 20:55:49,133] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 20:55:49,133] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 20:55:49,133] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:50145 )
  INFO root [2019-09-20 20:55:49,133] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:50145, SOMAXCONN=5.
  INFO root [2019-09-20 20:55:49,133] - server-configs:
  INFO root [2019-09-20 20:55:49,133] - 	internalTcpAddr : 10.12.231.110:50145
  INFO root [2019-09-20 20:55:49,133] - 	componentID : 5000
  WARN root [2019-09-20 20:55:49,133] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 20:55:50,648] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 8760 ----
  INFO root [2019-09-20 20:55:50,648] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 20:55:50,648] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 20:55:50,648] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 20:55:51,038] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 20:55:51,038] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 20:55:58,349] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 20:55:58,365] - Components::findComponents: found logger, addr:10.12.231.110:50150
  INFO root [2019-09-20 20:55:58,365] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 20:55:58,365] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 20:55:58,365] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 20:55:58,474] - Components::findComponents: found dbmgr, addr:10.12.231.110:50151
  INFO root [2019-09-20 20:55:58,474] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 20:55:58,474] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 20:55:58,474] - Components::findComponents: found dbmgr, addr:10.12.231.110:50151
  WARN root [2019-09-20 20:55:59,490] - Forwarding logs to logger[10.12.231.110:50150/0/0/0]...
 ERROR root [2019-09-20 21:01:26,028] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9151981452, lastReceivedTime=9084380951, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-20 21:01:26,031] - The following logs sent to logger failed:
  WARN root [2019-09-20 21:01:26,032] - ==> [2019-09-20 21:01:26 026] TCPPacketReceiver::processPendingEvents(10.12.231.110:50150): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 21:01:26,032] - ==> [2019-09-20 21:01:26 028] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9151981452, lastReceivedTime=9084380951, inactivityExceptionPeriod=599500064)
  WARN root [2019-09-20 21:01:26,103] - TCPPacketReceiver::processPendingEvents(10.12.231.110:50151): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 21:01:26,105] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9152752192, lastReceivedTime=9085029417, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-20 21:01:26,110] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 21:01:26,111] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 21:01:26,111] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 21:01:26,111] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-20 21:01:27,522] - 
  INFO root [2019-09-20 21:01:27,522] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-20 21:01:27,522] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-20 21:01:27,522] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-20 21:01:27,522] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-20 21:01:27,532] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:50328 )
  INFO root [2019-09-20 21:01:27,532] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:50328, SOMAXCONN=5.
  INFO root [2019-09-20 21:01:27,532] - server-configs:
  INFO root [2019-09-20 21:01:27,532] - 	internalTcpAddr : 10.12.231.110:50328
  INFO root [2019-09-20 21:01:27,532] - 	componentID : 5000
  WARN root [2019-09-20 21:01:27,532] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-20 21:01:29,036] - ---- baseappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: F070EF05A96B768F8BA788CE4BCBB097. Config: Debug X86. Built: 09:55:58 May  8 2019. AppID: 5000. UID: 41181. PID: 8548 ----
  INFO root [2019-09-20 21:01:29,037] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-20 21:01:29,037] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-20 21:01:29,037] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-20 21:01:29,466] - ---- baseappmgr is running ----
 DEBUG root [2019-09-20 21:01:29,473] - Components::process(): Request for the process of identity...
  INFO root [2019-09-20 21:01:36,742] - Components::findComponents: find logger(1)...
  INFO root [2019-09-20 21:01:36,822] - Components::findComponents: found logger, addr:10.12.231.110:50331
  INFO root [2019-09-20 21:01:36,822] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 21:01:36,822] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 21:01:36,822] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-20 21:01:36,932] - Components::findComponents: found dbmgr, addr:10.12.231.110:50327
  INFO root [2019-09-20 21:01:36,932] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-20 21:01:36,932] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-20 21:01:36,932] - Components::findComponents: found dbmgr, addr:10.12.231.110:50327
  WARN root [2019-09-20 21:01:37,948] - Forwarding logs to logger[10.12.231.110:50331/0/0/0]...
 ERROR root [2019-09-20 21:04:28,547] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10977215416, lastReceivedTime=10967927466, inactivityExceptionPeriod=599498338)
  INFO root [2019-09-20 21:04:28,557] - The following logs sent to logger failed:
  WARN root [2019-09-20 21:04:28,557] - ==> [2019-09-20 21:04:28 551] TCPPacketReceiver::processPendingEvents(10.12.231.110:50331): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 21:04:28,557] - ==> [2019-09-20 21:04:28 552] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10977215416, lastReceivedTime=10967927466, inactivityExceptionPeriod=599498338)
  WARN root [2019-09-20 21:04:28,642] - TCPPacketReceiver::processPendingEvents(10.12.231.110:50327): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-20 21:04:28,642] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10978151035, lastReceivedTime=10966530269, inactivityExceptionPeriod=599498338)
  INFO root [2019-09-20 21:04:28,667] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-20 21:04:28,667] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-20 21:04:28,667] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-20 21:04:28,667] - ThreadPool::destroy(): starting size 2.
