  INFO root [0x00004afc] [2019-09-20 14:29:51,125] - 
  INFO root [0x00004afc] [2019-09-20 14:29:51,125] - -----------------------------------------------------------------------------------------


  INFO root [0x00004afc] [2019-09-20 14:29:51,126] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00004afc] [2019-09-20 14:29:51,127] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00004afc] [2019-09-20 14:29:51,127] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00004afc] [2019-09-20 14:29:51,137] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00004afc] [2019-09-20 14:29:51,145] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00004afc] [2019-09-20 14:29:51,148] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00004afc] [2019-09-20 14:29:51,149] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00004afc] [2019-09-20 14:29:51,152] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:64946 )
  INFO root [0x00004afc] [2019-09-20 14:29:51,152] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:64946, SOMAXCONN=128.
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - server-configs:
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	gameUpdateHertz : 10
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	entryScriptFile : kbemain
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	internalTcpAddr : 192.168.43.114:64946
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00004afc] [2019-09-20 14:29:51,153] - 	componentID : 7001
  WARN root [0x00004afc] [2019-09-20 14:29:51,297] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00004afc] [2019-09-20 14:29:52,802] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 5708 ----
  INFO root [0x00004afc] [2019-09-20 14:29:52,803] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00004afc] [2019-09-20 14:29:52,803] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004afc] [2019-09-20 14:29:52,804] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00004afc] [2019-09-20 14:29:53,003] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00004afc] [2019-09-20 14:29:53,004] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004afc] [2019-09-20 14:29:53,155] - loaded entity-script:Account(1).
 DEBUG root [0x00004afc] [2019-09-20 14:29:53,155] - loaded entity-script:Hall(2).
 DEBUG root [0x00004afc] [2019-09-20 14:29:53,156] - loaded entity-script:Room(3).
  INFO root [0x00004afc] [2019-09-20 14:29:53,158] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00004afc] [2019-09-20 14:29:53,159] - TelnetServer server is running on port 40000
  INFO root [0x00004afc] [2019-09-20 14:29:53,591] - ---- baseapp is running ----
 DEBUG root [0x00004afc] [2019-09-20 14:29:53,591] - Components::process(): Request for the process of identity...
  WARN root [0x00004afc] [2019-09-20 14:29:59,694] - EntityApp::checkTickPeriod: tick took 6103% (6.10 seconds)!
  INFO root [0x00004afc] [2019-09-20 14:30:00,791] - Components::findComponents: find logger(1)...
  INFO root [0x00004afc] [2019-09-20 14:30:00,822] - Components::findComponents: found logger, addr:192.168.43.114:64943
  INFO root [0x00004afc] [2019-09-20 14:30:00,823] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004afc] [2019-09-20 14:30:00,823] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004afc] [2019-09-20 14:30:00,824] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004afc] [2019-09-20 14:30:00,926] - Components::findComponents: found dbmgr, addr:192.168.43.114:64939
  INFO root [0x00004afc] [2019-09-20 14:30:00,927] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004afc] [2019-09-20 14:30:00,927] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004afc] [2019-09-20 14:30:00,927] - Components::findComponents: found dbmgr, addr:192.168.43.114:64939
  WARN root [0x00004afc] [2019-09-20 14:30:01,927] - EntityApp::checkTickPeriod: tick took 1236% (1.24 seconds)!
  WARN root [0x00004afc] [2019-09-20 14:30:01,928] - Forwarding logs to logger[192.168.43.114:64943/0/0/0]...
 ERROR root [0x00004afc] [2019-09-20 14:32:08,394] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525853276283, lastReceivedTime=1525677837222, inactivityExceptionPeriod=599491496)
  INFO root [0x00004afc] [2019-09-20 14:32:08,401] - The following logs sent to logger failed:
  WARN root [0x00004afc] [2019-09-20 14:32:08,401] - ==> [2019-09-20 14:32:08 394] TCPPacketReceiver::processPendingEvents(192.168.43.114:64943): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004afc] [2019-09-20 14:32:08,402] - ==> [2019-09-20 14:32:08 396] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525853276283, lastReceivedTime=1525677837222, inactivityExceptionPeriod=599491496)
  WARN root [0x00004afc] [2019-09-20 14:32:08,487] - TCPPacketReceiver::processPendingEvents(192.168.43.114:64939): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004afc] [2019-09-20 14:32:08,492] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1525854253349, lastReceivedTime=1525676432628, inactivityExceptionPeriod=599491496)
  INFO root [0x00004afc] [2019-09-20 14:32:08,502] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00004afc] [2019-09-20 14:32:08,503] - onBaseAppShutDown: state=0
  INFO root [0x00004afc] [2019-09-20 14:32:08,503] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00004afc] [2019-09-20 14:32:08,503] - onBaseAppShutDown: state=1
  INFO root [0x00004afc] [2019-09-20 14:32:08,503] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00004afc] [2019-09-20 14:32:08,504] - onBaseAppShutDown: state=2
 ERROR root [0x00004afc] [2019-09-20 14:32:08,516] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00004afc] [2019-09-20 14:32:08,517] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00004afc] [2019-09-20 14:32:08,518] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x00004afc] [2019-09-20 14:32:08,519] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00004afc] [2019-09-20 14:32:08,521] - Account::~Account(): 2002
 DEBUG root [0x00004afc] [2019-09-20 14:32:08,521] - Account::~Account(): 2003
 DEBUG root [0x00004afc] [2019-09-20 14:32:08,521] - Room::~Room(): 2004
 DEBUG root [0x00004afc] [2019-09-20 14:32:08,521] - Hall::~Hall(): 2001
  INFO root [0x00004afc] [2019-09-20 14:32:08,538] - Script::uninstall(): is successfully!
 DEBUG root [0x00004afc] [2019-09-20 14:32:08,538] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002a44] [2019-09-20 14:32:32,189] - 
  INFO root [0x00002a44] [2019-09-20 14:32:32,190] - -----------------------------------------------------------------------------------------


  INFO root [0x00002a44] [2019-09-20 14:32:32,191] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002a44] [2019-09-20 14:32:32,191] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00002a44] [2019-09-20 14:32:32,191] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002a44] [2019-09-20 14:32:32,203] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00002a44] [2019-09-20 14:32:32,204] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00002a44] [2019-09-20 14:32:32,207] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00002a44] [2019-09-20 14:32:32,208] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00002a44] [2019-09-20 14:32:32,211] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65018 )
  INFO root [0x00002a44] [2019-09-20 14:32:32,211] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65018, SOMAXCONN=128.
  INFO root [0x00002a44] [2019-09-20 14:32:32,211] - server-configs:
  INFO root [0x00002a44] [2019-09-20 14:32:32,211] - 	gameUpdateHertz : 10
  INFO root [0x00002a44] [2019-09-20 14:32:32,212] - 	entryScriptFile : kbemain
  INFO root [0x00002a44] [2019-09-20 14:32:32,212] - 	internalTcpAddr : 192.168.43.114:65018
  INFO root [0x00002a44] [2019-09-20 14:32:32,212] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00002a44] [2019-09-20 14:32:32,212] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00002a44] [2019-09-20 14:32:32,212] - 	componentID : 7001
  WARN root [0x00002a44] [2019-09-20 14:32:32,400] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00002a44] [2019-09-20 14:32:32,725] - Components::findLogger: found logger, addr:192.168.43.114:65015
  INFO root [0x00002a44] [2019-09-20 14:32:32,725] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00002a44] [2019-09-20 14:32:32,725] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002a44] [2019-09-20 14:32:32,731] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 11228 ----
  INFO root [0x00002a44] [2019-09-20 14:32:32,732] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00002a44] [2019-09-20 14:32:32,732] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002a44] [2019-09-20 14:32:32,732] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00002a44] [2019-09-20 14:32:33,064] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00002a44] [2019-09-20 14:32:33,065] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002a44] [2019-09-20 14:32:33,206] - loaded entity-script:Account(1).
 DEBUG root [0x00002a44] [2019-09-20 14:32:33,206] - loaded entity-script:Hall(2).
 DEBUG root [0x00002a44] [2019-09-20 14:32:33,206] - loaded entity-script:Room(3).
  INFO root [0x00002a44] [2019-09-20 14:32:33,209] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002a44] [2019-09-20 14:32:33,209] - TelnetServer server is running on port 40000
  INFO root [0x00002a44] [2019-09-20 14:32:33,655] - ---- baseapp is running ----
 DEBUG root [0x00002a44] [2019-09-20 14:32:33,655] - Components::process(): Request for the process of identity...
  WARN root [0x00002a44] [2019-09-20 14:32:39,766] - Forwarding logs to logger[192.168.43.114:65015/0/0/0]...
 ERROR root [0x00002a44] [2019-09-20 14:34:43,102] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527400346153, lastReceivedTime=1527290320537, inactivityExceptionPeriod=599494629)
  INFO root [0x00002a44] [2019-09-20 14:34:43,105] - The following logs sent to logger failed:
  WARN root [0x00002a44] [2019-09-20 14:34:43,105] - ==> [2019-09-20 14:34:43 097] TCPPacketReceiver::processPendingEvents(192.168.43.114:65015): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a44] [2019-09-20 14:34:43,106] - ==> [2019-09-20 14:34:43 103] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527400346153, lastReceivedTime=1527290320537, inactivityExceptionPeriod=599494629)
  WARN root [0x00002a44] [2019-09-20 14:34:43,183] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65017): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002a44] [2019-09-20 14:34:43,186] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1527401191120, lastReceivedTime=1527291482003, inactivityExceptionPeriod=599494629)
  INFO root [0x00002a44] [2019-09-20 14:34:43,188] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002a44] [2019-09-20 14:34:43,189] - onBaseAppShutDown: state=0
  INFO root [0x00002a44] [2019-09-20 14:34:43,189] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002a44] [2019-09-20 14:34:43,189] - onBaseAppShutDown: state=1
  INFO root [0x00002a44] [2019-09-20 14:34:43,190] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002a44] [2019-09-20 14:34:43,190] - onBaseAppShutDown: state=2
 ERROR root [0x00002a44] [2019-09-20 14:34:43,202] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00002a44] [2019-09-20 14:34:43,203] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002a44] [2019-09-20 14:34:43,204] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x00002a44] [2019-09-20 14:34:43,204] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002a44] [2019-09-20 14:34:43,205] - Account::~Account(): 2002
 DEBUG root [0x00002a44] [2019-09-20 14:34:43,206] - Account::~Account(): 2003
 DEBUG root [0x00002a44] [2019-09-20 14:34:43,206] - Room::~Room(): 2004
 DEBUG root [0x00002a44] [2019-09-20 14:34:43,206] - Hall::~Hall(): 2001
  INFO root [0x00002a44] [2019-09-20 14:34:43,221] - Script::uninstall(): is successfully!
 DEBUG root [0x00002a44] [2019-09-20 14:34:43,221] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000022e4] [2019-09-20 14:36:23,162] - 
  INFO root [0x000022e4] [2019-09-20 14:36:23,163] - -----------------------------------------------------------------------------------------


  INFO root [0x000022e4] [2019-09-20 14:36:23,167] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000022e4] [2019-09-20 14:36:23,167] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000022e4] [2019-09-20 14:36:23,167] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000022e4] [2019-09-20 14:36:23,179] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000022e4] [2019-09-20 14:36:23,179] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000022e4] [2019-09-20 14:36:23,185] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000022e4] [2019-09-20 14:36:23,186] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65100 )
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65100, SOMAXCONN=128.
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - server-configs:
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - 	gameUpdateHertz : 10
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - 	entryScriptFile : kbemain
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - 	internalTcpAddr : 192.168.43.114:65100
  INFO root [0x000022e4] [2019-09-20 14:36:23,190] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000022e4] [2019-09-20 14:36:23,191] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000022e4] [2019-09-20 14:36:23,191] - 	componentID : 7001
  WARN root [0x000022e4] [2019-09-20 14:36:23,361] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000022e4] [2019-09-20 14:36:24,867] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 1064 ----
  INFO root [0x000022e4] [2019-09-20 14:36:24,868] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000022e4] [2019-09-20 14:36:24,868] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000022e4] [2019-09-20 14:36:24,868] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000022e4] [2019-09-20 14:36:25,071] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000022e4] [2019-09-20 14:36:25,071] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000022e4] [2019-09-20 14:36:25,189] - loaded entity-script:Account(1).
 DEBUG root [0x000022e4] [2019-09-20 14:36:25,189] - loaded entity-script:Hall(2).
 DEBUG root [0x000022e4] [2019-09-20 14:36:25,190] - loaded entity-script:Room(3).
  INFO root [0x000022e4] [2019-09-20 14:36:25,192] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000022e4] [2019-09-20 14:36:25,193] - TelnetServer server is running on port 40000
  INFO root [0x000022e4] [2019-09-20 14:36:25,743] - ---- baseapp is running ----
 DEBUG root [0x000022e4] [2019-09-20 14:36:25,744] - Components::process(): Request for the process of identity...
  WARN root [0x000022e4] [2019-09-20 14:36:31,875] - EntityApp::checkTickPeriod: tick took 6132% (6.13 seconds)!
  INFO root [0x000022e4] [2019-09-20 14:36:32,943] - Components::findComponents: find logger(1)...
  INFO root [0x000022e4] [2019-09-20 14:36:32,995] - Components::findComponents: found logger, addr:192.168.43.114:65104
  INFO root [0x000022e4] [2019-09-20 14:36:32,995] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000022e4] [2019-09-20 14:36:32,995] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000022e4] [2019-09-20 14:36:32,998] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000022e4] [2019-09-20 14:36:32,999] - Components::findComponents: found logger, addr:192.168.43.114:65104
  INFO root [0x000022e4] [2019-09-20 14:36:33,002] - Components::findComponents: found dbmgr, addr:192.168.43.114:65103
  INFO root [0x000022e4] [2019-09-20 14:36:33,003] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000022e4] [2019-09-20 14:36:33,003] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000022e4] [2019-09-20 14:36:33,104] - Components::findComponents: found dbmgr, addr:192.168.43.114:65103
  WARN root [0x000022e4] [2019-09-20 14:36:34,104] - EntityApp::checkTickPeriod: tick took 1260% (1.26 seconds)!
  WARN root [0x000022e4] [2019-09-20 14:36:34,105] - Forwarding logs to logger[192.168.43.114:65104/0/0/0]...
 ERROR root [0x000022e4] [2019-09-20 14:39:17,858] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530147906796, lastReceivedTime=1529902277032, inactivityExceptionPeriod=599494501)
  INFO root [0x000022e4] [2019-09-20 14:39:17,862] - The following logs sent to logger failed:
  WARN root [0x000022e4] [2019-09-20 14:39:17,862] - ==> [2019-09-20 14:39:17 858] TCPPacketReceiver::processPendingEvents(192.168.43.114:65104): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000022e4] [2019-09-20 14:39:17,862] - ==> [2019-09-20 14:39:17 859] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530147906796, lastReceivedTime=1529902277032, inactivityExceptionPeriod=599494501)
  WARN root [0x000022e4] [2019-09-20 14:39:17,938] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65103): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000022e4] [2019-09-20 14:39:17,940] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1530148720653, lastReceivedTime=1529902340733, inactivityExceptionPeriod=599494501)
  INFO root [0x000022e4] [2019-09-20 14:39:17,944] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000022e4] [2019-09-20 14:39:17,948] - onBaseAppShutDown: state=0
  INFO root [0x000022e4] [2019-09-20 14:39:17,949] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000022e4] [2019-09-20 14:39:17,949] - onBaseAppShutDown: state=1
  INFO root [0x000022e4] [2019-09-20 14:39:17,949] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000022e4] [2019-09-20 14:39:17,949] - onBaseAppShutDown: state=2
 ERROR root [0x000022e4] [2019-09-20 14:39:17,961] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000022e4] [2019-09-20 14:39:17,961] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000022e4] [2019-09-20 14:39:17,962] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x000022e4] [2019-09-20 14:39:17,962] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000022e4] [2019-09-20 14:39:17,964] - Account::~Account(): 2002
 DEBUG root [0x000022e4] [2019-09-20 14:39:17,964] - Account::~Account(): 2003
 DEBUG root [0x000022e4] [2019-09-20 14:39:17,964] - Room::~Room(): 2004
 DEBUG root [0x000022e4] [2019-09-20 14:39:17,964] - Hall::~Hall(): 2001
  INFO root [0x000022e4] [2019-09-20 14:39:17,979] - Script::uninstall(): is successfully!
 DEBUG root [0x000022e4] [2019-09-20 14:39:17,979] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000023d8] [2019-09-20 14:39:19,510] - 
  INFO root [0x000023d8] [2019-09-20 14:39:19,511] - -----------------------------------------------------------------------------------------


  INFO root [0x000023d8] [2019-09-20 14:39:19,512] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000023d8] [2019-09-20 14:39:19,512] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000023d8] [2019-09-20 14:39:19,512] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000023d8] [2019-09-20 14:39:19,525] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000023d8] [2019-09-20 14:39:19,525] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000023d8] [2019-09-20 14:39:19,531] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000023d8] [2019-09-20 14:39:19,532] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000023d8] [2019-09-20 14:39:19,535] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:65169 )
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:65169, SOMAXCONN=128.
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - server-configs:
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - 	gameUpdateHertz : 10
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - 	entryScriptFile : kbemain
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - 	internalTcpAddr : 192.168.43.114:65169
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000023d8] [2019-09-20 14:39:19,536] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000023d8] [2019-09-20 14:39:19,537] - 	componentID : 7001
  WARN root [0x000023d8] [2019-09-20 14:39:19,702] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000023d8] [2019-09-20 14:39:19,992] - Components::findLogger: found logger, addr:192.168.43.114:65166
  INFO root [0x000023d8] [2019-09-20 14:39:19,992] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000023d8] [2019-09-20 14:39:19,992] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000023d8] [2019-09-20 14:39:19,997] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 18380 ----
  INFO root [0x000023d8] [2019-09-20 14:39:19,998] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000023d8] [2019-09-20 14:39:19,998] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000023d8] [2019-09-20 14:39:19,998] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000023d8] [2019-09-20 14:39:20,194] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000023d8] [2019-09-20 14:39:20,194] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000023d8] [2019-09-20 14:39:20,314] - loaded entity-script:Account(1).
 DEBUG root [0x000023d8] [2019-09-20 14:39:20,315] - loaded entity-script:Hall(2).
 DEBUG root [0x000023d8] [2019-09-20 14:39:20,315] - loaded entity-script:Room(3).
  INFO root [0x000023d8] [2019-09-20 14:39:20,318] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000023d8] [2019-09-20 14:39:20,318] - TelnetServer server is running on port 40000
  INFO root [0x000023d8] [2019-09-20 14:39:20,783] - ---- baseapp is running ----
 DEBUG root [0x000023d8] [2019-09-20 14:39:20,783] - Components::process(): Request for the process of identity...
  WARN root [0x000023d8] [2019-09-20 14:39:26,901] - Forwarding logs to logger[192.168.43.114:65166/0/0/0]...
 ERROR root [0x000023d8] [2019-09-20 14:45:28,039] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533849720137, lastReceivedTime=1533764499342, inactivityExceptionPeriod=599493286)
  INFO root [0x000023d8] [2019-09-20 14:45:28,043] - The following logs sent to logger failed:
  WARN root [0x000023d8] [2019-09-20 14:45:28,044] - ==> [2019-09-20 14:45:28 038] TCPPacketReceiver::processPendingEvents(192.168.43.114:65166): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000023d8] [2019-09-20 14:45:28,045] - ==> [2019-09-20 14:45:28 040] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533849720137, lastReceivedTime=1533764499342, inactivityExceptionPeriod=599493286)
  WARN root [0x000023d8] [2019-09-20 14:45:28,118] - TCPPacketReceiver::processPendingEvents(192.168.43.114:65163): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000023d8] [2019-09-20 14:45:28,120] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1533850527166, lastReceivedTime=1533763555822, inactivityExceptionPeriod=599493286)
  INFO root [0x000023d8] [2019-09-20 14:45:28,126] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000023d8] [2019-09-20 14:45:28,126] - onBaseAppShutDown: state=0
  INFO root [0x000023d8] [2019-09-20 14:45:28,127] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000023d8] [2019-09-20 14:45:28,127] - onBaseAppShutDown: state=1
  INFO root [0x000023d8] [2019-09-20 14:45:28,127] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000023d8] [2019-09-20 14:45:28,127] - onBaseAppShutDown: state=2
 ERROR root [0x000023d8] [2019-09-20 14:45:28,140] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000023d8] [2019-09-20 14:45:28,141] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000023d8] [2019-09-20 14:45:28,142] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x000023d8] [2019-09-20 14:45:28,143] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000023d8] [2019-09-20 14:45:28,144] - Account::~Account(): 2
 DEBUG root [0x000023d8] [2019-09-20 14:45:28,144] - Account::~Account(): 3
 DEBUG root [0x000023d8] [2019-09-20 14:45:28,144] - Room::~Room(): 4
 DEBUG root [0x000023d8] [2019-09-20 14:45:28,144] - Hall::~Hall(): 1
  INFO root [0x000023d8] [2019-09-20 14:45:28,160] - Script::uninstall(): is successfully!
 DEBUG root [0x000023d8] [2019-09-20 14:45:28,160] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00003688] [2019-09-20 14:58:07,810] - 
  INFO root [0x00003688] [2019-09-20 14:58:07,810] - -----------------------------------------------------------------------------------------


  INFO root [0x00003688] [2019-09-20 14:58:07,811] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003688] [2019-09-20 14:58:07,811] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00003688] [2019-09-20 14:58:07,812] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003688] [2019-09-20 14:58:07,827] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00003688] [2019-09-20 14:58:07,827] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00003688] [2019-09-20 14:58:07,831] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00003688] [2019-09-20 14:58:07,831] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49575 )
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49575, SOMAXCONN=128.
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - server-configs:
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - 	gameUpdateHertz : 10
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - 	entryScriptFile : kbemain
  INFO root [0x00003688] [2019-09-20 14:58:07,835] - 	internalTcpAddr : 192.168.43.114:49575
  INFO root [0x00003688] [2019-09-20 14:58:07,836] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00003688] [2019-09-20 14:58:07,836] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00003688] [2019-09-20 14:58:07,836] - 	componentID : 7001
  WARN root [0x00003688] [2019-09-20 14:58:08,026] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00003688] [2019-09-20 14:58:09,586] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 10484 ----
  INFO root [0x00003688] [2019-09-20 14:58:09,591] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00003688] [2019-09-20 14:58:09,591] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003688] [2019-09-20 14:58:09,592] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003688] [2019-09-20 14:58:09,807] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003688] [2019-09-20 14:58:09,808] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003688] [2019-09-20 14:58:09,930] - loaded entity-script:Account(1).
 DEBUG root [0x00003688] [2019-09-20 14:58:09,931] - loaded entity-script:Hall(2).
 DEBUG root [0x00003688] [2019-09-20 14:58:09,931] - loaded entity-script:Room(3).
  INFO root [0x00003688] [2019-09-20 14:58:09,934] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003688] [2019-09-20 14:58:09,934] - TelnetServer server is running on port 40000
  INFO root [0x00003688] [2019-09-20 14:58:10,393] - ---- baseapp is running ----
 DEBUG root [0x00003688] [2019-09-20 14:58:10,393] - Components::process(): Request for the process of identity...
  WARN root [0x00003688] [2019-09-20 14:58:16,508] - EntityApp::checkTickPeriod: tick took 6115% (6.11 seconds)!
  INFO root [0x00003688] [2019-09-20 14:58:17,594] - Components::findComponents: find logger(1)...
  INFO root [0x00003688] [2019-09-20 14:58:17,643] - Components::findComponents: found logger, addr:192.168.43.114:49572
  INFO root [0x00003688] [2019-09-20 14:58:17,643] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00003688] [2019-09-20 14:58:17,643] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003688] [2019-09-20 14:58:17,644] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00003688] [2019-09-20 14:58:17,747] - Components::findComponents: found dbmgr, addr:192.168.43.114:49574
  INFO root [0x00003688] [2019-09-20 14:58:17,747] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00003688] [2019-09-20 14:58:17,747] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00003688] [2019-09-20 14:58:17,747] - Components::findComponents: found dbmgr, addr:192.168.43.114:49574
  WARN root [0x00003688] [2019-09-20 14:58:18,748] - EntityApp::checkTickPeriod: tick took 1254% (1.25 seconds)!
  WARN root [0x00003688] [2019-09-20 14:58:18,749] - Forwarding logs to logger[192.168.43.114:49572/0/0/0]...
 ERROR root [0x00003688] [2019-09-20 14:59:44,610] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542415425382, lastReceivedTime=1542346609701, inactivityExceptionPeriod=599493734)
  INFO root [0x00003688] [2019-09-20 14:59:44,615] - The following logs sent to logger failed:
  WARN root [0x00003688] [2019-09-20 14:59:44,615] - ==> [2019-09-20 14:59:44 601] TCPPacketReceiver::processPendingEvents(192.168.43.114:49572): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003688] [2019-09-20 14:59:44,615] - ==> [2019-09-20 14:59:44 611] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542415425382, lastReceivedTime=1542346609701, inactivityExceptionPeriod=599493734)
  WARN root [0x00003688] [2019-09-20 14:59:44,730] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49574): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00003688] [2019-09-20 14:59:44,737] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1542416694637, lastReceivedTime=1542347339522, inactivityExceptionPeriod=599493734)
  INFO root [0x00003688] [2019-09-20 14:59:44,744] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00003688] [2019-09-20 14:59:44,746] - onBaseAppShutDown: state=0
  INFO root [0x00003688] [2019-09-20 14:59:44,746] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00003688] [2019-09-20 14:59:44,746] - onBaseAppShutDown: state=1
  INFO root [0x00003688] [2019-09-20 14:59:44,746] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00003688] [2019-09-20 14:59:44,746] - onBaseAppShutDown: state=2
 ERROR root [0x00003688] [2019-09-20 14:59:44,762] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00003688] [2019-09-20 14:59:44,763] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00003688] [2019-09-20 14:59:44,764] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x00003688] [2019-09-20 14:59:44,764] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00003688] [2019-09-20 14:59:44,766] - Account::~Account(): 2
 DEBUG root [0x00003688] [2019-09-20 14:59:44,767] - Account::~Account(): 3
 DEBUG root [0x00003688] [2019-09-20 14:59:44,768] - Room::~Room(): 4
 DEBUG root [0x00003688] [2019-09-20 14:59:44,768] - Hall::~Hall(): 1
  INFO root [0x00003688] [2019-09-20 14:59:44,797] - Script::uninstall(): is successfully!
 DEBUG root [0x00003688] [2019-09-20 14:59:44,797] - ThreadPool::destroy(): starting size 2.
  WARN root [0x00003688] [2019-09-20 14:59:45,101] - ThreadPool::destroy(): waiting for thread(2)[0xa7cf60,0xa7d100,], try=1
  INFO root [0x0000340c] [2019-09-20 15:04:19,926] - 
  INFO root [0x0000340c] [2019-09-20 15:04:19,937] - -----------------------------------------------------------------------------------------


  INFO root [0x0000340c] [2019-09-20 15:04:19,940] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000340c] [2019-09-20 15:04:19,940] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x0000340c] [2019-09-20 15:04:19,940] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000340c] [2019-09-20 15:04:19,974] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x0000340c] [2019-09-20 15:04:19,974] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x0000340c] [2019-09-20 15:04:19,978] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x0000340c] [2019-09-20 15:04:19,978] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x0000340c] [2019-09-20 15:04:19,981] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49744 )
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49744, SOMAXCONN=128.
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - server-configs:
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	gameUpdateHertz : 10
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	entryScriptFile : kbemain
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	internalTcpAddr : 192.168.43.114:49744
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x0000340c] [2019-09-20 15:04:19,982] - 	componentID : 7001
  WARN root [0x0000340c] [2019-09-20 15:04:20,173] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x0000340c] [2019-09-20 15:04:20,547] - Components::findLogger: found logger, addr:192.168.43.114:49738
  INFO root [0x0000340c] [2019-09-20 15:04:20,547] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x0000340c] [2019-09-20 15:04:20,547] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000340c] [2019-09-20 15:04:20,553] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 4304 ----
  INFO root [0x0000340c] [2019-09-20 15:04:20,555] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x0000340c] [2019-09-20 15:04:20,561] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000340c] [2019-09-20 15:04:20,561] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000340c] [2019-09-20 15:04:20,800] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000340c] [2019-09-20 15:04:20,800] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000340c] [2019-09-20 15:04:20,979] - loaded entity-script:Account(1).
 DEBUG root [0x0000340c] [2019-09-20 15:04:20,979] - loaded entity-script:Hall(2).
 DEBUG root [0x0000340c] [2019-09-20 15:04:20,979] - loaded entity-script:Room(3).
  INFO root [0x0000340c] [2019-09-20 15:04:20,982] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000340c] [2019-09-20 15:04:20,983] - TelnetServer server is running on port 40000
  INFO root [0x0000340c] [2019-09-20 15:04:21,467] - ---- baseapp is running ----
 DEBUG root [0x0000340c] [2019-09-20 15:04:21,468] - Components::process(): Request for the process of identity...
  WARN root [0x0000340c] [2019-09-20 15:04:27,594] - Forwarding logs to logger[192.168.43.114:49738/0/0/0]...
 ERROR root [0x0000340c] [2019-09-20 15:05:38,567] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545955001222, lastReceivedTime=1545768411657, inactivityExceptionPeriod=599491943)
  INFO root [0x0000340c] [2019-09-20 15:05:38,578] - The following logs sent to logger failed:
  WARN root [0x0000340c] [2019-09-20 15:05:38,578] - ==> [2019-09-20 15:05:38 564] TCPPacketReceiver::processPendingEvents(192.168.43.114:49738): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000340c] [2019-09-20 15:05:38,579] - ==> [2019-09-20 15:05:38 568] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545955001222, lastReceivedTime=1545768411657, inactivityExceptionPeriod=599491943)
  WARN root [0x0000340c] [2019-09-20 15:05:38,693] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49740): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000340c] [2019-09-20 15:05:38,695] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1545956280786, lastReceivedTime=1545769033640, inactivityExceptionPeriod=599491943)
  INFO root [0x0000340c] [2019-09-20 15:05:38,699] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000340c] [2019-09-20 15:05:38,702] - onBaseAppShutDown: state=0
  INFO root [0x0000340c] [2019-09-20 15:05:38,702] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000340c] [2019-09-20 15:05:38,702] - onBaseAppShutDown: state=1
  INFO root [0x0000340c] [2019-09-20 15:05:38,702] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000340c] [2019-09-20 15:05:38,702] - onBaseAppShutDown: state=2
 ERROR root [0x0000340c] [2019-09-20 15:05:38,725] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x0000340c] [2019-09-20 15:05:38,728] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000340c] [2019-09-20 15:05:38,730] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x0000340c] [2019-09-20 15:05:38,731] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000340c] [2019-09-20 15:05:38,731] - Account::~Account(): 3
 DEBUG root [0x0000340c] [2019-09-20 15:05:38,732] - Account::~Account(): 2
 DEBUG root [0x0000340c] [2019-09-20 15:05:38,732] - Room::~Room(): 4
 DEBUG root [0x0000340c] [2019-09-20 15:05:38,732] - Hall::~Hall(): 1
  INFO root [0x0000340c] [2019-09-20 15:05:38,772] - Script::uninstall(): is successfully!
 DEBUG root [0x0000340c] [2019-09-20 15:05:38,772] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000340c] [2019-09-20 15:05:39,075] - ThreadPool::destroy(): waiting for thread(2)[0x231caf8,0x231c410,], try=1
  INFO root [0x00004a7c] [2019-09-20 15:06:35,970] - 
  INFO root [0x00004a7c] [2019-09-20 15:06:35,971] - -----------------------------------------------------------------------------------------


  INFO root [0x00004a7c] [2019-09-20 15:06:35,972] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00004a7c] [2019-09-20 15:06:35,972] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00004a7c] [2019-09-20 15:06:35,972] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00004a7c] [2019-09-20 15:06:35,983] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00004a7c] [2019-09-20 15:06:35,983] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00004a7c] [2019-09-20 15:06:35,987] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00004a7c] [2019-09-20 15:06:35,987] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00004a7c] [2019-09-20 15:06:35,990] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49802 )
  INFO root [0x00004a7c] [2019-09-20 15:06:35,990] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49802, SOMAXCONN=128.
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - server-configs:
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	gameUpdateHertz : 10
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	entryScriptFile : kbemain
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	internalTcpAddr : 192.168.43.114:49802
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00004a7c] [2019-09-20 15:06:35,991] - 	componentID : 7001
  WARN root [0x00004a7c] [2019-09-20 15:06:36,136] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00004a7c] [2019-09-20 15:06:36,428] - Components::findLogger: found logger, addr:192.168.43.114:49800
  INFO root [0x00004a7c] [2019-09-20 15:06:36,428] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004a7c] [2019-09-20 15:06:36,429] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004a7c] [2019-09-20 15:06:36,434] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 7340 ----
  INFO root [0x00004a7c] [2019-09-20 15:06:36,434] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00004a7c] [2019-09-20 15:06:36,434] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004a7c] [2019-09-20 15:06:36,435] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00004a7c] [2019-09-20 15:06:36,634] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00004a7c] [2019-09-20 15:06:36,634] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004a7c] [2019-09-20 15:06:36,792] - loaded entity-script:Account(1).
 DEBUG root [0x00004a7c] [2019-09-20 15:06:36,792] - loaded entity-script:Hall(2).
 DEBUG root [0x00004a7c] [2019-09-20 15:06:36,792] - loaded entity-script:Room(3).
  INFO root [0x00004a7c] [2019-09-20 15:06:36,795] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00004a7c] [2019-09-20 15:06:36,795] - TelnetServer server is running on port 40000
  INFO root [0x00004a7c] [2019-09-20 15:06:37,247] - ---- baseapp is running ----
 DEBUG root [0x00004a7c] [2019-09-20 15:06:37,248] - Components::process(): Request for the process of identity...
  WARN root [0x00004a7c] [2019-09-20 15:06:43,354] - Forwarding logs to logger[192.168.43.114:49800/0/0/0]...
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,477] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548874093376, lastReceivedTime=1548629027516, inactivityExceptionPeriod=599478898)
  INFO root [0x00004a7c] [2019-09-20 15:10:30,482] - The following logs sent to logger failed:
  WARN root [0x00004a7c] [2019-09-20 15:10:30,483] - ==> [2019-09-20 15:10:30 477] TCPPacketReceiver::processPendingEvents(192.168.43.114:49800): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,483] - ==> [2019-09-20 15:10:30 478] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548874093376, lastReceivedTime=1548629027516, inactivityExceptionPeriod=599478898)
  WARN root [0x00004a7c] [2019-09-20 15:10:30,567] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49796): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,572] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1548875048198, lastReceivedTime=1548628433884, inactivityExceptionPeriod=599478898)
  INFO root [0x00004a7c] [2019-09-20 15:10:30,579] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00004a7c] [2019-09-20 15:10:30,580] - onBaseAppShutDown: state=0
  INFO root [0x00004a7c] [2019-09-20 15:10:30,580] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00004a7c] [2019-09-20 15:10:30,580] - onBaseAppShutDown: state=1
  INFO root [0x00004a7c] [2019-09-20 15:10:30,580] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00004a7c] [2019-09-20 15:10:30,580] - onBaseAppShutDown: state=2
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,595] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,596] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,596] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x00004a7c] [2019-09-20 15:10:30,597] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00004a7c] [2019-09-20 15:10:30,598] - Account::~Account(): 2
 DEBUG root [0x00004a7c] [2019-09-20 15:10:30,598] - Account::~Account(): 3
 DEBUG root [0x00004a7c] [2019-09-20 15:10:30,598] - Room::~Room(): 4
 DEBUG root [0x00004a7c] [2019-09-20 15:10:30,598] - Hall::~Hall(): 1
  INFO root [0x00004a7c] [2019-09-20 15:10:30,618] - Script::uninstall(): is successfully!
 DEBUG root [0x00004a7c] [2019-09-20 15:10:30,618] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000008b8] [2019-09-20 15:10:32,306] - 
  INFO root [0x000008b8] [2019-09-20 15:10:32,306] - -----------------------------------------------------------------------------------------


  INFO root [0x000008b8] [2019-09-20 15:10:32,307] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000008b8] [2019-09-20 15:10:32,308] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000008b8] [2019-09-20 15:10:32,308] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000008b8] [2019-09-20 15:10:32,319] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000008b8] [2019-09-20 15:10:32,320] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000008b8] [2019-09-20 15:10:32,324] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000008b8] [2019-09-20 15:10:32,324] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:49903 )
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:49903, SOMAXCONN=128.
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - server-configs:
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - 	gameUpdateHertz : 10
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - 	entryScriptFile : kbemain
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - 	internalTcpAddr : 192.168.43.114:49903
  INFO root [0x000008b8] [2019-09-20 15:10:32,328] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000008b8] [2019-09-20 15:10:32,329] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000008b8] [2019-09-20 15:10:32,329] - 	componentID : 7001
  WARN root [0x000008b8] [2019-09-20 15:10:32,520] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000008b8] [2019-09-20 15:10:32,911] - Components::findLogger: found logger, addr:192.168.43.114:49900
  INFO root [0x000008b8] [2019-09-20 15:10:32,911] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000008b8] [2019-09-20 15:10:32,911] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000008b8] [2019-09-20 15:10:32,916] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 9484 ----
  INFO root [0x000008b8] [2019-09-20 15:10:32,916] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000008b8] [2019-09-20 15:10:32,917] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000008b8] [2019-09-20 15:10:32,917] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000008b8] [2019-09-20 15:10:33,141] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000008b8] [2019-09-20 15:10:33,142] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000008b8] [2019-09-20 15:10:33,272] - loaded entity-script:Account(1).
 DEBUG root [0x000008b8] [2019-09-20 15:10:33,273] - loaded entity-script:Hall(2).
 DEBUG root [0x000008b8] [2019-09-20 15:10:33,273] - loaded entity-script:Room(3).
  INFO root [0x000008b8] [2019-09-20 15:10:33,276] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000008b8] [2019-09-20 15:10:33,276] - TelnetServer server is running on port 40000
  INFO root [0x000008b8] [2019-09-20 15:10:33,752] - ---- baseapp is running ----
 DEBUG root [0x000008b8] [2019-09-20 15:10:33,753] - Components::process(): Request for the process of identity...
  WARN root [0x000008b8] [2019-09-20 15:10:39,880] - Forwarding logs to logger[192.168.43.114:49900/0/0/0]...
 ERROR root [0x000008b8] [2019-09-20 15:21:40,266] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555571990790, lastReceivedTime=1555491735583, inactivityExceptionPeriod=599493030)
  INFO root [0x000008b8] [2019-09-20 15:21:40,272] - The following logs sent to logger failed:
  WARN root [0x000008b8] [2019-09-20 15:21:40,273] - ==> [2019-09-20 15:21:40 265] TCPPacketReceiver::processPendingEvents(192.168.43.114:49900): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000008b8] [2019-09-20 15:21:40,273] - ==> [2019-09-20 15:21:40 267] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555571990790, lastReceivedTime=1555491735583, inactivityExceptionPeriod=599493030)
  WARN root [0x000008b8] [2019-09-20 15:21:40,350] - TCPPacketReceiver::processPendingEvents(192.168.43.114:49901): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000008b8] [2019-09-20 15:21:40,351] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1555572839588, lastReceivedTime=1555491504631, inactivityExceptionPeriod=599493030)
  INFO root [0x000008b8] [2019-09-20 15:21:40,360] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000008b8] [2019-09-20 15:21:40,361] - onBaseAppShutDown: state=0
  INFO root [0x000008b8] [2019-09-20 15:21:40,361] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000008b8] [2019-09-20 15:21:40,361] - onBaseAppShutDown: state=1
  INFO root [0x000008b8] [2019-09-20 15:21:40,361] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000008b8] [2019-09-20 15:21:40,362] - onBaseAppShutDown: state=2
 ERROR root [0x000008b8] [2019-09-20 15:21:40,375] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000008b8] [2019-09-20 15:21:40,375] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000008b8] [2019-09-20 15:21:40,376] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x000008b8] [2019-09-20 15:21:40,377] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000008b8] [2019-09-20 15:21:40,378] - Account::~Account(): 2
 DEBUG root [0x000008b8] [2019-09-20 15:21:40,378] - Account::~Account(): 3
 DEBUG root [0x000008b8] [2019-09-20 15:21:40,378] - Room::~Room(): 4
 DEBUG root [0x000008b8] [2019-09-20 15:21:40,379] - Hall::~Hall(): 1
  INFO root [0x000008b8] [2019-09-20 15:21:40,398] - Script::uninstall(): is successfully!
 DEBUG root [0x000008b8] [2019-09-20 15:21:40,398] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000013d0] [2019-09-20 15:28:51,061] - 
  INFO root [0x000013d0] [2019-09-20 15:28:51,062] - -----------------------------------------------------------------------------------------


  INFO root [0x000013d0] [2019-09-20 15:28:51,063] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000013d0] [2019-09-20 15:28:51,063] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000013d0] [2019-09-20 15:28:51,063] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000013d0] [2019-09-20 15:28:51,085] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000013d0] [2019-09-20 15:28:51,085] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000013d0] [2019-09-20 15:28:51,091] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000013d0] [2019-09-20 15:28:51,092] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000013d0] [2019-09-20 15:28:51,095] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50515 )
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50515, SOMAXCONN=128.
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - server-configs:
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - 	gameUpdateHertz : 10
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - 	entryScriptFile : kbemain
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - 	internalTcpAddr : 192.168.43.114:50515
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000013d0] [2019-09-20 15:28:51,096] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000013d0] [2019-09-20 15:28:51,097] - 	componentID : 7001
  WARN root [0x000013d0] [2019-09-20 15:28:51,270] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000013d0] [2019-09-20 15:28:51,627] - Components::findLogger: found logger, addr:192.168.43.114:50510
  INFO root [0x000013d0] [2019-09-20 15:28:51,627] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000013d0] [2019-09-20 15:28:51,627] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000013d0] [2019-09-20 15:28:51,632] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 10408 ----
  INFO root [0x000013d0] [2019-09-20 15:28:51,632] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000013d0] [2019-09-20 15:28:51,633] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000013d0] [2019-09-20 15:28:51,633] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000013d0] [2019-09-20 15:28:51,835] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000013d0] [2019-09-20 15:28:51,835] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000013d0] [2019-09-20 15:28:51,960] - loaded entity-script:Account(1).
 DEBUG root [0x000013d0] [2019-09-20 15:28:51,960] - loaded entity-script:Hall(2).
 DEBUG root [0x000013d0] [2019-09-20 15:28:51,960] - loaded entity-script:Room(3).
  INFO root [0x000013d0] [2019-09-20 15:28:51,963] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000013d0] [2019-09-20 15:28:51,964] - TelnetServer server is running on port 40000
  INFO root [0x000013d0] [2019-09-20 15:28:52,408] - ---- baseapp is running ----
 DEBUG root [0x000013d0] [2019-09-20 15:28:52,409] - Components::process(): Request for the process of identity...
  WARN root [0x000013d0] [2019-09-20 15:28:58,528] - Forwarding logs to logger[192.168.43.114:50510/0/0/0]...
 ERROR root [0x000013d0] [2019-09-20 15:31:29,540] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561464721080, lastReceivedTime=1561379218353, inactivityExceptionPeriod=599491176)
  INFO root [0x000013d0] [2019-09-20 15:31:29,548] - The following logs sent to logger failed:
  WARN root [0x000013d0] [2019-09-20 15:31:29,548] - ==> [2019-09-20 15:31:29 539] TCPPacketReceiver::processPendingEvents(192.168.43.114:50510): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000013d0] [2019-09-20 15:31:29,548] - ==> [2019-09-20 15:31:29 540] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561464721080, lastReceivedTime=1561379218353, inactivityExceptionPeriod=599491176)
  WARN root [0x000013d0] [2019-09-20 15:31:29,637] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50507): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000013d0] [2019-09-20 15:31:29,637] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1561465696477, lastReceivedTime=1561378085724, inactivityExceptionPeriod=599491176)
  INFO root [0x000013d0] [2019-09-20 15:31:29,639] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000013d0] [2019-09-20 15:31:29,639] - onBaseAppShutDown: state=0
  INFO root [0x000013d0] [2019-09-20 15:31:29,640] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000013d0] [2019-09-20 15:31:29,640] - onBaseAppShutDown: state=1
  INFO root [0x000013d0] [2019-09-20 15:31:29,640] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000013d0] [2019-09-20 15:31:29,640] - onBaseAppShutDown: state=2
 ERROR root [0x000013d0] [2019-09-20 15:31:29,653] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000013d0] [2019-09-20 15:31:29,656] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000013d0] [2019-09-20 15:31:29,658] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x000013d0] [2019-09-20 15:31:29,659] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000013d0] [2019-09-20 15:31:29,660] - Account::~Account(): 2
 DEBUG root [0x000013d0] [2019-09-20 15:31:29,661] - Account::~Account(): 3
 DEBUG root [0x000013d0] [2019-09-20 15:31:29,661] - Room::~Room(): 4
 DEBUG root [0x000013d0] [2019-09-20 15:31:29,661] - Hall::~Hall(): 1
  INFO root [0x000013d0] [2019-09-20 15:31:29,684] - Script::uninstall(): is successfully!
 DEBUG root [0x000013d0] [2019-09-20 15:31:29,684] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00004550] [2019-09-20 15:31:31,543] - 
  INFO root [0x00004550] [2019-09-20 15:31:31,548] - -----------------------------------------------------------------------------------------


  INFO root [0x00004550] [2019-09-20 15:31:31,549] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00004550] [2019-09-20 15:31:31,549] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00004550] [2019-09-20 15:31:31,549] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00004550] [2019-09-20 15:31:31,590] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00004550] [2019-09-20 15:31:31,590] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00004550] [2019-09-20 15:31:31,594] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00004550] [2019-09-20 15:31:31,594] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00004550] [2019-09-20 15:31:31,598] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50585 )
  INFO root [0x00004550] [2019-09-20 15:31:31,598] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50585, SOMAXCONN=128.
  INFO root [0x00004550] [2019-09-20 15:31:31,598] - server-configs:
  INFO root [0x00004550] [2019-09-20 15:31:31,599] - 	gameUpdateHertz : 10
  INFO root [0x00004550] [2019-09-20 15:31:31,599] - 	entryScriptFile : kbemain
  INFO root [0x00004550] [2019-09-20 15:31:31,599] - 	internalTcpAddr : 192.168.43.114:50585
  INFO root [0x00004550] [2019-09-20 15:31:31,599] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00004550] [2019-09-20 15:31:31,600] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00004550] [2019-09-20 15:31:31,600] - 	componentID : 7001
  WARN root [0x00004550] [2019-09-20 15:31:31,816] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00004550] [2019-09-20 15:31:33,322] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 13476 ----
  INFO root [0x00004550] [2019-09-20 15:31:33,322] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00004550] [2019-09-20 15:31:33,323] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004550] [2019-09-20 15:31:33,323] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00004550] [2019-09-20 15:31:33,604] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00004550] [2019-09-20 15:31:33,604] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004550] [2019-09-20 15:31:33,821] - loaded entity-script:Account(1).
 DEBUG root [0x00004550] [2019-09-20 15:31:33,822] - loaded entity-script:Hall(2).
 DEBUG root [0x00004550] [2019-09-20 15:31:33,822] - loaded entity-script:Room(3).
  INFO root [0x00004550] [2019-09-20 15:31:33,826] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00004550] [2019-09-20 15:31:33,826] - TelnetServer server is running on port 40000
  INFO root [0x00004550] [2019-09-20 15:31:34,421] - ---- baseapp is running ----
 DEBUG root [0x00004550] [2019-09-20 15:31:34,422] - Components::process(): Request for the process of identity...
  WARN root [0x00004550] [2019-09-20 15:31:40,558] - EntityApp::checkTickPeriod: tick took 6136% (6.14 seconds)!
  INFO root [0x00004550] [2019-09-20 15:31:41,567] - Components::findComponents: find logger(1)...
  INFO root [0x00004550] [2019-09-20 15:31:41,600] - Components::findComponents: found logger, addr:192.168.43.114:50579
  INFO root [0x00004550] [2019-09-20 15:31:41,600] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004550] [2019-09-20 15:31:41,600] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004550] [2019-09-20 15:31:41,602] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004550] [2019-09-20 15:31:41,704] - Components::findComponents: found dbmgr, addr:192.168.43.114:50580
  INFO root [0x00004550] [2019-09-20 15:31:41,704] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004550] [2019-09-20 15:31:41,704] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004550] [2019-09-20 15:31:41,705] - Components::findComponents: found dbmgr, addr:192.168.43.114:50580
  WARN root [0x00004550] [2019-09-20 15:31:42,705] - Forwarding logs to logger[192.168.43.114:50579/0/0/0]...
 ERROR root [0x00004550] [2019-09-20 15:38:37,828] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565747603679, lastReceivedTime=1565683814613, inactivityExceptionPeriod=599466876)
  INFO root [0x00004550] [2019-09-20 15:38:37,834] - The following logs sent to logger failed:
  WARN root [0x00004550] [2019-09-20 15:38:37,835] - ==> [2019-09-20 15:38:37 826] TCPPacketReceiver::processPendingEvents(192.168.43.114:50579): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004550] [2019-09-20 15:38:37,835] - ==> [2019-09-20 15:38:37 829] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565747603679, lastReceivedTime=1565683814613, inactivityExceptionPeriod=599466876)
  WARN root [0x00004550] [2019-09-20 15:38:37,950] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50580): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004550] [2019-09-20 15:38:37,952] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1565748848646, lastReceivedTime=1565684972530, inactivityExceptionPeriod=599466876)
  INFO root [0x00004550] [2019-09-20 15:38:37,964] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00004550] [2019-09-20 15:38:37,965] - onBaseAppShutDown: state=0
  INFO root [0x00004550] [2019-09-20 15:38:37,965] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00004550] [2019-09-20 15:38:37,965] - onBaseAppShutDown: state=1
  INFO root [0x00004550] [2019-09-20 15:38:37,966] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00004550] [2019-09-20 15:38:37,966] - onBaseAppShutDown: state=2
 ERROR root [0x00004550] [2019-09-20 15:38:37,982] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00004550] [2019-09-20 15:38:37,984] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00004550] [2019-09-20 15:38:37,991] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x00004550] [2019-09-20 15:38:37,995] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00004550] [2019-09-20 15:38:37,998] - Account::~Account(): 2002
 DEBUG root [0x00004550] [2019-09-20 15:38:37,998] - Account::~Account(): 2003
 DEBUG root [0x00004550] [2019-09-20 15:38:37,998] - Room::~Room(): 2004
 DEBUG root [0x00004550] [2019-09-20 15:38:37,998] - Hall::~Hall(): 2001
  INFO root [0x00004550] [2019-09-20 15:38:38,025] - Script::uninstall(): is successfully!
 DEBUG root [0x00004550] [2019-09-20 15:38:38,026] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001d68] [2019-09-20 15:42:10,048] - 
  INFO root [0x00001d68] [2019-09-20 15:42:10,050] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d68] [2019-09-20 15:42:10,052] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001d68] [2019-09-20 15:42:10,052] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00001d68] [2019-09-20 15:42:10,052] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001d68] [2019-09-20 15:42:10,084] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00001d68] [2019-09-20 15:42:10,084] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00001d68] [2019-09-20 15:42:10,088] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00001d68] [2019-09-20 15:42:10,089] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00001d68] [2019-09-20 15:42:10,094] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:50888 )
  INFO root [0x00001d68] [2019-09-20 15:42:10,095] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:50888, SOMAXCONN=128.
  INFO root [0x00001d68] [2019-09-20 15:42:10,095] - server-configs:
  INFO root [0x00001d68] [2019-09-20 15:42:10,095] - 	gameUpdateHertz : 10
  INFO root [0x00001d68] [2019-09-20 15:42:10,096] - 	entryScriptFile : kbemain
  INFO root [0x00001d68] [2019-09-20 15:42:10,096] - 	internalTcpAddr : 192.168.43.114:50888
  INFO root [0x00001d68] [2019-09-20 15:42:10,096] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00001d68] [2019-09-20 15:42:10,096] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00001d68] [2019-09-20 15:42:10,097] - 	componentID : 7001
  WARN root [0x00001d68] [2019-09-20 15:42:10,291] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00001d68] [2019-09-20 15:42:10,739] - Components::findLogger: found logger, addr:192.168.43.114:50887
  INFO root [0x00001d68] [2019-09-20 15:42:10,740] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00001d68] [2019-09-20 15:42:10,740] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d68] [2019-09-20 15:42:10,745] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 11828 ----
  INFO root [0x00001d68] [2019-09-20 15:42:10,747] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00001d68] [2019-09-20 15:42:10,748] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d68] [2019-09-20 15:42:10,748] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001d68] [2019-09-20 15:42:10,952] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001d68] [2019-09-20 15:42:10,952] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001d68] [2019-09-20 15:42:11,084] - loaded entity-script:Account(1).
 DEBUG root [0x00001d68] [2019-09-20 15:42:11,084] - loaded entity-script:Hall(2).
 DEBUG root [0x00001d68] [2019-09-20 15:42:11,085] - loaded entity-script:Room(3).
  INFO root [0x00001d68] [2019-09-20 15:42:11,087] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001d68] [2019-09-20 15:42:11,088] - TelnetServer server is running on port 40000
  INFO root [0x00001d68] [2019-09-20 15:42:11,640] - ---- baseapp is running ----
 DEBUG root [0x00001d68] [2019-09-20 15:42:11,641] - Components::process(): Request for the process of identity...
  WARN root [0x00001d68] [2019-09-20 15:42:17,786] - Forwarding logs to logger[192.168.43.114:50887/0/0/0]...
 ERROR root [0x00001d68] [2019-09-20 15:44:43,768] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407002696, lastReceivedTime=1569370197956, inactivityExceptionPeriod=599493670)
  INFO root [0x00001d68] [2019-09-20 15:44:43,775] - The following logs sent to logger failed:
  WARN root [0x00001d68] [2019-09-20 15:44:43,776] - ==> [2019-09-20 15:44:43 767] TCPPacketReceiver::processPendingEvents(192.168.43.114:50887): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d68] [2019-09-20 15:44:43,776] - ==> [2019-09-20 15:44:43 768] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407002696, lastReceivedTime=1569370197956, inactivityExceptionPeriod=599493670)
  WARN root [0x00001d68] [2019-09-20 15:44:43,858] - TCPPacketReceiver::processPendingEvents(192.168.43.114:50882): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d68] [2019-09-20 15:44:43,860] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1569407927898, lastReceivedTime=1569369865879, inactivityExceptionPeriod=599493670)
  INFO root [0x00001d68] [2019-09-20 15:44:43,864] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001d68] [2019-09-20 15:44:43,866] - onBaseAppShutDown: state=0
  INFO root [0x00001d68] [2019-09-20 15:44:43,866] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001d68] [2019-09-20 15:44:43,867] - onBaseAppShutDown: state=1
  INFO root [0x00001d68] [2019-09-20 15:44:43,867] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001d68] [2019-09-20 15:44:43,867] - onBaseAppShutDown: state=2
 ERROR root [0x00001d68] [2019-09-20 15:44:43,882] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00001d68] [2019-09-20 15:44:43,883] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001d68] [2019-09-20 15:44:43,884] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x00001d68] [2019-09-20 15:44:43,884] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001d68] [2019-09-20 15:44:43,885] - Account::~Account(): 2
 DEBUG root [0x00001d68] [2019-09-20 15:44:43,887] - Account::~Account(): 3
 DEBUG root [0x00001d68] [2019-09-20 15:44:43,887] - Room::~Room(): 4
 DEBUG root [0x00001d68] [2019-09-20 15:44:43,887] - Hall::~Hall(): 1
  INFO root [0x00001d68] [2019-09-20 15:44:43,903] - Script::uninstall(): is successfully!
 DEBUG root [0x00001d68] [2019-09-20 15:44:43,903] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000421c] [2019-09-20 15:48:39,497] - 
  INFO root [0x0000421c] [2019-09-20 15:48:39,497] - -----------------------------------------------------------------------------------------


  INFO root [0x0000421c] [2019-09-20 15:48:39,498] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000421c] [2019-09-20 15:48:39,498] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x0000421c] [2019-09-20 15:48:39,498] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000421c] [2019-09-20 15:48:39,509] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x0000421c] [2019-09-20 15:48:39,510] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x0000421c] [2019-09-20 15:48:39,514] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x0000421c] [2019-09-20 15:48:39,514] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x0000421c] [2019-09-20 15:48:39,517] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51008 )
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51008, SOMAXCONN=128.
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - server-configs:
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	gameUpdateHertz : 10
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	entryScriptFile : kbemain
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	internalTcpAddr : 192.168.43.114:51008
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x0000421c] [2019-09-20 15:48:39,518] - 	componentID : 7001
  WARN root [0x0000421c] [2019-09-20 15:48:39,728] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x0000421c] [2019-09-20 15:48:40,216] - Components::findLogger: found logger, addr:192.168.43.114:51005
  INFO root [0x0000421c] [2019-09-20 15:48:40,217] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x0000421c] [2019-09-20 15:48:40,217] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x0000421c] [2019-09-20 15:48:40,225] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 19136 ----
  INFO root [0x0000421c] [2019-09-20 15:48:40,225] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x0000421c] [2019-09-20 15:48:40,225] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000421c] [2019-09-20 15:48:40,226] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000421c] [2019-09-20 15:48:40,479] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000421c] [2019-09-20 15:48:40,480] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000421c] [2019-09-20 15:48:40,641] - loaded entity-script:Account(1).
 DEBUG root [0x0000421c] [2019-09-20 15:48:40,641] - loaded entity-script:Hall(2).
 DEBUG root [0x0000421c] [2019-09-20 15:48:40,643] - loaded entity-script:Room(3).
  INFO root [0x0000421c] [2019-09-20 15:48:40,645] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000421c] [2019-09-20 15:48:40,646] - TelnetServer server is running on port 40000
  INFO root [0x0000421c] [2019-09-20 15:48:41,227] - ---- baseapp is running ----
 DEBUG root [0x0000421c] [2019-09-20 15:48:41,232] - Components::process(): Request for the process of identity...
  WARN root [0x0000421c] [2019-09-20 15:48:47,402] - Forwarding logs to logger[192.168.43.114:51005/0/0/0]...
 ERROR root [0x0000421c] [2019-09-20 15:54:33,682] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575306149699, lastReceivedTime=1575063894132, inactivityExceptionPeriod=599475445)
  INFO root [0x0000421c] [2019-09-20 15:54:33,686] - The following logs sent to logger failed:
  WARN root [0x0000421c] [2019-09-20 15:54:33,686] - ==> [2019-09-20 15:54:33 681] TCPPacketReceiver::processPendingEvents(192.168.43.114:51005): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000421c] [2019-09-20 15:54:33,687] - ==> [2019-09-20 15:54:33 683] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575306149699, lastReceivedTime=1575063894132, inactivityExceptionPeriod=599475445)
  WARN root [0x0000421c] [2019-09-20 15:54:33,803] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x0000421c] [2019-09-20 15:54:33,813] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1575307459347, lastReceivedTime=1575063932601, inactivityExceptionPeriod=599475445)
  INFO root [0x0000421c] [2019-09-20 15:54:33,825] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x0000421c] [2019-09-20 15:54:33,828] - onBaseAppShutDown: state=0
  INFO root [0x0000421c] [2019-09-20 15:54:33,830] - Shutdowner::onShutdown: shutting down
S_INFO root [0x0000421c] [2019-09-20 15:54:33,831] - onBaseAppShutDown: state=1
  INFO root [0x0000421c] [2019-09-20 15:54:33,831] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x0000421c] [2019-09-20 15:54:33,831] - onBaseAppShutDown: state=2
 ERROR root [0x0000421c] [2019-09-20 15:54:33,853] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x0000421c] [2019-09-20 15:54:33,862] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x0000421c] [2019-09-20 15:54:33,864] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x0000421c] [2019-09-20 15:54:33,866] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x0000421c] [2019-09-20 15:54:33,867] - Account::~Account(): 2002
 DEBUG root [0x0000421c] [2019-09-20 15:54:33,867] - Account::~Account(): 2003
 DEBUG root [0x0000421c] [2019-09-20 15:54:33,867] - Room::~Room(): 2004
 DEBUG root [0x0000421c] [2019-09-20 15:54:33,868] - Hall::~Hall(): 2001
  INFO root [0x0000421c] [2019-09-20 15:54:33,890] - Script::uninstall(): is successfully!
 DEBUG root [0x0000421c] [2019-09-20 15:54:33,892] - ThreadPool::destroy(): starting size 2.
  WARN root [0x0000421c] [2019-09-20 15:54:34,194] - ThreadPool::destroy(): waiting for thread(2)[0x22a23d0,0x22a2438,], try=1
  INFO root [0x000027c4] [2019-09-20 15:58:28,512] - 
  INFO root [0x000027c4] [2019-09-20 15:58:28,514] - -----------------------------------------------------------------------------------------


  INFO root [0x000027c4] [2019-09-20 15:58:28,515] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000027c4] [2019-09-20 15:58:28,515] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000027c4] [2019-09-20 15:58:28,515] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000027c4] [2019-09-20 15:58:28,533] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000027c4] [2019-09-20 15:58:28,533] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000027c4] [2019-09-20 15:58:28,537] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000027c4] [2019-09-20 15:58:28,537] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000027c4] [2019-09-20 15:58:28,541] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51261 )
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51261, SOMAXCONN=128.
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - server-configs:
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - 	gameUpdateHertz : 10
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - 	entryScriptFile : kbemain
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - 	internalTcpAddr : 192.168.43.114:51261
  INFO root [0x000027c4] [2019-09-20 15:58:28,542] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000027c4] [2019-09-20 15:58:28,543] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000027c4] [2019-09-20 15:58:28,543] - 	componentID : 7001
  WARN root [0x000027c4] [2019-09-20 15:58:28,696] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000027c4] [2019-09-20 15:58:29,076] - Components::findLogger: found logger, addr:192.168.43.114:51259
  INFO root [0x000027c4] [2019-09-20 15:58:29,077] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000027c4] [2019-09-20 15:58:29,077] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027c4] [2019-09-20 15:58:29,082] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 3780 ----
  INFO root [0x000027c4] [2019-09-20 15:58:29,082] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000027c4] [2019-09-20 15:58:29,083] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000027c4] [2019-09-20 15:58:29,083] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000027c4] [2019-09-20 15:58:29,291] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000027c4] [2019-09-20 15:58:29,291] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000027c4] [2019-09-20 15:58:29,414] - loaded entity-script:Account(1).
 DEBUG root [0x000027c4] [2019-09-20 15:58:29,414] - loaded entity-script:Hall(2).
 DEBUG root [0x000027c4] [2019-09-20 15:58:29,414] - loaded entity-script:Room(3).
  INFO root [0x000027c4] [2019-09-20 15:58:29,417] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000027c4] [2019-09-20 15:58:29,417] - TelnetServer server is running on port 40000
  INFO root [0x000027c4] [2019-09-20 15:58:29,865] - ---- baseapp is running ----
 DEBUG root [0x000027c4] [2019-09-20 15:58:29,866] - Components::process(): Request for the process of identity...
  WARN root [0x000027c4] [2019-09-20 15:58:35,983] - Forwarding logs to logger[192.168.43.114:51259/0/0/0]...
 ERROR root [0x000027c4] [2019-09-20 16:00:55,593] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579125260655, lastReceivedTime=1578854563815, inactivityExceptionPeriod=599493030)
  INFO root [0x000027c4] [2019-09-20 16:00:55,600] - The following logs sent to logger failed:
  WARN root [0x000027c4] [2019-09-20 16:00:55,600] - ==> [2019-09-20 16:00:55 588] TCPPacketReceiver::processPendingEvents(192.168.43.114:51259): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027c4] [2019-09-20 16:00:55,600] - ==> [2019-09-20 16:00:55 595] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579125260655, lastReceivedTime=1578854563815, inactivityExceptionPeriod=599493030)
  WARN root [0x000027c4] [2019-09-20 16:00:55,701] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51260): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027c4] [2019-09-20 16:00:55,707] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1579126395595, lastReceivedTime=1578854653945, inactivityExceptionPeriod=599493030)
  INFO root [0x000027c4] [2019-09-20 16:00:55,711] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000027c4] [2019-09-20 16:00:55,712] - onBaseAppShutDown: state=0
  INFO root [0x000027c4] [2019-09-20 16:00:55,712] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000027c4] [2019-09-20 16:00:55,713] - onBaseAppShutDown: state=1
  INFO root [0x000027c4] [2019-09-20 16:00:55,713] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000027c4] [2019-09-20 16:00:55,714] - onBaseAppShutDown: state=2
 ERROR root [0x000027c4] [2019-09-20 16:00:55,726] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000027c4] [2019-09-20 16:00:55,728] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000027c4] [2019-09-20 16:00:55,734] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x000027c4] [2019-09-20 16:00:55,734] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000027c4] [2019-09-20 16:00:55,735] - Account::~Account(): 2002
 DEBUG root [0x000027c4] [2019-09-20 16:00:55,736] - Account::~Account(): 2003
 DEBUG root [0x000027c4] [2019-09-20 16:00:55,736] - Room::~Room(): 2004
 DEBUG root [0x000027c4] [2019-09-20 16:00:55,736] - Hall::~Hall(): 2001
  INFO root [0x000027c4] [2019-09-20 16:00:55,764] - Script::uninstall(): is successfully!
 DEBUG root [0x000027c4] [2019-09-20 16:00:55,765] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002254] [2019-09-20 16:01:37,087] - 
  INFO root [0x00002254] [2019-09-20 16:01:37,089] - -----------------------------------------------------------------------------------------


  INFO root [0x00002254] [2019-09-20 16:01:37,090] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002254] [2019-09-20 16:01:37,091] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00002254] [2019-09-20 16:01:37,091] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002254] [2019-09-20 16:01:37,102] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00002254] [2019-09-20 16:01:37,102] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00002254] [2019-09-20 16:01:37,106] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00002254] [2019-09-20 16:01:37,107] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00002254] [2019-09-20 16:01:37,116] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:51353 )
  INFO root [0x00002254] [2019-09-20 16:01:37,116] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:51353, SOMAXCONN=128.
  INFO root [0x00002254] [2019-09-20 16:01:37,116] - server-configs:
  INFO root [0x00002254] [2019-09-20 16:01:37,116] - 	gameUpdateHertz : 10
  INFO root [0x00002254] [2019-09-20 16:01:37,120] - 	entryScriptFile : kbemain
  INFO root [0x00002254] [2019-09-20 16:01:37,121] - 	internalTcpAddr : 192.168.43.114:51353
  INFO root [0x00002254] [2019-09-20 16:01:37,121] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00002254] [2019-09-20 16:01:37,121] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00002254] [2019-09-20 16:01:37,121] - 	componentID : 7001
  WARN root [0x00002254] [2019-09-20 16:01:37,294] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00002254] [2019-09-20 16:01:37,662] - Components::findLogger: found logger, addr:192.168.43.114:51352
  INFO root [0x00002254] [2019-09-20 16:01:37,662] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00002254] [2019-09-20 16:01:37,662] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002254] [2019-09-20 16:01:37,667] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 5740 ----
  INFO root [0x00002254] [2019-09-20 16:01:37,668] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00002254] [2019-09-20 16:01:37,668] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002254] [2019-09-20 16:01:37,668] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00002254] [2019-09-20 16:01:37,865] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00002254] [2019-09-20 16:01:37,865] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002254] [2019-09-20 16:01:37,988] - loaded entity-script:Account(1).
 DEBUG root [0x00002254] [2019-09-20 16:01:37,988] - loaded entity-script:Hall(2).
 DEBUG root [0x00002254] [2019-09-20 16:01:37,989] - loaded entity-script:Room(3).
  INFO root [0x00002254] [2019-09-20 16:01:37,991] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002254] [2019-09-20 16:01:37,992] - TelnetServer server is running on port 40000
  INFO root [0x00002254] [2019-09-20 16:01:38,456] - ---- baseapp is running ----
 DEBUG root [0x00002254] [2019-09-20 16:01:38,456] - Components::process(): Request for the process of identity...
  WARN root [0x00002254] [2019-09-20 16:01:44,562] - Forwarding logs to logger[192.168.43.114:51352/0/0/0]...
 ERROR root [0x00002254] [2019-09-20 16:08:58,693] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583956249921, lastReceivedTime=1583740591668, inactivityExceptionPeriod=599472759)
  INFO root [0x00002254] [2019-09-20 16:08:58,697] - The following logs sent to logger failed:
  WARN root [0x00002254] [2019-09-20 16:08:58,698] - ==> [2019-09-20 16:08:58 689] TCPPacketReceiver::processPendingEvents(192.168.43.114:51352): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002254] [2019-09-20 16:08:58,698] - ==> [2019-09-20 16:08:58 693] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583956249921, lastReceivedTime=1583740591668, inactivityExceptionPeriod=599472759)
  WARN root [0x00002254] [2019-09-20 16:08:58,772] - TCPPacketReceiver::processPendingEvents(192.168.43.114:51359): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002254] [2019-09-20 16:08:58,774] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1583957068297, lastReceivedTime=1583741155169, inactivityExceptionPeriod=599472759)
  INFO root [0x00002254] [2019-09-20 16:08:58,780] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002254] [2019-09-20 16:08:58,782] - onBaseAppShutDown: state=0
  INFO root [0x00002254] [2019-09-20 16:08:58,782] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002254] [2019-09-20 16:08:58,782] - onBaseAppShutDown: state=1
  INFO root [0x00002254] [2019-09-20 16:08:58,783] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002254] [2019-09-20 16:08:58,783] - onBaseAppShutDown: state=2
 DEBUG root [0x00002254] [2019-09-20 16:08:58,796] - Hall::~Hall(): 1
  INFO root [0x00002254] [2019-09-20 16:08:58,810] - Script::uninstall(): is successfully!
 DEBUG root [0x00002254] [2019-09-20 16:08:58,810] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00004ae0] [2019-09-20 17:04:57,448] - 
  INFO root [0x00004ae0] [2019-09-20 17:04:57,455] - -----------------------------------------------------------------------------------------


  INFO root [0x00004ae0] [2019-09-20 17:04:57,456] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00004ae0] [2019-09-20 17:04:57,456] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00004ae0] [2019-09-20 17:04:57,456] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00004ae0] [2019-09-20 17:04:57,481] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x00004ae0] [2019-09-20 17:04:57,481] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x00004ae0] [2019-09-20 17:04:57,486] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x00004ae0] [2019-09-20 17:04:57,486] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52514 )
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52514, SOMAXCONN=128.
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - server-configs:
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - 	gameUpdateHertz : 10
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - 	entryScriptFile : kbemain
  INFO root [0x00004ae0] [2019-09-20 17:04:57,489] - 	internalTcpAddr : 192.168.43.114:52514
  INFO root [0x00004ae0] [2019-09-20 17:04:57,490] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x00004ae0] [2019-09-20 17:04:57,490] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x00004ae0] [2019-09-20 17:04:57,490] - 	componentID : 7001
  WARN root [0x00004ae0] [2019-09-20 17:04:57,651] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00004ae0] [2019-09-20 17:04:59,156] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 16120 ----
  INFO root [0x00004ae0] [2019-09-20 17:04:59,157] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00004ae0] [2019-09-20 17:04:59,157] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00004ae0] [2019-09-20 17:04:59,158] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00004ae0] [2019-09-20 17:04:59,577] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00004ae0] [2019-09-20 17:04:59,577] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00004ae0] [2019-09-20 17:04:59,696] - loaded entity-script:Account(1).
 DEBUG root [0x00004ae0] [2019-09-20 17:04:59,696] - loaded entity-script:Hall(2).
 DEBUG root [0x00004ae0] [2019-09-20 17:04:59,696] - loaded entity-script:Room(3).
  INFO root [0x00004ae0] [2019-09-20 17:04:59,699] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00004ae0] [2019-09-20 17:04:59,700] - TelnetServer server is running on port 40000
  INFO root [0x00004ae0] [2019-09-20 17:05:00,138] - ---- baseapp is running ----
 DEBUG root [0x00004ae0] [2019-09-20 17:05:00,139] - Components::process(): Request for the process of identity...
  WARN root [0x00004ae0] [2019-09-20 17:05:06,258] - EntityApp::checkTickPeriod: tick took 6120% (6.12 seconds)!
  INFO root [0x00004ae0] [2019-09-20 17:05:07,267] - Components::findComponents: find logger(1)...
  INFO root [0x00004ae0] [2019-09-20 17:05:07,351] - Components::findComponents: found logger, addr:192.168.43.114:52513
  INFO root [0x00004ae0] [2019-09-20 17:05:07,352] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004ae0] [2019-09-20 17:05:07,352] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004ae0] [2019-09-20 17:05:07,353] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00004ae0] [2019-09-20 17:05:07,456] - Components::findComponents: found dbmgr, addr:192.168.43.114:52509
  INFO root [0x00004ae0] [2019-09-20 17:05:07,456] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00004ae0] [2019-09-20 17:05:07,456] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00004ae0] [2019-09-20 17:05:07,457] - Components::findComponents: found dbmgr, addr:192.168.43.114:52509
  WARN root [0x00004ae0] [2019-09-20 17:05:08,457] - Forwarding logs to logger[192.168.43.114:52513/0/0/0]...
 ERROR root [0x00004ae0] [2019-09-20 17:06:31,353] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618482854678, lastReceivedTime=1618444236406, inactivityExceptionPeriod=599471864)
  INFO root [0x00004ae0] [2019-09-20 17:06:31,358] - The following logs sent to logger failed:
  WARN root [0x00004ae0] [2019-09-20 17:06:31,358] - ==> [2019-09-20 17:06:31 352] TCPPacketReceiver::processPendingEvents(192.168.43.114:52513): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004ae0] [2019-09-20 17:06:31,358] - ==> [2019-09-20 17:06:31 354] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618482854678, lastReceivedTime=1618444236406, inactivityExceptionPeriod=599471864)
  WARN root [0x00004ae0] [2019-09-20 17:06:31,444] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52509): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00004ae0] [2019-09-20 17:06:31,447] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1618483798460, lastReceivedTime=1618443912710, inactivityExceptionPeriod=599471864)
  INFO root [0x00004ae0] [2019-09-20 17:06:31,459] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00004ae0] [2019-09-20 17:06:31,459] - onBaseAppShutDown: state=0
  INFO root [0x00004ae0] [2019-09-20 17:06:31,459] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00004ae0] [2019-09-20 17:06:31,460] - onBaseAppShutDown: state=1
  INFO root [0x00004ae0] [2019-09-20 17:06:31,460] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00004ae0] [2019-09-20 17:06:31,460] - onBaseAppShutDown: state=2
 ERROR root [0x00004ae0] [2019-09-20 17:06:31,485] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00004ae0] [2019-09-20 17:06:31,486] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00004ae0] [2019-09-20 17:06:31,488] - Account::~Account(): 2002
 DEBUG root [0x00004ae0] [2019-09-20 17:06:31,488] - Hall::~Hall(): 2001
  INFO root [0x00004ae0] [2019-09-20 17:06:31,504] - Script::uninstall(): is successfully!
 DEBUG root [0x00004ae0] [2019-09-20 17:06:31,504] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000009bc] [2019-09-20 17:06:33,119] - 
  INFO root [0x000009bc] [2019-09-20 17:06:33,120] - -----------------------------------------------------------------------------------------


  INFO root [0x000009bc] [2019-09-20 17:06:33,121] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000009bc] [2019-09-20 17:06:33,122] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000009bc] [2019-09-20 17:06:33,122] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000009bc] [2019-09-20 17:06:33,139] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000009bc] [2019-09-20 17:06:33,139] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000009bc] [2019-09-20 17:06:33,143] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000009bc] [2019-09-20 17:06:33,143] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000009bc] [2019-09-20 17:06:33,146] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52568 )
  INFO root [0x000009bc] [2019-09-20 17:06:33,146] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52568, SOMAXCONN=128.
  INFO root [0x000009bc] [2019-09-20 17:06:33,146] - server-configs:
  INFO root [0x000009bc] [2019-09-20 17:06:33,146] - 	gameUpdateHertz : 10
  INFO root [0x000009bc] [2019-09-20 17:06:33,147] - 	entryScriptFile : kbemain
  INFO root [0x000009bc] [2019-09-20 17:06:33,147] - 	internalTcpAddr : 192.168.43.114:52568
  INFO root [0x000009bc] [2019-09-20 17:06:33,147] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000009bc] [2019-09-20 17:06:33,147] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000009bc] [2019-09-20 17:06:33,147] - 	componentID : 7001
  WARN root [0x000009bc] [2019-09-20 17:06:33,328] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000009bc] [2019-09-20 17:06:33,624] - Components::findLogger: found logger, addr:192.168.43.114:52567
  INFO root [0x000009bc] [2019-09-20 17:06:33,624] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000009bc] [2019-09-20 17:06:33,625] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000009bc] [2019-09-20 17:06:33,636] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 14544 ----
  INFO root [0x000009bc] [2019-09-20 17:06:33,636] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000009bc] [2019-09-20 17:06:33,637] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000009bc] [2019-09-20 17:06:33,637] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000009bc] [2019-09-20 17:06:33,844] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000009bc] [2019-09-20 17:06:33,844] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000009bc] [2019-09-20 17:06:33,969] - loaded entity-script:Account(1).
 DEBUG root [0x000009bc] [2019-09-20 17:06:33,969] - loaded entity-script:Hall(2).
 DEBUG root [0x000009bc] [2019-09-20 17:06:33,970] - loaded entity-script:Room(3).
  INFO root [0x000009bc] [2019-09-20 17:06:33,972] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000009bc] [2019-09-20 17:06:33,973] - TelnetServer server is running on port 40000
  INFO root [0x000009bc] [2019-09-20 17:06:34,409] - ---- baseapp is running ----
 DEBUG root [0x000009bc] [2019-09-20 17:06:34,410] - Components::process(): Request for the process of identity...
  WARN root [0x000009bc] [2019-09-20 17:06:40,527] - Forwarding logs to logger[192.168.43.114:52567/0/0/0]...
 ERROR root [0x000009bc] [2019-09-20 17:09:05,622] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620025551003, lastReceivedTime=1620000622147, inactivityExceptionPeriod=599480753)
  INFO root [0x000009bc] [2019-09-20 17:09:05,630] - The following logs sent to logger failed:
  WARN root [0x000009bc] [2019-09-20 17:09:05,630] - ==> [2019-09-20 17:09:05 619] TCPPacketReceiver::processPendingEvents(192.168.43.114:52567): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000009bc] [2019-09-20 17:09:05,631] - ==> [2019-09-20 17:09:05 623] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620025551003, lastReceivedTime=1620000622147, inactivityExceptionPeriod=599480753)
  WARN root [0x000009bc] [2019-09-20 17:09:05,718] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52560): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000009bc] [2019-09-20 17:09:05,726] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620026586109, lastReceivedTime=1619999590780, inactivityExceptionPeriod=599480753)
  INFO root [0x000009bc] [2019-09-20 17:09:05,738] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000009bc] [2019-09-20 17:09:05,745] - onBaseAppShutDown: state=0
  INFO root [0x000009bc] [2019-09-20 17:09:05,745] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000009bc] [2019-09-20 17:09:05,746] - onBaseAppShutDown: state=1
  INFO root [0x000009bc] [2019-09-20 17:09:05,747] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000009bc] [2019-09-20 17:09:05,748] - onBaseAppShutDown: state=2
 ERROR root [0x000009bc] [2019-09-20 17:09:05,761] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000009bc] [2019-09-20 17:09:05,761] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000009bc] [2019-09-20 17:09:05,763] - Account::~Account(): 2
 DEBUG root [0x000009bc] [2019-09-20 17:09:05,764] - Hall::~Hall(): 1
  INFO root [0x000009bc] [2019-09-20 17:09:05,780] - Script::uninstall(): is successfully!
 DEBUG root [0x000009bc] [2019-09-20 17:09:05,780] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000046c0] [2019-09-20 17:09:07,383] - 
  INFO root [0x000046c0] [2019-09-20 17:09:07,385] - -----------------------------------------------------------------------------------------


  INFO root [0x000046c0] [2019-09-20 17:09:07,386] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000046c0] [2019-09-20 17:09:07,386] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000046c0] [2019-09-20 17:09:07,386] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000046c0] [2019-09-20 17:09:07,449] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20015 )
  INFO root [0x000046c0] [2019-09-20 17:09:07,449] - NetworkInterface::initialize(EXTERNAL-TCP): address 192.168.43.114:20015, SOMAXCONN=128.
  INFO root [0x000046c0] [2019-09-20 17:09:07,452] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:20005 )
  INFO root [0x000046c0] [2019-09-20 17:09:07,452] - NetworkInterface::initialize(EXTERNAL-UDP): address 192.168.43.114:20005, SOMAXCONN=128.
  INFO root [0x000046c0] [2019-09-20 17:09:07,455] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.43.114 ( 192.168.43.114:52618 )
  INFO root [0x000046c0] [2019-09-20 17:09:07,455] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.43.114:52618, SOMAXCONN=128.
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - server-configs:
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	gameUpdateHertz : 10
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	entryScriptFile : kbemain
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	internalTcpAddr : 192.168.43.114:52618
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	externalTcpAddr : 192.168.43.114:20015
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	externalUdpAddr : 192.168.43.114:20005
  INFO root [0x000046c0] [2019-09-20 17:09:07,456] - 	componentID : 7001
  WARN root [0x000046c0] [2019-09-20 17:09:07,625] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000046c0] [2019-09-20 17:09:07,970] - Components::findLogger: found logger, addr:192.168.43.114:52620
  INFO root [0x000046c0] [2019-09-20 17:09:07,971] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000046c0] [2019-09-20 17:09:07,971] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000046c0] [2019-09-20 17:09:07,977] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 11076 ----
  INFO root [0x000046c0] [2019-09-20 17:09:07,978] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000046c0] [2019-09-20 17:09:07,979] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000046c0] [2019-09-20 17:09:07,979] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000046c0] [2019-09-20 17:09:08,338] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000046c0] [2019-09-20 17:09:08,339] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000046c0] [2019-09-20 17:09:08,468] - loaded entity-script:Account(1).
 DEBUG root [0x000046c0] [2019-09-20 17:09:08,468] - loaded entity-script:Hall(2).
 DEBUG root [0x000046c0] [2019-09-20 17:09:08,469] - loaded entity-script:Room(3).
  INFO root [0x000046c0] [2019-09-20 17:09:08,471] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000046c0] [2019-09-20 17:09:08,472] - TelnetServer server is running on port 40000
  INFO root [0x000046c0] [2019-09-20 17:09:08,908] - ---- baseapp is running ----
 DEBUG root [0x000046c0] [2019-09-20 17:09:08,909] - Components::process(): Request for the process of identity...
  WARN root [0x000046c0] [2019-09-20 17:09:15,040] - Forwarding logs to logger[192.168.43.114:52620/0/0/0]...
 ERROR root [0x000046c0] [2019-09-20 17:10:33,173] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620901050763, lastReceivedTime=1620644057552, inactivityExceptionPeriod=599493286)
  INFO root [0x000046c0] [2019-09-20 17:10:33,176] - The following logs sent to logger failed:
  WARN root [0x000046c0] [2019-09-20 17:10:33,176] - ==> [2019-09-20 17:10:33 172] TCPPacketReceiver::processPendingEvents(192.168.43.114:52620): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046c0] [2019-09-20 17:10:33,177] - ==> [2019-09-20 17:10:33 173] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620901050763, lastReceivedTime=1620644057552, inactivityExceptionPeriod=599493286)
  WARN root [0x000046c0] [2019-09-20 17:10:33,266] - TCPPacketReceiver::processPendingEvents(192.168.43.114:52617): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000046c0] [2019-09-20 17:10:33,270] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1620902024153, lastReceivedTime=1620643867319, inactivityExceptionPeriod=599493286)
  INFO root [0x000046c0] [2019-09-20 17:10:33,275] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000046c0] [2019-09-20 17:10:33,276] - onBaseAppShutDown: state=0
  INFO root [0x000046c0] [2019-09-20 17:10:33,277] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000046c0] [2019-09-20 17:10:33,277] - onBaseAppShutDown: state=1
  INFO root [0x000046c0] [2019-09-20 17:10:33,277] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000046c0] [2019-09-20 17:10:33,277] - onBaseAppShutDown: state=2
 ERROR root [0x000046c0] [2019-09-20 17:10:33,290] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000046c0] [2019-09-20 17:10:33,290] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000046c0] [2019-09-20 17:10:33,291] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x000046c0] [2019-09-20 17:10:33,291] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000046c0] [2019-09-20 17:10:33,292] - Account::~Account(): 2
 DEBUG root [0x000046c0] [2019-09-20 17:10:33,293] - Account::~Account(): 3
 DEBUG root [0x000046c0] [2019-09-20 17:10:33,293] - Room::~Room(): 4
 DEBUG root [0x000046c0] [2019-09-20 17:10:33,293] - Hall::~Hall(): 1
  INFO root [0x000046c0] [2019-09-20 17:10:33,312] - Script::uninstall(): is successfully!
 DEBUG root [0x000046c0] [2019-09-20 17:10:33,312] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00002ef0] [2019-09-20 19:33:31,674] - 
  INFO root [0x00002ef0] [2019-09-20 19:33:31,687] - -----------------------------------------------------------------------------------------


  INFO root [0x00002ef0] [2019-09-20 19:33:31,688] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002ef0] [2019-09-20 19:33:31,688] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00002ef0] [2019-09-20 19:33:31,688] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002ef0] [2019-09-20 19:33:31,699] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20015 )
  INFO root [0x00002ef0] [2019-09-20 19:33:31,699] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20015, SOMAXCONN=128.
  INFO root [0x00002ef0] [2019-09-20 19:33:31,704] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20005 )
  INFO root [0x00002ef0] [2019-09-20 19:33:31,704] - NetworkInterface::initialize(EXTERNAL-UDP): address 10.12.231.110:20005, SOMAXCONN=128.
  INFO root [0x00002ef0] [2019-09-20 19:33:31,707] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53606 )
  INFO root [0x00002ef0] [2019-09-20 19:33:31,707] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53606, SOMAXCONN=128.
  INFO root [0x00002ef0] [2019-09-20 19:33:31,708] - server-configs:
  INFO root [0x00002ef0] [2019-09-20 19:33:31,708] - 	gameUpdateHertz : 10
  INFO root [0x00002ef0] [2019-09-20 19:33:31,708] - 	entryScriptFile : kbemain
  INFO root [0x00002ef0] [2019-09-20 19:33:31,708] - 	internalTcpAddr : 10.12.231.110:53606
  INFO root [0x00002ef0] [2019-09-20 19:33:31,708] - 	externalTcpAddr : 10.12.231.110:20015
  INFO root [0x00002ef0] [2019-09-20 19:33:31,709] - 	externalUdpAddr : 10.12.231.110:20005
  INFO root [0x00002ef0] [2019-09-20 19:33:31,709] - 	componentID : 7001
  WARN root [0x00002ef0] [2019-09-20 19:33:31,866] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [0x00002ef0] [2019-09-20 19:33:32,224] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20291, errorno=10048
  INFO root [0x00002ef0] [2019-09-20 19:33:32,228] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 12348 ----
  INFO root [0x00002ef0] [2019-09-20 19:33:32,229] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00002ef0] [2019-09-20 19:33:32,229] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002ef0] [2019-09-20 19:33:32,230] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00002ef0] [2019-09-20 19:33:32,467] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00002ef0] [2019-09-20 19:33:32,468] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002ef0] [2019-09-20 19:33:32,602] - loaded entity-script:Account(1).
 DEBUG root [0x00002ef0] [2019-09-20 19:33:32,602] - loaded entity-script:Hall(2).
 DEBUG root [0x00002ef0] [2019-09-20 19:33:32,602] - loaded entity-script:Room(3).
  INFO root [0x00002ef0] [2019-09-20 19:33:32,605] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002ef0] [2019-09-20 19:33:32,605] - TelnetServer server is running on port 40000
  INFO root [0x00002ef0] [2019-09-20 19:33:33,060] - ---- baseapp is running ----
 DEBUG root [0x00002ef0] [2019-09-20 19:33:33,061] - Components::process(): Request for the process of identity...
  WARN root [0x00002ef0] [2019-09-20 19:33:39,167] - EntityApp::checkTickPeriod: tick took 6106% (6.11 seconds)!
  INFO root [0x00002ef0] [2019-09-20 19:33:40,190] - Components::findComponents: find logger(1)...
  INFO root [0x00002ef0] [2019-09-20 19:33:40,206] - Components::findComponents: found logger, addr:10.12.231.110:53610
  INFO root [0x00002ef0] [2019-09-20 19:33:40,206] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00002ef0] [2019-09-20 19:33:40,207] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ef0] [2019-09-20 19:33:40,208] - Components::findComponents: find dbmgr(2)...
  INFO root [0x00002ef0] [2019-09-20 19:33:40,310] - Components::findComponents: found dbmgr, addr:10.12.231.110:53604
  INFO root [0x00002ef0] [2019-09-20 19:33:40,311] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00002ef0] [2019-09-20 19:33:40,311] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00002ef0] [2019-09-20 19:33:40,311] - Components::findComponents: found dbmgr, addr:10.12.231.110:53604
  WARN root [0x00002ef0] [2019-09-20 19:33:41,311] - Forwarding logs to logger[10.12.231.110:53610/0/0/0]...
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,522] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708226565328, lastReceivedTime=1707942324476, inactivityExceptionPeriod=599483694)
  INFO root [0x00002ef0] [2019-09-20 19:36:00,525] - The following logs sent to logger failed:
  WARN root [0x00002ef0] [2019-09-20 19:36:00,525] - ==> [2019-09-20 19:36:00 517] TCPPacketReceiver::processPendingEvents(10.12.231.110:53610): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,525] - ==> [2019-09-20 19:36:00 523] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708226565328, lastReceivedTime=1707942324476, inactivityExceptionPeriod=599483694)
  WARN root [0x00002ef0] [2019-09-20 19:36:00,595] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53604): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,596] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1708227300449, lastReceivedTime=1707938186765, inactivityExceptionPeriod=599483694)
  INFO root [0x00002ef0] [2019-09-20 19:36:00,605] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00002ef0] [2019-09-20 19:36:00,606] - onBaseAppShutDown: state=0
  INFO root [0x00002ef0] [2019-09-20 19:36:00,607] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00002ef0] [2019-09-20 19:36:00,607] - onBaseAppShutDown: state=1
  INFO root [0x00002ef0] [2019-09-20 19:36:00,607] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00002ef0] [2019-09-20 19:36:00,607] - onBaseAppShutDown: state=2
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,621] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,621] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,622] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x00002ef0] [2019-09-20 19:36:00,623] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00002ef0] [2019-09-20 19:36:00,624] - Account::~Account(): 2
 DEBUG root [0x00002ef0] [2019-09-20 19:36:00,624] - Account::~Account(): 3
 DEBUG root [0x00002ef0] [2019-09-20 19:36:00,624] - Room::~Room(): 4
 DEBUG root [0x00002ef0] [2019-09-20 19:36:00,624] - Hall::~Hall(): 1
  INFO root [0x00002ef0] [2019-09-20 19:36:00,640] - Script::uninstall(): is successfully!
 DEBUG root [0x00002ef0] [2019-09-20 19:36:00,640] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000006cc] [2019-09-20 19:36:02,176] - 
  INFO root [0x000006cc] [2019-09-20 19:36:02,177] - -----------------------------------------------------------------------------------------


  INFO root [0x000006cc] [2019-09-20 19:36:02,178] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000006cc] [2019-09-20 19:36:02,178] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000006cc] [2019-09-20 19:36:02,178] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000006cc] [2019-09-20 19:36:02,188] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20015 )
  INFO root [0x000006cc] [2019-09-20 19:36:02,188] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20015, SOMAXCONN=128.
  INFO root [0x000006cc] [2019-09-20 19:36:02,191] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20005 )
  INFO root [0x000006cc] [2019-09-20 19:36:02,191] - NetworkInterface::initialize(EXTERNAL-UDP): address 10.12.231.110:20005, SOMAXCONN=128.
  INFO root [0x000006cc] [2019-09-20 19:36:02,194] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53679 )
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53679, SOMAXCONN=128.
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - server-configs:
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	gameUpdateHertz : 10
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	entryScriptFile : kbemain
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	internalTcpAddr : 10.12.231.110:53679
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	externalTcpAddr : 10.12.231.110:20015
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	externalUdpAddr : 10.12.231.110:20005
  INFO root [0x000006cc] [2019-09-20 19:36:02,195] - 	componentID : 7001
  WARN root [0x000006cc] [2019-09-20 19:36:02,357] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000006cc] [2019-09-20 19:36:03,863] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 16972 ----
  INFO root [0x000006cc] [2019-09-20 19:36:03,864] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000006cc] [2019-09-20 19:36:03,864] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000006cc] [2019-09-20 19:36:03,864] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000006cc] [2019-09-20 19:36:04,067] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000006cc] [2019-09-20 19:36:04,068] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000006cc] [2019-09-20 19:36:04,208] - loaded entity-script:Account(1).
 DEBUG root [0x000006cc] [2019-09-20 19:36:04,208] - loaded entity-script:Hall(2).
 DEBUG root [0x000006cc] [2019-09-20 19:36:04,208] - loaded entity-script:Room(3).
  INFO root [0x000006cc] [2019-09-20 19:36:04,211] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000006cc] [2019-09-20 19:36:04,211] - TelnetServer server is running on port 40000
  INFO root [0x000006cc] [2019-09-20 19:36:04,663] - ---- baseapp is running ----
 DEBUG root [0x000006cc] [2019-09-20 19:36:04,663] - Components::process(): Request for the process of identity...
  WARN root [0x000006cc] [2019-09-20 19:36:10,764] - EntityApp::checkTickPeriod: tick took 6102% (6.10 seconds)!
  INFO root [0x000006cc] [2019-09-20 19:36:11,862] - Components::findComponents: find logger(1)...
  INFO root [0x000006cc] [2019-09-20 19:36:11,965] - Components::findComponents: found logger, addr:10.12.231.110:53678
  INFO root [0x000006cc] [2019-09-20 19:36:11,966] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000006cc] [2019-09-20 19:36:11,966] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000006cc] [2019-09-20 19:36:11,967] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000006cc] [2019-09-20 19:36:12,070] - Components::findComponents: found dbmgr, addr:10.12.231.110:53675
  INFO root [0x000006cc] [2019-09-20 19:36:12,070] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000006cc] [2019-09-20 19:36:12,070] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000006cc] [2019-09-20 19:36:12,070] - Components::findComponents: found dbmgr, addr:10.12.231.110:53675
  WARN root [0x000006cc] [2019-09-20 19:36:13,071] - EntityApp::checkTickPeriod: tick took 1308% (1.31 seconds)!
  WARN root [0x000006cc] [2019-09-20 19:36:13,072] - Forwarding logs to logger[10.12.231.110:53678/0/0/0]...
 ERROR root [0x000006cc] [2019-09-20 19:37:43,243] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709253778293, lastReceivedTime=1709143078613, inactivityExceptionPeriod=599492902)
  INFO root [0x000006cc] [2019-09-20 19:37:43,247] - The following logs sent to logger failed:
  WARN root [0x000006cc] [2019-09-20 19:37:43,247] - ==> [2019-09-20 19:37:43 241] TCPPacketReceiver::processPendingEvents(10.12.231.110:53678): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000006cc] [2019-09-20 19:37:43,247] - ==> [2019-09-20 19:37:43 244] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709253778293, lastReceivedTime=1709143078613, inactivityExceptionPeriod=599492902)
  WARN root [0x000006cc] [2019-09-20 19:37:43,329] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53675): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000006cc] [2019-09-20 19:37:43,332] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1709254669535, lastReceivedTime=1709143012682, inactivityExceptionPeriod=599492902)
  INFO root [0x000006cc] [2019-09-20 19:37:43,342] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000006cc] [2019-09-20 19:37:43,343] - onBaseAppShutDown: state=0
  INFO root [0x000006cc] [2019-09-20 19:37:43,343] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000006cc] [2019-09-20 19:37:43,344] - onBaseAppShutDown: state=1
  INFO root [0x000006cc] [2019-09-20 19:37:43,344] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000006cc] [2019-09-20 19:37:43,344] - onBaseAppShutDown: state=2
 ERROR root [0x000006cc] [2019-09-20 19:37:43,363] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x000006cc] [2019-09-20 19:37:43,364] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000006cc] [2019-09-20 19:37:43,365] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x000006cc] [2019-09-20 19:37:43,365] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000006cc] [2019-09-20 19:37:43,366] - Account::~Account(): 2002
 DEBUG root [0x000006cc] [2019-09-20 19:37:43,367] - Account::~Account(): 2003
 DEBUG root [0x000006cc] [2019-09-20 19:37:43,367] - Room::~Room(): 2004
 DEBUG root [0x000006cc] [2019-09-20 19:37:43,367] - Hall::~Hall(): 2001
  INFO root [0x000006cc] [2019-09-20 19:37:43,383] - Script::uninstall(): is successfully!
 DEBUG root [0x000006cc] [2019-09-20 19:37:43,384] - ThreadPool::destroy(): starting size 2.
  INFO root [0x00001e40] [2019-09-20 19:39:08,199] - 
  INFO root [0x00001e40] [2019-09-20 19:39:08,205] - -----------------------------------------------------------------------------------------


  INFO root [0x00001e40] [2019-09-20 19:39:08,206] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001e40] [2019-09-20 19:39:08,206] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00001e40] [2019-09-20 19:39:08,207] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001e40] [2019-09-20 19:39:08,220] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20015 )
  INFO root [0x00001e40] [2019-09-20 19:39:08,221] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20015, SOMAXCONN=128.
  INFO root [0x00001e40] [2019-09-20 19:39:08,225] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20005 )
  INFO root [0x00001e40] [2019-09-20 19:39:08,225] - NetworkInterface::initialize(EXTERNAL-UDP): address 10.12.231.110:20005, SOMAXCONN=128.
  INFO root [0x00001e40] [2019-09-20 19:39:08,229] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53732 )
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53732, SOMAXCONN=128.
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - server-configs:
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - 	gameUpdateHertz : 10
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - 	entryScriptFile : kbemain
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - 	internalTcpAddr : 10.12.231.110:53732
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - 	externalTcpAddr : 10.12.231.110:20015
  INFO root [0x00001e40] [2019-09-20 19:39:08,230] - 	externalUdpAddr : 10.12.231.110:20005
  INFO root [0x00001e40] [2019-09-20 19:39:08,231] - 	componentID : 7001
  WARN root [0x00001e40] [2019-09-20 19:39:08,408] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00001e40] [2019-09-20 19:39:08,822] - Components::findLogger: found logger, addr:10.12.231.110:53727
  INFO root [0x00001e40] [2019-09-20 19:39:08,823] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00001e40] [2019-09-20 19:39:08,823] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001e40] [2019-09-20 19:39:08,831] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 3160 ----
  INFO root [0x00001e40] [2019-09-20 19:39:08,832] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00001e40] [2019-09-20 19:39:08,832] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001e40] [2019-09-20 19:39:08,833] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001e40] [2019-09-20 19:39:09,084] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001e40] [2019-09-20 19:39:09,084] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001e40] [2019-09-20 19:39:09,224] - loaded entity-script:Account(1).
 DEBUG root [0x00001e40] [2019-09-20 19:39:09,225] - loaded entity-script:Hall(2).
 DEBUG root [0x00001e40] [2019-09-20 19:39:09,225] - loaded entity-script:Room(3).
  INFO root [0x00001e40] [2019-09-20 19:39:09,228] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001e40] [2019-09-20 19:39:09,228] - TelnetServer server is running on port 40000
  INFO root [0x00001e40] [2019-09-20 19:39:09,714] - ---- baseapp is running ----
 DEBUG root [0x00001e40] [2019-09-20 19:39:09,715] - Components::process(): Request for the process of identity...
  WARN root [0x00001e40] [2019-09-20 19:39:15,836] - Forwarding logs to logger[10.12.231.110:53727/0/0/0]...
 ERROR root [0x00001e40] [2019-09-20 19:42:05,949] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711880836940, lastReceivedTime=1711603101014, inactivityExceptionPeriod=599493030)
  INFO root [0x00001e40] [2019-09-20 19:42:05,956] - The following logs sent to logger failed:
  WARN root [0x00001e40] [2019-09-20 19:42:05,957] - ==> [2019-09-20 19:42:05 949] TCPPacketReceiver::processPendingEvents(10.12.231.110:53727): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001e40] [2019-09-20 19:42:05,957] - ==> [2019-09-20 19:42:05 950] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711880836940, lastReceivedTime=1711603101014, inactivityExceptionPeriod=599493030)
  WARN root [0x00001e40] [2019-09-20 19:42:06,031] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53729): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001e40] [2019-09-20 19:42:06,032] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=1711881665230, lastReceivedTime=1711603379677, inactivityExceptionPeriod=599493030)
  INFO root [0x00001e40] [2019-09-20 19:42:06,034] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001e40] [2019-09-20 19:42:06,037] - onBaseAppShutDown: state=0
  INFO root [0x00001e40] [2019-09-20 19:42:06,037] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001e40] [2019-09-20 19:42:06,038] - onBaseAppShutDown: state=1
  INFO root [0x00001e40] [2019-09-20 19:42:06,038] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001e40] [2019-09-20 19:42:06,039] - onBaseAppShutDown: state=2
 ERROR root [0x00001e40] [2019-09-20 19:42:06,052] - Account::onCellWriteToDBCompleted(2002): not found dbmgr!
 ERROR root [0x00001e40] [2019-09-20 19:42:06,053] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001e40] [2019-09-20 19:42:06,054] - Account::onCellWriteToDBCompleted(2003): not found dbmgr!
 ERROR root [0x00001e40] [2019-09-20 19:42:06,055] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001e40] [2019-09-20 19:42:06,056] - Account::~Account(): 2002
 DEBUG root [0x00001e40] [2019-09-20 19:42:06,056] - Account::~Account(): 2003
 DEBUG root [0x00001e40] [2019-09-20 19:42:06,056] - Room::~Room(): 2004
 DEBUG root [0x00001e40] [2019-09-20 19:42:06,056] - Hall::~Hall(): 2001
  INFO root [0x00001e40] [2019-09-20 19:42:06,070] - Script::uninstall(): is successfully!
 DEBUG root [0x00001e40] [2019-09-20 19:42:06,071] - ThreadPool::destroy(): starting size 2.
  INFO root [0x0000141c] [2019-09-20 20:40:03,823] - 
  INFO root [0x0000141c] [2019-09-20 20:40:03,824] - -----------------------------------------------------------------------------------------


  INFO root [0x0000141c] [2019-09-20 20:40:03,825] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000141c] [2019-09-20 20:40:03,825] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x0000141c] [2019-09-20 20:40:03,825] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000141c] [2019-09-20 20:40:03,836] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x0000141c] [2019-09-20 20:40:03,836] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x0000141c] [2019-09-20 20:40:03,840] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x0000141c] [2019-09-20 20:40:03,840] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x0000141c] [2019-09-20 20:40:03,844] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53807 )
  INFO root [0x0000141c] [2019-09-20 20:40:03,844] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53807, SOMAXCONN=128.
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - server-configs:
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	gameUpdateHertz : 10
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	entryScriptFile : kbemain
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	internalTcpAddr : 127.0.0.1:53807
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x0000141c] [2019-09-20 20:40:03,845] - 	componentID : 7001
  WARN root [0x0000141c] [2019-09-20 20:40:03,989] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x0000141c] [2019-09-20 20:40:05,494] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 6808 ----
  INFO root [0x0000141c] [2019-09-20 20:40:05,510] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x0000141c] [2019-09-20 20:40:05,510] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000141c] [2019-09-20 20:40:05,511] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000141c] [2019-09-20 20:40:05,899] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000141c] [2019-09-20 20:40:05,900] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000141c] [2019-09-20 20:40:06,013] - loaded entity-script:Account(1).
 DEBUG root [0x0000141c] [2019-09-20 20:40:06,014] - loaded entity-script:Hall(2).
 DEBUG root [0x0000141c] [2019-09-20 20:40:06,014] - loaded entity-script:Room(3).
  INFO root [0x0000141c] [2019-09-20 20:40:06,017] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000141c] [2019-09-20 20:40:06,018] - TelnetServer server is running on port 40000
  INFO root [0x0000141c] [2019-09-20 20:40:06,482] - ---- baseapp is running ----
 DEBUG root [0x0000141c] [2019-09-20 20:40:06,482] - Components::process(): Request for the process of identity...
  WARN root [0x0000141c] [2019-09-20 20:40:12,582] - EntityApp::checkTickPeriod: tick took 6100% (6.10 seconds)!
  INFO root [0x0000141c] [2019-09-20 20:40:13,626] - Components::findComponents: find logger(1)...
 ERROR root [0x0000141c] [2019-09-20 20:40:15,145] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000141c] [2019-09-20 20:40:15,146] - Components::findComponents: receive error!
  WARN root [0x0000141c] [2019-09-20 20:40:15,147] - Components::findComponents: not found logger!
  WARN root [0x0000141c] [2019-09-20 20:40:15,148] - EntityApp::checkTickPeriod: tick took 1566% (1.57 seconds)!
  INFO root [0x0000141c] [2019-09-20 20:40:16,182] - Components::findComponents: find dbmgr(1)...
 ERROR root [0x0000141c] [2019-09-20 20:40:17,683] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000141c] [2019-09-20 20:40:17,684] - Components::findComponents: receive error!
  WARN root [0x0000141c] [2019-09-20 20:40:17,685] - EntityApp::checkTickPeriod: tick took 1602% (1.60 seconds)!
  INFO root [0x0000141c] [2019-09-20 20:40:18,725] - Components::findComponents: find dbmgr(2)...
 ERROR root [0x0000141c] [2019-09-20 20:40:20,227] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000141c] [2019-09-20 20:40:20,228] - Components::findComponents: receive error!
  WARN root [0x0000141c] [2019-09-20 20:40:20,230] - EntityApp::checkTickPeriod: tick took 1547% (1.55 seconds)!
  INFO root [0x0000141c] [2019-09-20 20:40:21,281] - Components::findComponents: find dbmgr(3)...
 ERROR root [0x0000141c] [2019-09-20 20:40:22,782] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000141c] [2019-09-20 20:40:22,784] - Components::findComponents: receive error!
  WARN root [0x0000141c] [2019-09-20 20:40:22,785] - EntityApp::checkTickPeriod: tick took 1605% (1.61 seconds)!
  INFO root [0x0000141c] [2019-09-20 20:40:23,826] - Components::findComponents: find dbmgr(4)...
 ERROR root [0x0000141c] [2019-09-20 20:40:25,327] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000141c] [2019-09-20 20:40:25,331] - Components::findComponents: receive error!
  WARN root [0x0000141c] [2019-09-20 20:40:25,332] - EntityApp::checkTickPeriod: tick took 1550% (1.55 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:27,539] - 
  INFO root [0x00001d78] [2019-09-20 20:40:27,541] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d78] [2019-09-20 20:40:27,542] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001d78] [2019-09-20 20:40:27,542] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00001d78] [2019-09-20 20:40:27,543] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001d78] [2019-09-20 20:40:27,559] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x00001d78] [2019-09-20 20:40:27,559] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x00001d78] [2019-09-20 20:40:27,564] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x00001d78] [2019-09-20 20:40:27,564] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53821 )
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53821, SOMAXCONN=128.
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - server-configs:
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - 	gameUpdateHertz : 10
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - 	entryScriptFile : kbemain
  INFO root [0x00001d78] [2019-09-20 20:40:27,568] - 	internalTcpAddr : 127.0.0.1:53821
  INFO root [0x00001d78] [2019-09-20 20:40:27,569] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x00001d78] [2019-09-20 20:40:27,569] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x00001d78] [2019-09-20 20:40:27,569] - 	componentID : 7001
  WARN root [0x00001d78] [2019-09-20 20:40:27,747] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00001d78] [2019-09-20 20:40:29,252] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 3232 ----
  INFO root [0x00001d78] [2019-09-20 20:40:29,253] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00001d78] [2019-09-20 20:40:29,253] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d78] [2019-09-20 20:40:29,254] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001d78] [2019-09-20 20:40:29,556] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001d78] [2019-09-20 20:40:29,556] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001d78] [2019-09-20 20:40:29,675] - loaded entity-script:Account(1).
 DEBUG root [0x00001d78] [2019-09-20 20:40:29,676] - loaded entity-script:Hall(2).
 DEBUG root [0x00001d78] [2019-09-20 20:40:29,676] - loaded entity-script:Room(3).
  INFO root [0x00001d78] [2019-09-20 20:40:29,679] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001d78] [2019-09-20 20:40:29,680] - TelnetServer server is running on port 40000
  INFO root [0x00001d78] [2019-09-20 20:40:30,229] - ---- baseapp is running ----
 DEBUG root [0x00001d78] [2019-09-20 20:40:30,230] - Components::process(): Request for the process of identity...
  WARN root [0x00001d78] [2019-09-20 20:40:36,396] - EntityApp::checkTickPeriod: tick took 6167% (6.17 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:37,429] - Components::findComponents: find logger(1)...
 ERROR root [0x00001d78] [2019-09-20 20:40:38,931] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001d78] [2019-09-20 20:40:38,932] - Components::findComponents: receive error!
  WARN root [0x00001d78] [2019-09-20 20:40:38,933] - Components::findComponents: not found logger!
  WARN root [0x00001d78] [2019-09-20 20:40:38,934] - EntityApp::checkTickPeriod: tick took 1604% (1.60 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:39,947] - Components::findComponents: find dbmgr(1)...
 ERROR root [0x00001d78] [2019-09-20 20:40:41,448] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001d78] [2019-09-20 20:40:41,449] - Components::findComponents: receive error!
  WARN root [0x00001d78] [2019-09-20 20:40:41,450] - EntityApp::checkTickPeriod: tick took 1521% (1.52 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:42,529] - Components::findComponents: find dbmgr(2)...
 ERROR root [0x00001d78] [2019-09-20 20:40:44,029] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001d78] [2019-09-20 20:40:44,030] - Components::findComponents: receive error!
  WARN root [0x00001d78] [2019-09-20 20:40:44,032] - EntityApp::checkTickPeriod: tick took 1603% (1.60 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:45,047] - Components::findComponents: find dbmgr(3)...
 ERROR root [0x00001d78] [2019-09-20 20:40:46,548] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00001d78] [2019-09-20 20:40:46,550] - Components::findComponents: receive error!
  WARN root [0x00001d78] [2019-09-20 20:40:46,551] - EntityApp::checkTickPeriod: tick took 1521% (1.52 seconds)!
  INFO root [0x00001d78] [2019-09-20 20:40:47,629] - Components::findComponents: find dbmgr(4)...
  INFO root [0x00002924] [2019-09-20 20:40:50,059] - 
  INFO root [0x00002924] [2019-09-20 20:40:50,061] - -----------------------------------------------------------------------------------------


  INFO root [0x00002924] [2019-09-20 20:40:50,062] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00002924] [2019-09-20 20:40:50,063] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00002924] [2019-09-20 20:40:50,063] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00002924] [2019-09-20 20:40:50,082] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x00002924] [2019-09-20 20:40:50,083] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x00002924] [2019-09-20 20:40:50,086] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x00002924] [2019-09-20 20:40:50,086] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x00002924] [2019-09-20 20:40:50,090] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53838 )
  INFO root [0x00002924] [2019-09-20 20:40:50,090] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53838, SOMAXCONN=128.
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - server-configs:
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	gameUpdateHertz : 10
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	entryScriptFile : kbemain
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	internalTcpAddr : 127.0.0.1:53838
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x00002924] [2019-09-20 20:40:50,091] - 	componentID : 7001
  WARN root [0x00002924] [2019-09-20 20:40:50,237] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00002924] [2019-09-20 20:40:51,742] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 15052 ----
  INFO root [0x00002924] [2019-09-20 20:40:51,743] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00002924] [2019-09-20 20:40:51,743] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00002924] [2019-09-20 20:40:51,744] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00002924] [2019-09-20 20:40:51,943] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00002924] [2019-09-20 20:40:51,943] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00002924] [2019-09-20 20:40:52,113] - loaded entity-script:Account(1).
 DEBUG root [0x00002924] [2019-09-20 20:40:52,114] - loaded entity-script:Hall(2).
 DEBUG root [0x00002924] [2019-09-20 20:40:52,114] - loaded entity-script:Room(3).
  INFO root [0x00002924] [2019-09-20 20:40:52,116] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00002924] [2019-09-20 20:40:52,117] - TelnetServer server is running on port 40000
  INFO root [0x00002924] [2019-09-20 20:40:52,585] - ---- baseapp is running ----
 DEBUG root [0x00002924] [2019-09-20 20:40:52,585] - Components::process(): Request for the process of identity...
  WARN root [0x00002924] [2019-09-20 20:40:58,690] - EntityApp::checkTickPeriod: tick took 6105% (6.11 seconds)!
  INFO root [0x00002924] [2019-09-20 20:40:59,771] - Components::findComponents: find logger(1)...
 ERROR root [0x00002924] [2019-09-20 20:41:01,273] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00002924] [2019-09-20 20:41:01,274] - Components::findComponents: receive error!
  WARN root [0x00002924] [2019-09-20 20:41:01,275] - Components::findComponents: not found logger!
  WARN root [0x00002924] [2019-09-20 20:41:01,276] - EntityApp::checkTickPeriod: tick took 1590% (1.59 seconds)!
  INFO root [0x00002924] [2019-09-20 20:41:02,285] - Components::findComponents: find dbmgr(1)...
 ERROR root [0x00002924] [2019-09-20 20:41:03,786] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00002924] [2019-09-20 20:41:03,787] - Components::findComponents: receive error!
  WARN root [0x00002924] [2019-09-20 20:41:03,788] - EntityApp::checkTickPeriod: tick took 1603% (1.60 seconds)!
  INFO root [0x00003728] [2019-09-20 20:41:48,633] - 
  INFO root [0x00003728] [2019-09-20 20:41:48,633] - -----------------------------------------------------------------------------------------


  INFO root [0x00003728] [2019-09-20 20:41:48,634] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00003728] [2019-09-20 20:41:48,634] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00003728] [2019-09-20 20:41:48,635] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00003728] [2019-09-20 20:41:48,644] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x00003728] [2019-09-20 20:41:48,645] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x00003728] [2019-09-20 20:41:48,648] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x00003728] [2019-09-20 20:41:48,648] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x00003728] [2019-09-20 20:41:48,651] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:53847 )
  INFO root [0x00003728] [2019-09-20 20:41:48,651] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:53847, SOMAXCONN=128.
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - server-configs:
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	gameUpdateHertz : 10
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	entryScriptFile : kbemain
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	internalTcpAddr : 127.0.0.1:53847
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x00003728] [2019-09-20 20:41:48,652] - 	componentID : 7001
  WARN root [0x00003728] [2019-09-20 20:41:48,806] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00003728] [2019-09-20 20:41:50,311] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 188 ----
  INFO root [0x00003728] [2019-09-20 20:41:50,311] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00003728] [2019-09-20 20:41:50,312] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00003728] [2019-09-20 20:41:50,312] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00003728] [2019-09-20 20:41:50,517] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00003728] [2019-09-20 20:41:50,518] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00003728] [2019-09-20 20:41:50,744] - loaded entity-script:Account(1).
 DEBUG root [0x00003728] [2019-09-20 20:41:50,744] - loaded entity-script:Hall(2).
 DEBUG root [0x00003728] [2019-09-20 20:41:50,745] - loaded entity-script:Room(3).
  INFO root [0x00003728] [2019-09-20 20:41:50,747] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00003728] [2019-09-20 20:41:50,748] - TelnetServer server is running on port 40000
  INFO root [0x00003728] [2019-09-20 20:41:51,215] - ---- baseapp is running ----
 DEBUG root [0x00003728] [2019-09-20 20:41:51,215] - Components::process(): Request for the process of identity...
  WARN root [0x00003728] [2019-09-20 20:41:57,315] - EntityApp::checkTickPeriod: tick took 6100% (6.10 seconds)!
  INFO root [0x00003728] [2019-09-20 20:41:58,336] - Components::findComponents: find logger(1)...
 ERROR root [0x00003728] [2019-09-20 20:41:59,838] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x00003728] [2019-09-20 20:41:59,839] - Components::findComponents: receive error!
  WARN root [0x00003728] [2019-09-20 20:41:59,840] - Components::findComponents: not found logger!
  WARN root [0x00003728] [2019-09-20 20:41:59,840] - EntityApp::checkTickPeriod: tick took 1525% (1.52 seconds)!
  INFO root [0x00003728] [2019-09-20 20:42:00,915] - Components::findComponents: find dbmgr(1)...
  INFO root [0x000023f0] [2019-09-20 20:49:21,594] - 
  INFO root [0x000023f0] [2019-09-20 20:49:21,626] - -----------------------------------------------------------------------------------------


  INFO root [0x000023f0] [2019-09-20 20:49:21,626] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000023f0] [2019-09-20 20:49:21,626] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000023f0] [2019-09-20 20:49:21,626] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49690 )
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49690, SOMAXCONN=128.
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - server-configs:
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	gameUpdateHertz : 10
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	entryScriptFile : kbemain
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	internalTcpAddr : 127.0.0.1:49690
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x000023f0] [2019-09-20 20:49:21,641] - 	componentID : 7001
  WARN root [0x000023f0] [2019-09-20 20:49:21,813] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x000023f0] [2019-09-20 20:49:23,327] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 9196 ----
  INFO root [0x000023f0] [2019-09-20 20:49:23,327] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000023f0] [2019-09-20 20:49:23,327] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000023f0] [2019-09-20 20:49:23,327] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000023f0] [2019-09-20 20:49:23,531] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000023f0] [2019-09-20 20:49:23,531] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000023f0] [2019-09-20 20:49:23,728] - loaded entity-script:Account(1).
 DEBUG root [0x000023f0] [2019-09-20 20:49:23,728] - loaded entity-script:Hall(2).
 DEBUG root [0x000023f0] [2019-09-20 20:49:23,728] - loaded entity-script:Room(3).
  INFO root [0x000023f0] [2019-09-20 20:49:23,732] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000023f0] [2019-09-20 20:49:23,732] - TelnetServer server is running on port 40000
  INFO root [0x000023f0] [2019-09-20 20:49:24,122] - ---- baseapp is running ----
 DEBUG root [0x000023f0] [2019-09-20 20:49:24,122] - Components::process(): Request for the process of identity...
  WARN root [0x000023f0] [2019-09-20 20:49:30,652] - EntityApp::checkTickPeriod: tick took 6379% (6.38 seconds)!
  WARN root [0x000023f0] [2019-09-20 20:49:30,730] - d:\kbengine\kbe\src\server\baseapp\baseapp.cpp:560: Profile gameTick took 0.24 seconds
  WARN root [0x000023f0] [2019-09-20 20:49:30,730] - EntityApp::checkTickPeriod: tick took 236% (0.24 seconds)!
  WARN root [0x000023f0] [2019-09-20 20:49:30,761] - d:\kbengine\kbe\src\lib\network\event_dispatcher.cpp:153: Profile callSystemTimers took 0.33 seconds
  INFO root [0x0000238c] [2019-09-20 20:50:47,377] - 
  INFO root [0x0000238c] [2019-09-20 20:50:47,377] - -----------------------------------------------------------------------------------------


  INFO root [0x0000238c] [2019-09-20 20:50:47,377] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x0000238c] [2019-09-20 20:50:47,377] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x0000238c] [2019-09-20 20:50:47,377] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20015 )
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(EXTERNAL-TCP): address 127.0.0.1:20015, SOMAXCONN=128.
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:20005 )
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(EXTERNAL-UDP): address 127.0.0.1:20005, SOMAXCONN=128.
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49728 )
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49728, SOMAXCONN=128.
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - server-configs:
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	gameUpdateHertz : 10
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	entryScriptFile : kbemain
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	internalTcpAddr : 127.0.0.1:49728
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	externalTcpAddr : 127.0.0.1:20015
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	externalUdpAddr : 127.0.0.1:20005
  INFO root [0x0000238c] [2019-09-20 20:50:47,393] - 	componentID : 7001
  WARN root [0x0000238c] [2019-09-20 20:50:47,549] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x0000238c] [2019-09-20 20:50:49,065] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 9172 ----
  INFO root [0x0000238c] [2019-09-20 20:50:49,080] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x0000238c] [2019-09-20 20:50:49,080] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x0000238c] [2019-09-20 20:50:49,080] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x0000238c] [2019-09-20 20:50:49,439] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x0000238c] [2019-09-20 20:50:49,439] - Script::install(): KBExtra is successfully!
 DEBUG root [0x0000238c] [2019-09-20 20:50:49,549] - loaded entity-script:Account(1).
 DEBUG root [0x0000238c] [2019-09-20 20:50:49,549] - loaded entity-script:Hall(2).
 DEBUG root [0x0000238c] [2019-09-20 20:50:49,549] - loaded entity-script:Room(3).
  INFO root [0x0000238c] [2019-09-20 20:50:49,549] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x0000238c] [2019-09-20 20:50:49,549] - TelnetServer server is running on port 40000
  INFO root [0x0000238c] [2019-09-20 20:50:50,040] - ---- baseapp is running ----
 DEBUG root [0x0000238c] [2019-09-20 20:50:50,040] - Components::process(): Request for the process of identity...
  WARN root [0x0000238c] [2019-09-20 20:50:56,304] - EntityApp::checkTickPeriod: tick took 6256% (6.26 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:50:57,397] - Components::findComponents: find logger(1)...
 ERROR root [0x0000238c] [2019-09-20 20:50:58,912] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:50:58,912] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:50:58,912] - Components::findComponents: not found logger!
  WARN root [0x0000238c] [2019-09-20 20:50:58,912] - EntityApp::checkTickPeriod: tick took 1564% (1.56 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:50:59,959] - Components::findComponents: find dbmgr(1)...
 ERROR root [0x0000238c] [2019-09-20 20:51:01,474] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:01,474] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:01,474] - EntityApp::checkTickPeriod: tick took 1626% (1.63 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:02,505] - Components::findComponents: find dbmgr(2)...
 ERROR root [0x0000238c] [2019-09-20 20:51:04,021] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:04,021] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:04,021] - EntityApp::checkTickPeriod: tick took 1564% (1.56 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:05,052] - Components::findComponents: find dbmgr(3)...
 ERROR root [0x0000238c] [2019-09-20 20:51:06,567] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:06,567] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:06,567] - EntityApp::checkTickPeriod: tick took 1612% (1.61 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:07,598] - Components::findComponents: find dbmgr(4)...
 ERROR root [0x0000238c] [2019-09-20 20:51:09,113] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:09,113] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:09,113] - EntityApp::checkTickPeriod: tick took 1565% (1.57 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:10,160] - Components::findComponents: find dbmgr(5)...
 ERROR root [0x0000238c] [2019-09-20 20:51:11,675] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:11,675] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:11,675] - EntityApp::checkTickPeriod: tick took 1628% (1.63 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:12,690] - Components::findComponents: find dbmgr(6)...
 ERROR root [0x0000238c] [2019-09-20 20:51:14,206] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:14,206] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:14,206] - EntityApp::checkTickPeriod: tick took 1550% (1.55 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:15,252] - Components::findComponents: find dbmgr(7)...
 ERROR root [0x0000238c] [2019-09-20 20:51:16,768] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:16,768] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:16,768] - EntityApp::checkTickPeriod: tick took 1612% (1.61 seconds)!
  INFO root [0x0000238c] [2019-09-20 20:51:17,799] - Components::findComponents: find dbmgr(8)...
 ERROR root [0x0000238c] [2019-09-20 20:51:19,314] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [0x0000238c] [2019-09-20 20:51:19,314] - Components::findComponents: receive error!
  WARN root [0x0000238c] [2019-09-20 20:51:19,314] - EntityApp::checkTickPeriod: tick took 1565% (1.57 seconds)!
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - 
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - -----------------------------------------------------------------------------------------


  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20015 )
  INFO root [0x00001d08] [2019-09-20 20:55:49,196] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20015, SOMAXCONN=128.
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20005 )
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - NetworkInterface::initialize(EXTERNAL-UDP): address 10.12.231.110:20005, SOMAXCONN=128.
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:50148 )
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:50148, SOMAXCONN=128.
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - server-configs:
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	gameUpdateHertz : 10
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	entryScriptFile : kbemain
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	internalTcpAddr : 10.12.231.110:50148
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	externalTcpAddr : 10.12.231.110:20015
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	externalUdpAddr : 10.12.231.110:20005
  INFO root [0x00001d08] [2019-09-20 20:55:49,211] - 	componentID : 7001
  WARN root [0x00001d08] [2019-09-20 20:55:49,352] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [0x00001d08] [2019-09-20 20:55:49,774] - Components::findLogger: found logger, addr:10.12.231.110:50150
  INFO root [0x00001d08] [2019-09-20 20:55:49,774] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x00001d08] [2019-09-20 20:55:49,774] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x00001d08] [2019-09-20 20:55:49,789] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 10716 ----
  INFO root [0x00001d08] [2019-09-20 20:55:49,789] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x00001d08] [2019-09-20 20:55:49,789] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x00001d08] [2019-09-20 20:55:49,789] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x00001d08] [2019-09-20 20:55:50,023] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x00001d08] [2019-09-20 20:55:50,023] - Script::install(): KBExtra is successfully!
 DEBUG root [0x00001d08] [2019-09-20 20:55:50,151] - loaded entity-script:Account(1).
 DEBUG root [0x00001d08] [2019-09-20 20:55:50,151] - loaded entity-script:Hall(2).
 DEBUG root [0x00001d08] [2019-09-20 20:55:50,151] - loaded entity-script:Room(3).
  INFO root [0x00001d08] [2019-09-20 20:55:50,151] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x00001d08] [2019-09-20 20:55:50,151] - TelnetServer server is running on port 40000
  INFO root [0x00001d08] [2019-09-20 20:55:50,570] - ---- baseapp is running ----
 DEBUG root [0x00001d08] [2019-09-20 20:55:50,570] - Components::process(): Request for the process of identity...
  WARN root [0x00001d08] [2019-09-20 20:55:56,834] - Forwarding logs to logger[10.12.231.110:50150/0/0/0]...
 ERROR root [0x00001d08] [2019-09-20 21:01:26,029] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9151991405, lastReceivedTime=9084385728, inactivityExceptionPeriod=599495460)
  INFO root [0x00001d08] [2019-09-20 21:01:26,031] - The following logs sent to logger failed:
  WARN root [0x00001d08] [2019-09-20 21:01:26,031] - ==> [2019-09-20 21:01:26 026] TCPPacketReceiver::processPendingEvents(10.12.231.110:50150): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d08] [2019-09-20 21:01:26,032] - ==> [2019-09-20 21:01:26 029] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9151991405, lastReceivedTime=9084385728, inactivityExceptionPeriod=599495460)
  WARN root [0x00001d08] [2019-09-20 21:01:26,102] - TCPPacketReceiver::processPendingEvents(10.12.231.110:50151): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x00001d08] [2019-09-20 21:01:26,105] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=9152749107, lastReceivedTime=9085031014, inactivityExceptionPeriod=599495460)
  INFO root [0x00001d08] [2019-09-20 21:01:26,112] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x00001d08] [2019-09-20 21:01:26,114] - onBaseAppShutDown: state=0
  INFO root [0x00001d08] [2019-09-20 21:01:26,114] - Shutdowner::onShutdown: shutting down
S_INFO root [0x00001d08] [2019-09-20 21:01:26,114] - onBaseAppShutDown: state=1
  INFO root [0x00001d08] [2019-09-20 21:01:26,114] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x00001d08] [2019-09-20 21:01:26,115] - onBaseAppShutDown: state=2
 ERROR root [0x00001d08] [2019-09-20 21:01:26,127] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x00001d08] [2019-09-20 21:01:26,128] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x00001d08] [2019-09-20 21:01:26,129] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x00001d08] [2019-09-20 21:01:26,130] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x00001d08] [2019-09-20 21:01:26,130] - Account::~Account(): 2
 DEBUG root [0x00001d08] [2019-09-20 21:01:26,131] - Account::~Account(): 3
 DEBUG root [0x00001d08] [2019-09-20 21:01:26,131] - Room::~Room(): 4
 DEBUG root [0x00001d08] [2019-09-20 21:01:26,131] - Hall::~Hall(): 1
  INFO root [0x00001d08] [2019-09-20 21:01:26,145] - Script::uninstall(): is successfully!
 DEBUG root [0x00001d08] [2019-09-20 21:01:26,146] - ThreadPool::destroy(): starting size 2.
  INFO root [0x000027d4] [2019-09-20 21:01:27,637] - 
  INFO root [0x000027d4] [2019-09-20 21:01:27,637] - -----------------------------------------------------------------------------------------


  INFO root [0x000027d4] [2019-09-20 21:01:27,642] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [0x000027d4] [2019-09-20 21:01:27,642] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [0x000027d4] [2019-09-20 21:01:27,642] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [0x000027d4] [2019-09-20 21:01:27,647] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20015 )
  INFO root [0x000027d4] [2019-09-20 21:01:27,647] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.12.231.110:20015, SOMAXCONN=128.
  INFO root [0x000027d4] [2019-09-20 21:01:27,652] - NetworkInterface::initialize(EXTERNAL-UDP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:20005 )
  INFO root [0x000027d4] [2019-09-20 21:01:27,652] - NetworkInterface::initialize(EXTERNAL-UDP): address 10.12.231.110:20005, SOMAXCONN=128.
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:50334 )
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:50334, SOMAXCONN=128.
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - server-configs:
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	gameUpdateHertz : 10
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	entryScriptFile : kbemain
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	internalTcpAddr : 10.12.231.110:50334
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	externalTcpAddr : 10.12.231.110:20015
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	externalUdpAddr : 10.12.231.110:20005
  INFO root [0x000027d4] [2019-09-20 21:01:27,657] - 	componentID : 7001
  WARN root [0x000027d4] [2019-09-20 21:01:27,834] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [0x000027d4] [2019-09-20 21:01:28,463] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20226, errorno=10048
  INFO root [0x000027d4] [2019-09-20 21:01:28,463] - ---- baseapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: DCFA95A4364DC44A8B8A14D3936CBE92. Config: Debug X86. Built: 09:56:40 May  8 2019. AppID: 7001. UID: 41181. PID: 9772 ----
  INFO root [0x000027d4] [2019-09-20 21:01:28,463] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [0x000027d4] [2019-09-20 21:01:28,463] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [0x000027d4] [2019-09-20 21:01:28,463] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [0x000027d4] [2019-09-20 21:01:28,678] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [0x000027d4] [2019-09-20 21:01:28,678] - Script::install(): KBExtra is successfully!
 DEBUG root [0x000027d4] [2019-09-20 21:01:28,778] - loaded entity-script:Account(1).
 DEBUG root [0x000027d4] [2019-09-20 21:01:28,782] - loaded entity-script:Hall(2).
 DEBUG root [0x000027d4] [2019-09-20 21:01:28,782] - loaded entity-script:Room(3).
  INFO root [0x000027d4] [2019-09-20 21:01:28,782] - Baseapp::initializeEnd: started resmgr tick(60s)!
  INFO root [0x000027d4] [2019-09-20 21:01:28,782] - TelnetServer server is running on port 40000
  INFO root [0x000027d4] [2019-09-20 21:01:29,210] - ---- baseapp is running ----
 DEBUG root [0x000027d4] [2019-09-20 21:01:29,210] - Components::process(): Request for the process of identity...
  WARN root [0x000027d4] [2019-09-20 21:01:35,413] - EntityApp::checkTickPeriod: tick took 6205% (6.20 seconds)!
  INFO root [0x000027d4] [2019-09-20 21:01:36,452] - Components::findComponents: find logger(1)...
  INFO root [0x000027d4] [2019-09-20 21:01:36,467] - Components::findComponents: found logger, addr:10.12.231.110:50331
  INFO root [0x000027d4] [2019-09-20 21:01:36,467] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000027d4] [2019-09-20 21:01:36,467] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027d4] [2019-09-20 21:01:36,472] - Components::findComponents: find dbmgr(2)...
  INFO root [0x000027d4] [2019-09-20 21:01:36,582] - Components::findComponents: found dbmgr, addr:10.12.231.110:50327
  INFO root [0x000027d4] [2019-09-20 21:01:36,582] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [0x000027d4] [2019-09-20 21:01:36,582] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [0x000027d4] [2019-09-20 21:01:36,582] - Components::findComponents: found dbmgr, addr:10.12.231.110:50327
  WARN root [0x000027d4] [2019-09-20 21:01:37,587] - Forwarding logs to logger[10.12.231.110:50331/0/0/0]...
 ERROR root [0x000027d4] [2019-09-20 21:04:28,547] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10977221554, lastReceivedTime=10967936021, inactivityExceptionPeriod=599433368)
  INFO root [0x000027d4] [2019-09-20 21:04:28,557] - The following logs sent to logger failed:
  WARN root [0x000027d4] [2019-09-20 21:04:28,557] - ==> [2019-09-20 21:04:28 551] TCPPacketReceiver::processPendingEvents(10.12.231.110:50331): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027d4] [2019-09-20 21:04:28,557] - ==> [2019-09-20 21:04:28 552] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10977221554, lastReceivedTime=10967936021, inactivityExceptionPeriod=599433368)
  WARN root [0x000027d4] [2019-09-20 21:04:28,632] - TCPPacketReceiver::processPendingEvents(10.12.231.110:50327): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [0x000027d4] [2019-09-20 21:04:28,642] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=10978158051, lastReceivedTime=10966536832, inactivityExceptionPeriod=599433368)
  INFO root [0x000027d4] [2019-09-20 21:04:28,657] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [0x000027d4] [2019-09-20 21:04:28,662] - onBaseAppShutDown: state=0
  INFO root [0x000027d4] [2019-09-20 21:04:28,662] - Shutdowner::onShutdown: shutting down
S_INFO root [0x000027d4] [2019-09-20 21:04:28,662] - onBaseAppShutDown: state=1
  INFO root [0x000027d4] [2019-09-20 21:04:28,662] - Shutdowner::onShutdownEnd: shutting down
S_INFO root [0x000027d4] [2019-09-20 21:04:28,662] - onBaseAppShutDown: state=2
 ERROR root [0x000027d4] [2019-09-20 21:04:28,677] - Account::onCellWriteToDBCompleted(2): not found dbmgr!
 ERROR root [0x000027d4] [2019-09-20 21:04:28,677] - Entity::onDestroy: not found dbmgr!
 ERROR root [0x000027d4] [2019-09-20 21:04:28,687] - Account::onCellWriteToDBCompleted(3): not found dbmgr!
 ERROR root [0x000027d4] [2019-09-20 21:04:28,687] - Entity::onDestroy: not found dbmgr!
 DEBUG root [0x000027d4] [2019-09-20 21:04:28,692] - Account::~Account(): 2
 DEBUG root [0x000027d4] [2019-09-20 21:04:28,692] - Account::~Account(): 3
 DEBUG root [0x000027d4] [2019-09-20 21:04:28,692] - Room::~Room(): 4
 DEBUG root [0x000027d4] [2019-09-20 21:04:28,692] - Hall::~Hall(): 1
  INFO root [0x000027d4] [2019-09-20 21:04:28,712] - Script::uninstall(): is successfully!
 DEBUG root [0x000027d4] [2019-09-20 21:04:28,712] - ThreadPool::destroy(): starting size 2.
