  INFO root [2019-10-01 16:22:11,483] - 
  INFO root [2019-10-01 16:22:11,484] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:22:11,608] - 
  INFO root [2019-10-01 16:22:11,609] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:22:11,764] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:22:11,764] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:22:11,764] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/r  INFO root [2019-10-01 16:22:11,764] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
es/
  INFO root [2019-10-01 16:22:11,795] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:22:11,795] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:22:11,955] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53305 )
  INFO root [2019-10-01 16:22:11,955] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53306 )
  INFO root [2019-10-01 16:22:11,955] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53305, SOMAXCONN=5.
  INFO root [2019-10-01 16:22:11,955] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53306, SOMAXCONN=5.
  INFO root [2019-10-01 16:22:11,955] - server-configs:
  INFO root [2019-10-01 16:22:11,955] - server-configs:
  INFO root [2019-10-01 16:22:11,955] - 	internalTcpAddr : 10.12.231.110:53305
  INFO root [2019-10-01 16:22:11,955] - 	internalTcpAddr : 10.12.231.110:53306
  INFO root [2019-10-01 16:22:11,955] - 	componentID : 6000
  INFO root [2019-10-01 16:22:11,956] - 	componentID : 6000
  WARN root [2019-10-01 16:22:11,956] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-10-01 16:22:11,956] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:22:12,049] - Components::findLogger: found logger, addr:10.12.231.110:53293
  INFO root [2019-10-01 16:22:12,228] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:22:12,228] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  WARN root [2019-10-01 16:22:12,384] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20983, errorno=10048
  INFO root [2019-10-01 16:22:12,388] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 12220 ----
  INFO root [2019-10-01 16:22:12,388] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:22:12,537] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 11740 ----
  INFO root [2019-10-01 16:22:12,537] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:22:12,665] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:22:12,665] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:22:12,806] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:22:12,806] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:22:15,013] - ---- cellappmgr is running ----
  INFO root [2019-10-01 16:22:15,013] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:22:15,173] - Components::process(): Request for the process of identity...
 DEBUG root [2019-10-01 16:22:15,173] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:22:15,513] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20419, errorno=10048
 ERROR root [2019-10-01 16:22:15,759] - Components::process: found cellappmgr, addr:10.12.231.110:53305
 ERROR root [2019-10-01 16:22:15,760] - ServerApp::onIdentityillegal: The current process and cellappmgr(componentID=6000 ->conflicted???, pid=11740, addr=10.12.231.110) conflict, the process will exit!
Can modify the components-CID and UID to avoid conflict.
  INFO root [2019-10-01 16:22:16,057] - Shutdowner::onShutdownBegin: shutting down(period=1, tickPeriod=1)
  INFO root [2019-10-01 16:22:17,058] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:22:18,059] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:22:18,306] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:22:18,777] - ThreadPool::destroy(): waiting for thread(2)[0x1bbca70,0x1bbd0f0,], try=1
 DEBUG root [2019-10-01 16:22:19,179] - TPThread::~TPThread(): 0x1bbca70
 DEBUG root [2019-10-01 16:22:19,179] - TPThread::~TPThread(): 0x1bbd0f0
 DEBUG root [2019-10-01 16:22:19,179] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-10-01 16:22:19,816] - Bundle::destroyObjPool(): size 4.
 DEBUG root [2019-10-01 16:22:19,816] - Channel::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:22:19,881] - TCPPacket::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:22:19,881] - UDPPacket::destroyObjPool(): size 12.
 DEBUG root [2019-10-01 16:22:19,881] - EndPoint::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:22:19,881] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:22:19,881] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-10-01 16:22:19,881] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-10-01 16:22:19,881] - cellappmgr(6000) has shut down.
  INFO root [2019-10-01 16:22:21,128] - EventDispatcher()::~EventDispatcher: Num timers = 1
  WARN root [2019-10-01 16:22:21,625] - Forwarding logs to logger[10.12.231.110:53293/0/0/0]...
 ERROR root [2019-10-01 16:23:08,256] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=77804339637, lastReceivedTime=77724896844, inactivityExceptionPeriod=599470073)
  INFO root [2019-10-01 16:23:08,256] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:23:08,291] - ==> [2019-10-01 16:23:08 254] TCPPacketReceiver::processPendingEvents(10.12.231.110:53293): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:23:08,291] - ==> [2019-10-01 16:23:08 256] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=77804339637, lastReceivedTime=77724896844, inactivityExceptionPeriod=599470073)
  WARN root [2019-10-01 16:23:08,301] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53294): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:23:08,301] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=77804826546, lastReceivedTime=77735496915, inactivityExceptionPeriod=599470073)
  INFO root [2019-10-01 16:23:08,316] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:23:08,351] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:23:08,351] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:23:08,351] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:23:14,951] - 
  INFO root [2019-10-01 16:23:14,951] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:23:14,951] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:23:14,951] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:23:14,951] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:23:14,961] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53364 )
  INFO root [2019-10-01 16:23:14,961] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53364, SOMAXCONN=5.
  INFO root [2019-10-01 16:23:14,961] - server-configs:
  INFO root [2019-10-01 16:23:14,961] - 	internalTcpAddr : 10.12.231.110:53364
  INFO root [2019-10-01 16:23:14,961] - 	componentID : 6000
  WARN root [2019-10-01 16:23:14,991] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:23:15,056] - Components::findLogger: found logger, addr:10.12.231.110:53361
  INFO root [2019-10-01 16:23:15,056] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:23:15,056] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:23:15,066] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 2780 ----
  INFO root [2019-10-01 16:23:15,071] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:23:15,071] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:23:15,071] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:23:15,514] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:23:15,514] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:23:21,771] - Forwarding logs to logger[10.12.231.110:53361/0/0/0]...
 ERROR root [2019-10-01 16:29:48,761] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81809456679, lastReceivedTime=81768396127, inactivityExceptionPeriod=599499617)
  INFO root [2019-10-01 16:29:48,761] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:29:48,771] - ==> [2019-10-01 16:29:48 767] TCPPacketReceiver::processPendingEvents(10.12.231.110:53361): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:29:48,771] - ==> [2019-10-01 16:29:48 768] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81809456679, lastReceivedTime=81768396127, inactivityExceptionPeriod=599499617)
  WARN root [2019-10-01 16:29:48,856] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53362): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:29:48,856] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=81810354899, lastReceivedTime=81768805788, inactivityExceptionPeriod=599499617)
  INFO root [2019-10-01 16:29:48,856] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:29:48,861] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:29:48,861] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:29:48,861] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:31:34,971] - 
  INFO root [2019-10-01 16:31:34,976] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:31:34,976] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:31:34,976] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:31:34,976] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:31:34,990] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53491 )
  INFO root [2019-10-01 16:31:34,990] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53491, SOMAXCONN=5.
  INFO root [2019-10-01 16:31:34,990] - server-configs:
  INFO root [2019-10-01 16:31:34,990] - 	internalTcpAddr : 10.12.231.110:53491
  INFO root [2019-10-01 16:31:34,990] - 	componentID : 6000
  WARN root [2019-10-01 16:31:34,990] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:31:35,045] - Components::findLogger: found logger, addr:10.12.231.110:53488
  INFO root [2019-10-01 16:31:35,045] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:31:35,045] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:31:35,050] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 8056 ----
  INFO root [2019-10-01 16:31:35,050] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:31:35,050] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:31:35,050] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:31:35,450] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:31:35,461] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:31:41,721] - Forwarding logs to logger[10.12.231.110:53488/0/0/0]...
 ERROR root [2019-10-01 16:34:00,880] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84330607968, lastReceivedTime=84066757841, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:34:00,880] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:34:00,880] - ==> [2019-10-01 16:34:00 882] TCPPacketReceiver::processPendingEvents(10.12.231.110:53488): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:34:00,880] - ==> [2019-10-01 16:34:00 883] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84330607968, lastReceivedTime=84066757841, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 16:34:00,940] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53490): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:34:00,940] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=84331271063, lastReceivedTime=84067902206, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:34:00,950] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:34:00,950] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:34:00,950] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:34:00,950] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:35:23,635] - 
  INFO root [2019-10-01 16:35:23,635] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:35:23,635] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:35:23,635] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:35:23,635] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:35:23,665] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53567 )
  INFO root [2019-10-01 16:35:23,665] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53567, SOMAXCONN=5.
  INFO root [2019-10-01 16:35:23,665] - server-configs:
  INFO root [2019-10-01 16:35:23,665] - 	internalTcpAddr : 10.12.231.110:53567
  INFO root [2019-10-01 16:35:23,665] - 	componentID : 6000
  WARN root [2019-10-01 16:35:23,670] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:35:23,779] - Components::findLogger: found logger, addr:10.12.231.110:53564
  INFO root [2019-10-01 16:35:23,780] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:35:23,780] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:35:23,789] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 4160 ----
  INFO root [2019-10-01 16:35:23,795] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:35:23,797] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:35:23,797] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:35:24,271] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:35:24,273] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:35:30,510] - Forwarding logs to logger[10.12.231.110:53564/0/0/0]...
 ERROR root [2019-10-01 16:36:54,496] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86066745094, lastReceivedTime=86054914246, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 16:36:54,497] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:36:54,497] - ==> [2019-10-01 16:36:54 487] TCPPacketReceiver::processPendingEvents(10.12.231.110:53564): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:36:54,498] - ==> [2019-10-01 16:36:54 496] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86066745094, lastReceivedTime=86054914246, inactivityExceptionPeriod=599498913)
  WARN root [2019-10-01 16:36:54,589] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53565): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:36:54,592] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=86067707879, lastReceivedTime=86055960775, inactivityExceptionPeriod=599498913)
  INFO root [2019-10-01 16:36:54,598] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:36:54,604] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:36:54,604] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:36:54,604] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:36:54,905] - ThreadPool::destroy(): waiting for thread(2)[0x1d09438,0x1d09ec8,], try=1
  INFO root [2019-10-01 16:38:48,385] - 
  INFO root [2019-10-01 16:38:48,390] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:38:48,390] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:38:48,390] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:38:48,390] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:38:48,425] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53644 )
  INFO root [2019-10-01 16:38:48,425] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53644, SOMAXCONN=5.
  INFO root [2019-10-01 16:38:48,430] - server-configs:
  INFO root [2019-10-01 16:38:48,430] - 	internalTcpAddr : 10.12.231.110:53644
  INFO root [2019-10-01 16:38:48,430] - 	componentID : 6000
  WARN root [2019-10-01 16:38:48,435] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:38:48,580] - Components::findLogger: found logger, addr:10.12.231.110:53641
  INFO root [2019-10-01 16:38:48,582] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:38:48,582] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:38:48,585] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 4508 ----
  INFO root [2019-10-01 16:38:48,595] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:38:48,595] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:38:48,600] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:38:49,050] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:38:49,054] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:38:55,320] - Forwarding logs to logger[10.12.231.110:53641/0/0/0]...
 ERROR root [2019-10-01 16:41:28,559] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88807385468, lastReceivedTime=88702734427, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:41:28,562] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:41:28,562] - ==> [2019-10-01 16:41:28 559] TCPPacketReceiver::processPendingEvents(10.12.231.110:53641): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:41:28,563] - ==> [2019-10-01 16:41:28 561] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88807385468, lastReceivedTime=88702734427, inactivityExceptionPeriod=599500064)
  WARN root [2019-10-01 16:41:28,662] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53642): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:41:28,665] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=88808439010, lastReceivedTime=88703675540, inactivityExceptionPeriod=599500064)
  INFO root [2019-10-01 16:41:28,677] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:41:28,679] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:41:28,680] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:41:28,680] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:41:28,981] - ThreadPool::destroy(): waiting for thread(2)[0x178c280,0x178c558,], try=1
  INFO root [2019-10-01 16:41:52,865] - 
  INFO root [2019-10-01 16:41:52,865] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:41:52,870] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:41:52,870] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:41:52,870] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:41:52,880] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53720 )
  INFO root [2019-10-01 16:41:52,880] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53720, SOMAXCONN=5.
  INFO root [2019-10-01 16:41:52,880] - server-configs:
  INFO root [2019-10-01 16:41:52,882] - 	internalTcpAddr : 10.12.231.110:53720
  INFO root [2019-10-01 16:41:52,882] - 	componentID : 6000
  WARN root [2019-10-01 16:41:52,882] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:41:53,150] - Components::findLogger: found logger, addr:10.12.231.110:53717
  INFO root [2019-10-01 16:41:53,150] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:41:53,150] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:41:53,160] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 10260 ----
  INFO root [2019-10-01 16:41:53,165] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:41:53,165] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:41:53,165] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:41:53,600] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:41:53,600] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:41:59,790] - Forwarding logs to logger[10.12.231.110:53717/0/0/0]...
 ERROR root [2019-10-01 16:45:04,191] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90963702510, lastReceivedTime=90847368643, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:45:04,198] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:45:04,199] - ==> [2019-10-01 16:45:04 192] TCPPacketReceiver::processPendingEvents(10.12.231.110:53717): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:45:04,199] - ==> [2019-10-01 16:45:04 192] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90963702510, lastReceivedTime=90847368643, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 16:45:04,343] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:45:04,344] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=90965225673, lastReceivedTime=90850047990, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:45:04,345] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:45:04,345] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:45:04,345] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:45:04,346] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-10-01 16:45:04,646] - ThreadPool::destroy(): waiting for thread(2)[0x18e81a0,0x18e7c58,], try=1
  INFO root [2019-10-01 16:47:27,742] - 
  INFO root [2019-10-01 16:47:27,742] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:47:27,742] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:47:27,742] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:47:27,742] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:47:27,753] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53809 )
  INFO root [2019-10-01 16:47:27,753] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53809, SOMAXCONN=5.
  INFO root [2019-10-01 16:47:27,753] - server-configs:
  INFO root [2019-10-01 16:47:27,760] - 	internalTcpAddr : 10.12.231.110:53809
  INFO root [2019-10-01 16:47:27,760] - 	componentID : 6000
  WARN root [2019-10-01 16:47:27,761] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:47:27,912] - Components::findLogger: found logger, addr:10.12.231.110:53806
  INFO root [2019-10-01 16:47:27,914] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:47:27,914] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:47:27,922] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 12076 ----
  INFO root [2019-10-01 16:47:27,924] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:47:27,924] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:47:27,924] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:47:28,346] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:47:28,346] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:47:34,555] - Forwarding logs to logger[10.12.231.110:53806/0/0/0]...
 ERROR root [2019-10-01 16:49:22,956] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551349720, lastReceivedTime=93295963054, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:49:22,957] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:49:22,958] - ==> [2019-10-01 16:49:22 955] TCPPacketReceiver::processPendingEvents(10.12.231.110:53806): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:49:22,958] - ==> [2019-10-01 16:49:22 957] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551349720, lastReceivedTime=93295963054, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 16:49:23,016] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53807): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:49:23,018] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=93551977355, lastReceivedTime=93298103455, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 16:49:23,022] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:49:23,023] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:49:23,024] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:49:23,024] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:50:11,130] - 
  INFO root [2019-10-01 16:50:11,136] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:50:11,137] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:50:11,137] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:50:11,137] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:50:11,177] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:53887 )
  INFO root [2019-10-01 16:50:11,177] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:53887, SOMAXCONN=5.
  INFO root [2019-10-01 16:50:11,177] - server-configs:
  INFO root [2019-10-01 16:50:11,177] - 	internalTcpAddr : 10.12.231.110:53887
  INFO root [2019-10-01 16:50:11,177] - 	componentID : 6000
  WARN root [2019-10-01 16:50:11,180] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:50:11,374] - Components::findLogger: found logger, addr:10.12.231.110:53884
  INFO root [2019-10-01 16:50:11,374] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:50:11,374] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:50:11,379] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 5728 ----
  INFO root [2019-10-01 16:50:11,391] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:50:11,392] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:50:11,392] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:50:11,898] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:50:11,899] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:50:18,026] - Forwarding logs to logger[10.12.231.110:53884/0/0/0]...
 ERROR root [2019-10-01 16:51:42,590] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94947717267, lastReceivedTime=94930294847, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:51:42,590] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:51:42,590] - ==> [2019-10-01 16:51:42 593] TCPPacketReceiver::processPendingEvents(10.12.231.110:53884): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:51:42,590] - ==> [2019-10-01 16:51:42 594] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94947717267, lastReceivedTime=94930294847, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 16:51:42,669] - TCPPacketReceiver::processPendingEvents(10.12.231.110:53885): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:51:42,669] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=94948557766, lastReceivedTime=94931692300, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 16:51:42,681] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:51:42,685] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:51:42,685] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:51:42,685] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:55:06,280] - 
  INFO root [2019-10-01 16:55:06,281] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:55:06,282] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:55:06,282] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:55:06,282] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:55:06,329] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54002 )
  INFO root [2019-10-01 16:55:06,329] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54002, SOMAXCONN=5.
  INFO root [2019-10-01 16:55:06,329] - server-configs:
  INFO root [2019-10-01 16:55:06,330] - 	internalTcpAddr : 10.12.231.110:54002
  INFO root [2019-10-01 16:55:06,330] - 	componentID : 6000
  WARN root [2019-10-01 16:55:06,340] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:55:06,597] - Components::findLogger: found logger, addr:10.12.231.110:53999
  INFO root [2019-10-01 16:55:06,598] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:55:06,598] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:55:06,606] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 9268 ----
  INFO root [2019-10-01 16:55:06,610] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:55:06,612] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:55:06,612] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:55:07,084] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:55:07,093] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:55:13,249] - Forwarding logs to logger[10.12.231.110:53999/0/0/0]...
 ERROR root [2019-10-01 16:56:56,594] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98087730594, lastReceivedTime=97881943325, inactivityExceptionPeriod=599497507)
  INFO root [2019-10-01 16:56:56,597] - The following logs sent to logger failed:
  WARN root [2019-10-01 16:56:56,597] - ==> [2019-10-01 16:56:56 593] TCPPacketReceiver::processPendingEvents(10.12.231.110:53999): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:56:56,598] - ==> [2019-10-01 16:56:56 595] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98087730594, lastReceivedTime=97881943325, inactivityExceptionPeriod=599497507)
  WARN root [2019-10-01 16:56:56,663] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54000): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 16:56:56,664] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=98088430377, lastReceivedTime=97883573883, inactivityExceptionPeriod=599497507)
  INFO root [2019-10-01 16:56:56,668] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 16:56:56,669] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 16:56:56,670] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 16:56:56,670] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 16:58:25,529] - 
  INFO root [2019-10-01 16:58:25,560] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 16:58:25,561] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 16:58:25,561] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 16:58:25,561] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 16:58:25,592] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54086 )
  INFO root [2019-10-01 16:58:25,592] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54086, SOMAXCONN=5.
  INFO root [2019-10-01 16:58:25,592] - server-configs:
  INFO root [2019-10-01 16:58:25,593] - 	internalTcpAddr : 10.12.231.110:54086
  INFO root [2019-10-01 16:58:25,593] - 	componentID : 6000
  WARN root [2019-10-01 16:58:25,597] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 16:58:25,836] - Components::findLogger: found logger, addr:10.12.231.110:54083
  INFO root [2019-10-01 16:58:25,836] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 16:58:25,837] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 16:58:25,844] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 10548 ----
  INFO root [2019-10-01 16:58:25,851] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 16:58:25,853] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 16:58:25,853] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 16:58:26,358] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 16:58:26,361] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 16:58:32,511] - Forwarding logs to logger[10.12.231.110:54083/0/0/0]...
 ERROR root [2019-10-01 17:00:23,965] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100161437242, lastReceivedTime=99874398987, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:00:23,967] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:00:23,968] - ==> [2019-10-01 17:00:23 964] TCPPacketReceiver::processPendingEvents(10.12.231.110:54083): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:00:23,968] - ==> [2019-10-01 17:00:23 966] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100161437242, lastReceivedTime=99874398987, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 17:00:24,034] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54084): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:00:24,037] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=100162157921, lastReceivedTime=99875826352, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:00:24,042] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:00:24,044] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:00:24,044] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:00:24,044] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:02:51,210] - 
  INFO root [2019-10-01 17:02:51,211] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:02:51,212] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:02:51,212] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:02:51,212] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:02:51,222] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54178 )
  INFO root [2019-10-01 17:02:51,222] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54178, SOMAXCONN=5.
  INFO root [2019-10-01 17:02:51,222] - server-configs:
  INFO root [2019-10-01 17:02:51,223] - 	internalTcpAddr : 10.12.231.110:54178
  INFO root [2019-10-01 17:02:51,223] - 	componentID : 6000
  WARN root [2019-10-01 17:02:51,223] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:02:51,377] - Components::findLogger: found logger, addr:10.12.231.110:54175
  INFO root [2019-10-01 17:02:51,378] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:02:51,378] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:02:51,385] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 13240 ----
  INFO root [2019-10-01 17:02:51,393] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:02:51,398] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:02:51,399] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:02:51,876] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:02:51,910] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:02:55,364] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20401, errorno=10048
  WARN root [2019-10-01 17:02:58,402] - Forwarding logs to logger[10.12.231.110:54175/0/0/0]...
 ERROR root [2019-10-01 17:06:35,969] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103881480036, lastReceivedTime=103730546594, inactivityExceptionPeriod=596292372)
  INFO root [2019-10-01 17:06:35,974] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:06:35,974] - ==> [2019-10-01 17:06:35 969] TCPPacketReceiver::processPendingEvents(10.12.231.110:54175): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:06:35,975] - ==> [2019-10-01 17:06:35 970] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103881480036, lastReceivedTime=103730546594, inactivityExceptionPeriod=596292372)
  WARN root [2019-10-01 17:06:36,055] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54176): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:06:36,056] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=103882351597, lastReceivedTime=103732369106, inactivityExceptionPeriod=596292372)
  INFO root [2019-10-01 17:06:36,061] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:06:36,064] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:06:36,064] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:06:36,064] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:08:32,012] - 
  INFO root [2019-10-01 17:08:32,037] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:08:32,039] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:08:32,040] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:08:32,040] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:08:32,066] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54275 )
  INFO root [2019-10-01 17:08:32,066] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54275, SOMAXCONN=5.
  INFO root [2019-10-01 17:08:32,066] - server-configs:
  INFO root [2019-10-01 17:08:32,066] - 	internalTcpAddr : 10.12.231.110:54275
  INFO root [2019-10-01 17:08:32,067] - 	componentID : 6000
  WARN root [2019-10-01 17:08:32,069] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:08:32,260] - Components::findLogger: found logger, addr:10.12.231.110:54272
  INFO root [2019-10-01 17:08:32,260] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:08:32,260] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:08:32,265] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 812 ----
  INFO root [2019-10-01 17:08:32,270] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:08:32,275] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:08:32,276] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:08:32,742] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:08:32,742] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:08:38,905] - Forwarding logs to logger[10.12.231.110:54272/0/0/0]...
 ERROR root [2019-10-01 17:09:01,668] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105338465669, lastReceivedTime=105044402812, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:09:01,672] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:09:01,672] - ==> [2019-10-01 17:09:01 667] TCPPacketReceiver::processPendingEvents(10.12.231.110:54272): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:09:01,672] - ==> [2019-10-01 17:09:01 669] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105338465669, lastReceivedTime=105044402812, inactivityExceptionPeriod=599499873)
  WARN root [2019-10-01 17:09:01,761] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54273): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:09:01,762] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=105339410478, lastReceivedTime=105161965608, inactivityExceptionPeriod=599499873)
  INFO root [2019-10-01 17:09:01,774] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:09:01,787] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:09:01,787] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:09:01,787] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:09:03,657] - 
  INFO root [2019-10-01 17:09:03,671] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:09:03,672] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:09:03,672] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:09:03,672] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:09:03,743] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54311 )
  INFO root [2019-10-01 17:09:03,744] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54311, SOMAXCONN=5.
  INFO root [2019-10-01 17:09:03,744] - server-configs:
  INFO root [2019-10-01 17:09:03,744] - 	internalTcpAddr : 10.12.231.110:54311
  INFO root [2019-10-01 17:09:03,744] - 	componentID : 6000
  WARN root [2019-10-01 17:09:03,755] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:09:04,048] - Components::findLogger: found logger, addr:10.12.231.110:54309
  INFO root [2019-10-01 17:09:04,048] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:09:04,048] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:09:04,059] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 11704 ----
  INFO root [2019-10-01 17:09:04,065] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:09:04,066] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:09:04,067] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:09:04,514] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:09:04,516] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:09:10,637] - Forwarding logs to logger[10.12.231.110:54309/0/0/0]...
 ERROR root [2019-10-01 17:14:20,747] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529260315, lastReceivedTime=108356149732, inactivityExceptionPeriod=599498658)
  INFO root [2019-10-01 17:14:20,750] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:14:20,751] - ==> [2019-10-01 17:14:20 744] TCPPacketReceiver::processPendingEvents(10.12.231.110:54309): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:14:20,751] - ==> [2019-10-01 17:14:20 748] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529260315, lastReceivedTime=108356149732, inactivityExceptionPeriod=599498658)
  WARN root [2019-10-01 17:14:20,816] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54312): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:14:20,816] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=108529949972, lastReceivedTime=108359195892, inactivityExceptionPeriod=599498658)
  INFO root [2019-10-01 17:14:20,820] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:14:20,822] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:14:20,822] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:14:20,822] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:15:33,276] - 
  INFO root [2019-10-01 17:15:33,277] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:15:33,278] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:15:33,278] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:15:33,278] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:15:33,296] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54400 )
  INFO root [2019-10-01 17:15:33,296] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54400, SOMAXCONN=5.
  INFO root [2019-10-01 17:15:33,296] - server-configs:
  INFO root [2019-10-01 17:15:33,296] - 	internalTcpAddr : 10.12.231.110:54400
  INFO root [2019-10-01 17:15:33,297] - 	componentID : 6000
  WARN root [2019-10-01 17:15:33,298] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:15:33,670] - Components::findLogger: found logger, addr:10.12.231.110:54397
  INFO root [2019-10-01 17:15:33,670] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:15:33,670] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:15:33,676] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 12024 ----
  INFO root [2019-10-01 17:15:33,676] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:15:33,676] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:15:33,676] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:15:34,130] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:15:34,131] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:15:40,277] - Forwarding logs to logger[10.12.231.110:54397/0/0/0]...
 ERROR root [2019-10-01 17:17:07,093] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110192719680, lastReceivedTime=110152063909, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:17:07,095] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:17:07,095] - ==> [2019-10-01 17:17:07 090] TCPPacketReceiver::processPendingEvents(10.12.231.110:54397): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:17:07,095] - ==> [2019-10-01 17:17:07 094] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110192719680, lastReceivedTime=110152063909, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 17:17:07,163] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54398): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:17:07,165] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=110193441423, lastReceivedTime=110153390311, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:17:07,173] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:17:07,174] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:18:07,935] - 
  INFO root [2019-10-01 17:18:07,937] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:18:07,938] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:18:07,938] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:18:07,938] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:18:07,958] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54462 )
  INFO root [2019-10-01 17:18:07,958] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54462, SOMAXCONN=5.
  INFO root [2019-10-01 17:18:07,958] - server-configs:
  INFO root [2019-10-01 17:18:07,959] - 	internalTcpAddr : 10.12.231.110:54462
  INFO root [2019-10-01 17:18:07,959] - 	componentID : 6000
  WARN root [2019-10-01 17:18:07,963] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:18:08,302] - Components::findLogger: found logger, addr:10.12.231.110:54459
  INFO root [2019-10-01 17:18:08,303] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:18:08,303] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:18:08,308] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 3564 ----
  INFO root [2019-10-01 17:18:08,309] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:18:08,309] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:18:08,310] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:18:08,742] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:18:08,743] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:18:14,876] - Forwarding logs to logger[10.12.231.110:54459/0/0/0]...
 ERROR root [2019-10-01 17:23:34,297] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114064759047, lastReceivedTime=113798769919, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:23:34,300] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:23:34,301] - ==> [2019-10-01 17:23:34 296] TCPPacketReceiver::processPendingEvents(10.12.231.110:54459): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:23:34,301] - ==> [2019-10-01 17:23:34 298] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114064759047, lastReceivedTime=113798769919, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 17:23:34,363] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54460): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:23:34,365] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=114065433857, lastReceivedTime=113799968000, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:23:34,373] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:23:34,374] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:23:34,374] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:23:34,374] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:23:36,428] - 
  INFO root [2019-10-01 17:23:36,429] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:23:36,430] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:23:36,430] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:23:36,430] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:23:36,443] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54559 )
  INFO root [2019-10-01 17:23:36,443] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54559, SOMAXCONN=5.
  INFO root [2019-10-01 17:23:36,443] - server-configs:
  INFO root [2019-10-01 17:23:36,443] - 	internalTcpAddr : 10.12.231.110:54559
  INFO root [2019-10-01 17:23:36,443] - 	componentID : 6000
  WARN root [2019-10-01 17:23:36,444] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:23:36,671] - Components::findLogger: found logger, addr:10.12.231.110:54556
  INFO root [2019-10-01 17:23:36,672] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:23:36,672] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:23:36,693] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 10068 ----
  INFO root [2019-10-01 17:23:36,695] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:23:36,697] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:23:36,698] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:23:37,137] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:23:37,142] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:23:43,286] - Forwarding logs to logger[10.12.231.110:54556/0/0/0]...
 ERROR root [2019-10-01 17:25:28,806] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115209844184, lastReceivedTime=114983498070, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:25:28,811] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:25:28,811] - ==> [2019-10-01 17:25:28 801] TCPPacketReceiver::processPendingEvents(10.12.231.110:54556): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:25:28,811] - ==> [2019-10-01 17:25:28 806] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115209844184, lastReceivedTime=114983498070, inactivityExceptionPeriod=599500000)
  WARN root [2019-10-01 17:25:28,882] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54558): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:25:28,884] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=115210626527, lastReceivedTime=114985218780, inactivityExceptionPeriod=599500000)
  INFO root [2019-10-01 17:25:28,888] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:25:28,889] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:25:28,889] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:25:28,889] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:26:25,787] - 
  INFO root [2019-10-01 17:26:25,799] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:26:25,800] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:26:25,801] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:26:25,801] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:26:25,818] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54638 )
  INFO root [2019-10-01 17:26:25,818] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54638, SOMAXCONN=5.
  INFO root [2019-10-01 17:26:25,819] - server-configs:
  INFO root [2019-10-01 17:26:25,820] - 	internalTcpAddr : 10.12.231.110:54638
  INFO root [2019-10-01 17:26:25,820] - 	componentID : 6000
  WARN root [2019-10-01 17:26:25,822] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:26:26,042] - Components::findLogger: found logger, addr:10.12.231.110:54635
  INFO root [2019-10-01 17:26:26,042] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:26:26,043] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:26:26,050] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 11504 ----
  INFO root [2019-10-01 17:26:26,052] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:26:26,056] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:26:26,056] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:26:26,546] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:26:26,555] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:26:32,733] - Forwarding logs to logger[10.12.231.110:54635/0/0/0]...
 ERROR root [2019-10-01 17:27:59,622] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718008503, lastReceivedTime=116676254299, inactivityExceptionPeriod=599500192)
  INFO root [2019-10-01 17:27:59,628] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:27:59,628] - ==> [2019-10-01 17:27:59 619] TCPPacketReceiver::processPendingEvents(10.12.231.110:54635): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:27:59,629] - ==> [2019-10-01 17:27:59 623] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718008503, lastReceivedTime=116676254299, inactivityExceptionPeriod=599500192)
  WARN root [2019-10-01 17:27:59,699] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54636): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:27:59,701] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=116718805160, lastReceivedTime=116679085367, inactivityExceptionPeriod=599500192)
  INFO root [2019-10-01 17:27:59,709] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:27:59,710] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:27:59,710] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:27:59,711] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 17:28:57,715] - 
  INFO root [2019-10-01 17:28:57,716] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 17:28:57,718] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 17:28:57,718] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 17:28:57,720] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 17:28:57,748] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.12.231.110 ( 10.12.231.110:54716 )
  INFO root [2019-10-01 17:28:57,748] - NetworkInterface::initialize(INTERNAL-TCP): address 10.12.231.110:54716, SOMAXCONN=5.
  INFO root [2019-10-01 17:28:57,748] - server-configs:
  INFO root [2019-10-01 17:28:57,748] - 	internalTcpAddr : 10.12.231.110:54716
  INFO root [2019-10-01 17:28:57,748] - 	componentID : 6000
  WARN root [2019-10-01 17:28:57,751] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 17:28:58,007] - Components::findLogger: found logger, addr:10.12.231.110:54713
  INFO root [2019-10-01 17:28:58,007] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-10-01 17:28:58,008] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-10-01 17:28:58,019] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 6012 ----
  INFO root [2019-10-01 17:28:58,039] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 17:28:58,039] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 17:28:58,039] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 17:28:58,544] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 17:28:58,579] - Components::process(): Request for the process of identity...
  WARN root [2019-10-01 17:29:04,743] - Forwarding logs to logger[10.12.231.110:54713/0/0/0]...
 ERROR root [2019-10-01 17:30:08,429] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006077579, lastReceivedTime=117895922812, inactivityExceptionPeriod=599497826)
  INFO root [2019-10-01 17:30:08,434] - The following logs sent to logger failed:
  WARN root [2019-10-01 17:30:08,434] - ==> [2019-10-01 17:30:08 428] TCPPacketReceiver::processPendingEvents(10.12.231.110:54713): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:30:08,434] - ==> [2019-10-01 17:30:08 430] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006077579, lastReceivedTime=117895922812, inactivityExceptionPeriod=599497826)
  WARN root [2019-10-01 17:30:08,502] - TCPPacketReceiver::processPendingEvents(10.12.231.110:54714): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-10-01 17:30:08,508] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=118006864220, lastReceivedTime=117897211264, inactivityExceptionPeriod=599497826)
  INFO root [2019-10-01 17:30:08,513] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-10-01 17:30:08,513] - Shutdowner::onShutdown: shutting down
  INFO root [2019-10-01 17:30:08,514] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-10-01 17:30:08,514] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-10-01 22:37:11,382] - 
  INFO root [2019-10-01 22:37:11,398] - -----------------------------------------------------------------------------------------


  INFO root [2019-10-01 22:37:11,429] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-10-01 22:37:11,429] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-10-01 22:37:11,429] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-10-01 22:37:11,476] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 127.0.0.1 ( 127.0.0.1:49715 )
  INFO root [2019-10-01 22:37:11,476] - NetworkInterface::initialize(INTERNAL-TCP): address 127.0.0.1:49715, SOMAXCONN=5.
  INFO root [2019-10-01 22:37:11,476] - server-configs:
  INFO root [2019-10-01 22:37:11,476] - 	internalTcpAddr : 127.0.0.1:49715
  INFO root [2019-10-01 22:37:11,476] - 	componentID : 6000
  WARN root [2019-10-01 22:37:11,476] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-10-01 22:37:13,038] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 8184 ----
  INFO root [2019-10-01 22:37:13,038] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-10-01 22:37:13,069] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-10-01 22:37:13,069] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-10-01 22:37:13,553] - ---- cellappmgr is running ----
 DEBUG root [2019-10-01 22:37:13,553] - Components::process(): Request for the process of identity...
  INFO root [2019-10-01 22:37:20,880] - Components::findComponents: find logger(1)...
 ERROR root [2019-10-01 22:37:22,395] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:22,395] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:37:22,395] - Components::findComponents: not found logger!
  INFO root [2019-10-01 22:37:23,410] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-10-01 22:37:24,926] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:24,926] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:25,941] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-10-01 22:37:27,456] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:27,456] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:28,472] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-10-01 22:37:29,987] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:29,987] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:31,002] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-10-01 22:37:32,518] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:32,518] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:33,533] - Components::findComponents: find dbmgr(5)...
 ERROR root [2019-10-01 22:37:35,048] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:35,048] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:36,064] - Components::findComponents: find dbmgr(6)...
 ERROR root [2019-10-01 22:37:37,579] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:37,579] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:38,610] - Components::findComponents: find dbmgr(7)...
 ERROR root [2019-10-01 22:37:40,125] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:40,125] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:41,141] - Components::findComponents: find dbmgr(8)...
 ERROR root [2019-10-01 22:37:42,656] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:42,656] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:43,671] - Components::findComponents: find dbmgr(9)...
 ERROR root [2019-10-01 22:37:45,187] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:45,187] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:46,202] - Components::findComponents: find dbmgr(10)...
 ERROR root [2019-10-01 22:37:47,717] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:47,717] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:48,733] - Components::findComponents: find dbmgr(11)...
 ERROR root [2019-10-01 22:37:50,248] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:50,248] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:51,263] - Components::findComponents: find dbmgr(12)...
 ERROR root [2019-10-01 22:37:52,778] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:52,778] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:53,809] - Components::findComponents: find dbmgr(13)...
 ERROR root [2019-10-01 22:37:55,325] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:55,325] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:56,340] - Components::findComponents: find dbmgr(14)...
 ERROR root [2019-10-01 22:37:57,855] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:37:57,855] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:37:58,871] - Components::findComponents: find dbmgr(15)...
 ERROR root [2019-10-01 22:38:00,386] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:00,386] - Components::findComponents: receive error!
  INFO root [2019-10-01 22:38:01,401] - Components::findComponents: find dbmgr(16)...
 ERROR root [2019-10-01 22:38:02,917] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:02,917] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:03,932] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:05,447] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:05,447] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:06,463] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:07,978] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:07,978] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:08,993] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:10,509] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:10,509] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:11,524] - Components::findComponents: find dbmgr(20)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:13,039] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:13,039] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:14,070] - Components::findComponents: find dbmgr(21)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:15,586] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:15,586] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:16,601] - Components::findComponents: find dbmgr(22)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:18,116] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:18,116] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:19,132] - Components::findComponents: find dbmgr(23)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:20,647] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:20,647] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:21,662] - Components::findComponents: find dbmgr(24)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:23,178] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:23,178] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:24,193] - Components::findComponents: find dbmgr(25)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:25,708] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:25,708] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:26,724] - Components::findComponents: find dbmgr(26)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:28,239] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:28,239] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:29,270] - Components::findComponents: find dbmgr(27)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:30,785] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:30,785] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:31,801] - Components::findComponents: find dbmgr(28)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:33,316] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:33,316] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:34,331] - Components::findComponents: find dbmgr(29)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:35,846] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:35,846] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:36,862] - Components::findComponents: find dbmgr(30)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:38,377] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:38,377] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:39,393] - Components::findComponents: find dbmgr(31)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:40,908] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:40,908] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:41,923] - Components::findComponents: find dbmgr(32)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:43,438] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:43,438] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:44,469] - Components::findComponents: find dbmgr(33)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:45,985] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:45,985] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:47,000] - Components::findComponents: find dbmgr(34)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:48,515] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:48,515] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:49,531] - Components::findComponents: find dbmgr(35)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:51,046] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:51,046] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:52,061] - Components::findComponents: find dbmgr(36)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:53,577] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:53,577] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:54,592] - Components::findComponents: find dbmgr(37)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:56,107] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:56,107] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:57,123] - Components::findComponents: find dbmgr(38)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:38:58,638] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:38:58,638] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:38:59,653] - Components::findComponents: find dbmgr(39)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:01,169] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:01,169] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:02,184] - Components::findComponents: find dbmgr(40)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:03,699] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:03,699] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:04,730] - Components::findComponents: find dbmgr(41)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:06,246] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:06,246] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:07,261] - Components::findComponents: find dbmgr(42)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:08,776] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:08,776] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:09,792] - Components::findComponents: find dbmgr(43)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:11,307] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:11,307] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:12,322] - Components::findComponents: find dbmgr(44)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:13,838] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:13,838] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:14,853] - Components::findComponents: find dbmgr(45)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:16,368] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:16,368] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:17,384] - Components::findComponents: find dbmgr(46)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:18,899] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:18,899] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:19,930] - Components::findComponents: find dbmgr(47)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:21,445] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:21,445] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:22,460] - Components::findComponents: find dbmgr(48)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:23,976] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:23,976] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:24,991] - Components::findComponents: find dbmgr(49)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:26,506] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:26,506] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:27,522] - Components::findComponents: find dbmgr(50)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:29,037] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:29,037] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:30,052] - Components::findComponents: find dbmgr(51)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:31,568] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:31,568] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:32,583] - Components::findComponents: find dbmgr(52)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:34,098] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:34,098] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:35,129] - Components::findComponents: find dbmgr(53)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:36,645] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:36,645] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:37,660] - Components::findComponents: find dbmgr(54)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:39,175] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:39,175] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:40,191] - Components::findComponents: find dbmgr(55)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:41,706] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:41,706] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:42,721] - Components::findComponents: find dbmgr(56)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:44,237] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:44,237] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:45,252] - Components::findComponents: find dbmgr(57)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:46,767] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:46,767] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:47,783] - Components::findComponents: find dbmgr(58)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:49,298] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:49,298] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:50,329] - Components::findComponents: find dbmgr(59)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:51,844] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:51,844] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:52,860] - Components::findComponents: find dbmgr(60)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:54,362] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:54,362] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:55,393] - Components::findComponents: find dbmgr(61)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:56,908] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:56,908] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:39:57,923] - Components::findComponents: find dbmgr(62)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:39:59,439] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:39:59,439] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:00,470] - Components::findComponents: find dbmgr(63)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:01,985] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:01,985] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:03,000] - Components::findComponents: find dbmgr(64)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:04,516] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:04,516] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:05,531] - Components::findComponents: find dbmgr(65)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:07,046] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:07,046] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:08,062] - Components::findComponents: find dbmgr(66)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:09,577] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:09,577] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:10,592] - Components::findComponents: find dbmgr(67)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:12,108] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:12,108] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:13,123] - Components::findComponents: find dbmgr(68)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:14,638] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:14,638] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:15,669] - Components::findComponents: find dbmgr(69)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:17,184] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:17,184] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:18,200] - Components::findComponents: find dbmgr(70)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:19,715] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:19,715] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:20,730] - Components::findComponents: find dbmgr(71)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:22,246] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:22,246] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:23,261] - Components::findComponents: find dbmgr(72)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:24,776] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:24,776] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:25,792] - Components::findComponents: find dbmgr(73)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:27,307] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:27,307] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:28,322] - Components::findComponents: find dbmgr(74)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:29,838] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:29,838] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:30,869] - Components::findComponents: find dbmgr(75)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:32,384] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:32,384] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:33,399] - Components::findComponents: find dbmgr(76)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:34,915] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:34,915] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:35,930] - Components::findComponents: find dbmgr(77)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:37,445] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:37,445] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:38,461] - Components::findComponents: find dbmgr(78)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:39,976] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:39,976] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:40,991] - Components::findComponents: find dbmgr(79)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:42,507] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:42,507] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:43,522] - Components::findComponents: find dbmgr(80)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:45,037] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:45,037] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:46,053] - Components::findComponents: find dbmgr(81)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:47,568] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:47,568] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:48,583] - Components::findComponents: find dbmgr(82)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:50,099] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:50,099] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:51,130] - Components::findComponents: find dbmgr(83)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:52,645] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:52,645] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:53,660] - Components::findComponents: find dbmgr(84)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:55,176] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:55,176] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:56,191] - Components::findComponents: find dbmgr(85)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:40:57,706] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:40:57,706] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:40:58,722] - Components::findComponents: find dbmgr(86)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:00,237] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:00,237] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:01,252] - Components::findComponents: find dbmgr(87)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:02,767] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:02,767] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:03,783] - Components::findComponents: find dbmgr(88)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:05,298] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:05,298] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:06,329] - Components::findComponents: find dbmgr(89)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:07,844] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:07,844] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:08,860] - Components::findComponents: find dbmgr(90)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:10,375] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:10,375] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:11,390] - Components::findComponents: find dbmgr(91)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:12,906] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:12,906] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:13,921] - Components::findComponents: find dbmgr(92)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:15,436] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:15,436] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:16,452] - Components::findComponents: find dbmgr(93)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:17,967] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:17,967] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:18,982] - Components::findComponents: find dbmgr(94)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:20,498] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:20,498] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:21,529] - Components::findComponents: find dbmgr(95)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:23,044] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:23,044] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:24,059] - Components::findComponents: find dbmgr(96)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:25,575] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:25,575] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:26,590] - Components::findComponents: find dbmgr(97)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:28,105] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:28,105] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:29,121] - Components::findComponents: find dbmgr(98)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:30,636] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:30,636] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:31,651] - Components::findComponents: find dbmgr(99)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:33,167] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:33,167] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:34,182] - Components::findComponents: find dbmgr(100)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:35,697] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:35,697] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:36,728] - Components::findComponents: find dbmgr(101)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:38,244] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:38,244] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:39,259] - Components::findComponents: find dbmgr(102)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:40,774] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:40,774] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:41,790] - Components::findComponents: find dbmgr(103)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:43,305] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:43,305] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:44,320] - Components::findComponents: find dbmgr(104)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:45,836] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:45,836] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:46,851] - Components::findComponents: find dbmgr(105)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:48,366] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:48,366] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:49,382] - Components::findComponents: find dbmgr(106)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:50,897] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:50,897] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:51,912] - Components::findComponents: find dbmgr(107)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:53,427] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:53,427] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:54,443] - Components::findComponents: find dbmgr(108)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-10-01 22:41:55,958] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-10-01 22:41:55,958] - Components::findComponents: receive error!
  WARN root [2019-10-01 22:41:56,989] - Components::findComponents: find dbmgr(109)...
delay time is too long, please check the dbmgr logs!
