  INFO root [2019-09-03 21:24:27,409] - 
  INFO root [2019-09-03 21:24:27,409] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-03 21:24:27,939] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-03 21:24:27,939] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-03 21:24:27,939] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-03 21:24:28,059] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:52645 )
  INFO root [2019-09-03 21:24:28,059] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:52645, SOMAXCONN=5.
  INFO root [2019-09-03 21:24:28,059] - server-configs:
  INFO root [2019-09-03 21:24:28,059] - 	internalTcpAddr : 192.168.56.1:52645
  INFO root [2019-09-03 21:24:28,059] - 	componentID : 6000
  WARN root [2019-09-03 21:24:28,059] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-03 21:24:29,698] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 2082. PID: 12956 ----
  INFO root [2019-09-03 21:24:29,698] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-03 21:24:29,749] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-03 21:24:29,759] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-03 21:24:30,959] - ---- cellappmgr is running ----
 DEBUG root [2019-09-03 21:24:30,959] - Components::process(): Request for the process of identity...
  INFO root [2019-09-03 21:24:38,999] - Components::findComponents: find logger(1)...
  INFO root [2019-09-03 21:24:39,223] - Components::findComponents: found logger, addr:192.168.56.1:52648
  INFO root [2019-09-03 21:24:39,223] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-03 21:24:39,223] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-03 21:24:39,289] - Components::findComponents: find dbmgr(2)...
  WARN root [2019-09-03 21:24:40,389] - Forwarding logs to logger[192.168.56.1:52648/0/0/0]...
 ERROR root [2019-09-03 21:36:03,748] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=270510429218, lastReceivedTime=270504686291, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-03 21:36:03,748] - The following logs sent to logger failed:
  WARN root [2019-09-03 21:36:03,758] - ==> [2019-09-03 21:36:03 751] TCPPacketReceiver::processPendingEvents(192.168.56.1:52648): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-03 21:36:03,758] - ==> [2019-09-03 21:36:03 752] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=270510429218, lastReceivedTime=270504686291, inactivityExceptionPeriod=134887628)
  WARN root [2019-09-03 21:36:03,868] - TCPPacketReceiver::processPendingEvents(192.168.56.1:52649): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-03 21:36:03,868] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=270510705590, lastReceivedTime=270506576329, inactivityExceptionPeriod=134887628)
  INFO root [2019-09-03 21:36:03,918] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-03 21:36:03,918] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-03 21:36:03,918] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-03 21:36:03,958] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-03 21:36:05,633] - 
  INFO root [2019-09-03 21:36:05,642] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-03 21:36:05,642] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-03 21:36:05,642] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-03 21:36:05,642] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-03 21:36:05,662] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:52852 )
  INFO root [2019-09-03 21:36:05,662] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:52852, SOMAXCONN=5.
  INFO root [2019-09-03 21:36:05,662] - server-configs:
  INFO root [2019-09-03 21:36:05,662] - 	internalTcpAddr : 192.168.56.1:52852
  INFO root [2019-09-03 21:36:05,662] - 	componentID : 6000
  WARN root [2019-09-03 21:36:05,672] - invalid UID(0) <= 0, please check UID for environment! automatically set to 2082.
  INFO root [2019-09-03 21:36:07,187] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 2082. PID: 3948 ----
  INFO root [2019-09-03 21:36:07,187] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-03 21:36:07,187] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-03 21:36:07,187] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-03 21:36:07,593] - ---- cellappmgr is running ----
 DEBUG root [2019-09-03 21:36:07,593] - Components::process(): Request for the process of identity...
  INFO root [2019-09-03 21:36:14,918] - Components::findComponents: find logger(1)...
  INFO root [2019-09-03 21:36:14,978] - Components::findComponents: found logger, addr:192.168.56.1:52850
  INFO root [2019-09-03 21:36:14,978] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-03 21:36:14,978] - Components::addComponent[logger], uid=2082, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-03 21:36:14,978] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-03 21:36:15,098] - Components::findComponents: found dbmgr, addr:192.168.56.1:52855
  INFO root [2019-09-03 21:36:15,098] - Components::addComponent: reset orderLog, uid=2082!
  INFO root [2019-09-03 21:36:15,098] - Components::addComponent[dbmgr], uid=2082, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-03 21:36:15,098] - Components::findComponents: found dbmgr, addr:192.168.56.1:52855
  WARN root [2019-09-03 21:36:16,118] - Forwarding logs to logger[192.168.56.1:52850/0/0/0]...
 ERROR root [2019-09-03 21:50:26,960] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=272452679228, lastReceivedTime=272404611166, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-03 21:50:26,975] - The following logs sent to logger failed:
  WARN root [2019-09-03 21:50:26,975] - ==> [2019-09-03 21:50:26 967] TCPPacketReceiver::processPendingEvents(192.168.56.1:52850): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-03 21:50:26,975] - ==> [2019-09-03 21:50:26 973] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=272452679228, lastReceivedTime=272404611166, inactivityExceptionPeriod=134887500)
  WARN root [2019-09-03 21:50:27,069] - TCPPacketReceiver::processPendingEvents(192.168.56.1:52855): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-03 21:50:27,069] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=272452922627, lastReceivedTime=272404835179, inactivityExceptionPeriod=134887500)
  INFO root [2019-09-03 21:50:27,084] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-03 21:50:27,084] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-03 21:50:27,084] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-03 21:50:27,084] - ThreadPool::destroy(): starting size 2.
