  INFO root [2019-05-08 10:03:48,968] - 
  INFO root [2019-05-08 10:03:48,968] - -----------------------------------------------------------------------------------------


  INFO root [2019-05-08 10:03:48,968] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-05-08 10:03:48,968] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/server_assets/;D:/kbengine/server_assets/scripts/;D:/kbengine/server_assets/res/
  INFO root [2019-05-08 10:03:48,974] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-05-08 10:03:48,984] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 192.168.56.1 ( 192.168.56.1:64904 )
  INFO root [2019-05-08 10:03:48,998] - NetworkInterface::initialize(INTERNAL-TCP): address 192.168.56.1:64904, SOMAXCONN=5.
  INFO root [2019-05-08 10:03:48,998] - server-configs:
  INFO root [2019-05-08 10:03:48,998] - 	internalTcpAddr : 192.168.56.1:64904
  INFO root [2019-05-08 10:03:48,998] - 	componentID : 6000
  WARN root [2019-05-08 10:03:48,998] - invalid UID(0) <= 0, please check UID for environment! automatically set to 3960.
  INFO root [2019-05-08 10:03:49,138] - Components::findLogger: found logger, addr:192.168.56.1:64886
  INFO root [2019-05-08 10:03:49,138] - Components::addComponent: reset orderLog, uid=3960!
  INFO root [2019-05-08 10:03:49,138] - Components::addComponent[logger], uid=3960, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-05-08 10:03:49,144] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 3960. PID: 12488 ----
  INFO root [2019-05-08 10:03:49,144] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-05-08 10:03:49,144] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-05-08 10:03:49,144] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-05-08 10:03:49,527] - ---- cellappmgr is running ----
 DEBUG root [2019-05-08 10:03:49,527] - Components::process(): Request for the process of identity...
  WARN root [2019-05-08 10:03:55,794] - Forwarding logs to logger[192.168.56.1:64886/0/0/0]...
 ERROR root [2019-05-08 10:05:17,628] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317863974086, lastReceivedTime=317852846214, inactivityExceptionPeriod=134887676)
  INFO root [2019-05-08 10:05:17,628] - The following logs sent to logger failed:
  WARN root [2019-05-08 10:05:17,628] - ==> [2019-05-08 10:05:17 630] TCPPacketReceiver::processPendingEvents(192.168.56.1:64886): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-05-08 10:05:17,628] - ==> [2019-05-08 10:05:17 631] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317863974086, lastReceivedTime=317852846214, inactivityExceptionPeriod=134887676)
  WARN root [2019-05-08 10:05:17,728] - TCPPacketReceiver::processPendingEvents(192.168.56.1:64889): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-05-08 10:05:17,734] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=317864209617, lastReceivedTime=317823055719, inactivityExceptionPeriod=134887676)
  INFO root [2019-05-08 10:05:17,744] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-05-08 10:05:17,748] - Shutdowner::onShutdown: shutting down
  INFO root [2019-05-08 10:05:17,748] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-05-08 10:05:17,748] - ThreadPool::destroy(): starting size 2.
