  INFO root [2019-09-21 09:28:05,438] - 
  INFO root [2019-09-21 09:28:05,439] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:28:05,440] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:28:05,440] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:28:05,441] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:28:05,450] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51538 )
  INFO root [2019-09-21 09:28:05,450] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51538, SOMAXCONN=5.
  INFO root [2019-09-21 09:28:05,451] - server-configs:
  INFO root [2019-09-21 09:28:05,451] - 	internalTcpAddr : 10.15.26.195:51538
  INFO root [2019-09-21 09:28:05,451] - 	componentID : 6000
  WARN root [2019-09-21 09:28:05,451] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:28:06,959] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 5336 ----
  INFO root [2019-09-21 09:28:06,959] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:28:06,960] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:28:06,960] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:28:07,352] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:28:07,355] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:28:14,502] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-21 09:28:16,004] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:16,005] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:28:16,005] - Components::findComponents: not found logger!
  INFO root [2019-09-21 09:28:17,022] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-09-21 09:28:18,523] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:18,524] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:19,542] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-09-21 09:28:19,543] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:19,603] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:19,923] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:19,923] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:20,744] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:20,745] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:21,284] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:21,285] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:21,698] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:21,699] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:22,437] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:22,439] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:23,319] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:23,322] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:23,803] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:23,805] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:24,227] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:24,228] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:24,958] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:24,959] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:25,844] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:25,846] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:26,323] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:26,325] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:26,798] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:26,800] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:27,477] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:27,479] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:28,418] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:28,419] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:28,841] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:28,843] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:29,327] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:29,329] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:29,997] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:29,998] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:30,944] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:30,946] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:31,364] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:31,366] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:31,899] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:31,899] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:32,518] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:32,520] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:33,518] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:33,519] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:33,883] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:33,885] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:34,427] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:34,427] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:35,039] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:35,039] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:36,044] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:36,044] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:36,404] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:36,405] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:36,998] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:37,000] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:37,558] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:37,560] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:38,618] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:38,619] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:38,923] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:38,924] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:39,526] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:39,527] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:40,077] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:40,081] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:41,143] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:41,145] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:41,441] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:41,443] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:42,099] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:42,100] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:42,597] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:42,599] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:43,718] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:43,719] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:43,963] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:43,964] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:44,626] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:44,627] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:45,117] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:45,118] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:46,244] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:46,245] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:46,483] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:46,484] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:47,198] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:47,200] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:47,623] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:47,625] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:48,818] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:48,820] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:49,003] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:49,005] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:49,726] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:49,727] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:50,137] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:50,137] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:51,344] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:51,345] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:51,523] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:51,524] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:52,298] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:52,300] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:52,657] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:52,658] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:53,918] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:53,919] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:54,041] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:54,043] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:54,827] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:54,828] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:55,177] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:55,178] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:56,444] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:56,445] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:56,563] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:56,566] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:57,398] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:57,400] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:57,701] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:57,702] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:58,963] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:58,965] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:59,086] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:59,088] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:28:59,929] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:28:59,931] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:00,218] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:00,220] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:01,520] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:01,523] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:01,605] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:01,607] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:02,499] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:02,502] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:02,739] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:02,741] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:04,045] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:04,047] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:04,124] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:04,126] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:05,029] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:05,030] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:05,259] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:05,261] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:06,620] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:06,622] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:06,645] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:06,647] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:07,601] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:07,602] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:07,779] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:07,781] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:09,146] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:09,148] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:09,165] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:09,166] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:10,128] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:10,130] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:10,299] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:10,300] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:11,685] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:11,687] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:11,720] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:11,722] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:12,700] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:12,701] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:12,819] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:12,820] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:14,209] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:14,212] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:14,244] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:14,246] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:15,229] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:15,231] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:15,338] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:15,341] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:16,725] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:16,727] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:16,819] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:16,821] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:17,800] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:17,802] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:17,859] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:17,860] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:19,243] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:19,245] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:19,346] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:19,348] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:20,329] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:20,329] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:20,379] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:20,381] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:21,764] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:21,768] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:21,919] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:21,922] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:22,898] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:22,900] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:24,285] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:24,288] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:24,301] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:24,302] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:24,445] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:24,447] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:25,418] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:25,420] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:26,804] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:26,806] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:26,828] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:26,830] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:26,964] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:26,965] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:27,938] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:27,941] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:29,325] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:29,327] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:29,399] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:29,401] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:29,521] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:29,522] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:30,459] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:30,461] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:31,843] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:31,846] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:31,929] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:31,930] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
 ERROR root [2019-09-21 09:29:32,045] - Attempted to get in MemoryStream (pos:41, size:0, opsize:2)!
 ERROR root [2019-09-21 09:29:32,047] - BundleBroadcast::receive: data wrong. size=41, from 10.15.26.195.
  INFO root [2019-09-21 09:29:34,281] - 
  INFO root [2019-09-21 09:29:34,282] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:29:34,283] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:29:34,283] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:29:34,283] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:29:34,294] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51566 )
  INFO root [2019-09-21 09:29:34,295] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51566, SOMAXCONN=5.
  INFO root [2019-09-21 09:29:34,295] - server-configs:
  INFO root [2019-09-21 09:29:34,295] - 	internalTcpAddr : 10.15.26.195:51566
  INFO root [2019-09-21 09:29:34,295] - 	componentID : 6000
  WARN root [2019-09-21 09:29:34,295] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:29:35,800] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 7004 ----
  INFO root [2019-09-21 09:29:35,801] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:29:35,801] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:29:35,802] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:29:36,189] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:29:36,190] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:29:43,322] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:29:43,366] - Components::findComponents: found logger, addr:10.15.26.195:51565
  INFO root [2019-09-21 09:29:43,366] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:29:43,366] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:29:43,367] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:29:43,470] - Components::findComponents: found dbmgr, addr:10.15.26.195:51562
  INFO root [2019-09-21 09:29:43,470] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:29:43,470] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:29:43,470] - Components::findComponents: found dbmgr, addr:10.15.26.195:51562
  WARN root [2019-09-21 09:29:44,470] - Forwarding logs to logger[10.15.26.195:51565/0/0/0]...
  INFO root [2019-09-21 09:38:37,605] - EventDispatcher()::~EventDispatcher: Num timers = 2
  INFO root [2019-09-21 09:40:36,924] - 
  INFO root [2019-09-21 09:40:36,924] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:40:36,925] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:40:36,926] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:40:36,926] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:40:36,936] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51757 )
  INFO root [2019-09-21 09:40:36,936] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51757, SOMAXCONN=5.
  INFO root [2019-09-21 09:40:36,937] - server-configs:
  INFO root [2019-09-21 09:40:36,937] - 	internalTcpAddr : 10.15.26.195:51757
  INFO root [2019-09-21 09:40:36,937] - 	componentID : 6000
  WARN root [2019-09-21 09:40:36,937] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:40:38,444] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 14164 ----
  INFO root [2019-09-21 09:40:38,445] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:40:38,446] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:40:38,446] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:40:38,869] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:40:38,870] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:40:46,027] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:40:46,096] - Components::findComponents: found logger, addr:10.15.26.195:51754
  INFO root [2019-09-21 09:40:46,097] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:40:46,097] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:40:46,098] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:40:46,199] - Components::findComponents: found dbmgr, addr:10.15.26.195:51759
  INFO root [2019-09-21 09:40:46,199] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:40:46,200] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:40:46,200] - Components::findComponents: found dbmgr, addr:10.15.26.195:51759
  WARN root [2019-09-21 09:40:47,201] - Forwarding logs to logger[10.15.26.195:51754/0/0/0]...
 ERROR root [2019-09-21 09:45:33,915] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467633615221, lastReceivedTime=467362713705, inactivityExceptionPeriod=599500512)
  INFO root [2019-09-21 09:45:33,919] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:45:33,919] - ==> [2019-09-21 09:45:33 913] TCPPacketReceiver::processPendingEvents(10.15.26.195:51754): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:45:33,919] - ==> [2019-09-21 09:45:33 916] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467633615221, lastReceivedTime=467362713705, inactivityExceptionPeriod=599500512)
  WARN root [2019-09-21 09:45:34,013] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:45:34,015] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467634613137, lastReceivedTime=467364186617, inactivityExceptionPeriod=599500512)
  INFO root [2019-09-21 09:45:34,047] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 09:45:34,049] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:45:34,049] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 09:45:34,049] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 09:48:09,570] - 
  INFO root [2019-09-21 09:48:09,573] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:48:09,574] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:48:09,575] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:48:09,575] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:48:09,596] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51843 )
  INFO root [2019-09-21 09:48:09,596] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51843, SOMAXCONN=5.
  INFO root [2019-09-21 09:48:09,596] - server-configs:
  INFO root [2019-09-21 09:48:09,596] - 	internalTcpAddr : 10.15.26.195:51843
  INFO root [2019-09-21 09:48:09,596] - 	componentID : 6000
  WARN root [2019-09-21 09:48:09,599] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:48:11,109] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 14228 ----
  INFO root [2019-09-21 09:48:11,110] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:48:11,111] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:48:11,111] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:48:11,531] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:48:11,535] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:48:17,695] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51864): Throwing REASON_GENERAL_NETWORK - WSAECONNABORTED
  INFO root [2019-09-21 09:48:18,712] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:48:18,740] - Components::findComponents: found logger, addr:10.15.26.195:51845
  INFO root [2019-09-21 09:48:18,741] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:48:18,741] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:48:18,742] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:48:18,746] - Components::findComponents: found dbmgr, addr:10.15.26.195:51846
  INFO root [2019-09-21 09:48:18,746] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:48:18,746] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:48:18,848] - Components::findComponents: found dbmgr, addr:10.15.26.195:51846
  WARN root [2019-09-21 09:48:19,849] - Forwarding logs to logger[10.15.26.195:51845/0/0/0]...
 ERROR root [2019-09-21 09:52:20,733] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471701793562, lastReceivedTime=471590627547, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:52:20,740] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:52:20,740] - ==> [2019-09-21 09:52:20 731] TCPPacketReceiver::processPendingEvents(10.15.26.195:51845): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:52:20,741] - ==> [2019-09-21 09:52:20 733] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471701793562, lastReceivedTime=471590627547, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 09:52:20,832] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51846): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:52:20,833] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471702793203, lastReceivedTime=471590610106, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:52:20,849] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 09:52:20,850] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:52:20,850] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 09:52:20,850] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 09:54:15,557] - 
  INFO root [2019-09-21 09:54:15,558] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:54:15,559] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:54:15,559] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:54:15,559] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:54:15,603] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51950 )
  INFO root [2019-09-21 09:54:15,603] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51950, SOMAXCONN=5.
  INFO root [2019-09-21 09:54:15,603] - server-configs:
  INFO root [2019-09-21 09:54:15,603] - 	internalTcpAddr : 10.15.26.195:51950
  INFO root [2019-09-21 09:54:15,603] - 	componentID : 6000
  WARN root [2019-09-21 09:54:15,604] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-21 09:54:15,945] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20493, errorno=10048
  INFO root [2019-09-21 09:54:15,948] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 13904 ----
  INFO root [2019-09-21 09:54:15,949] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:54:15,949] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:54:15,949] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:54:16,366] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:54:16,367] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:54:23,511] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:54:23,556] - Components::findComponents: found logger, addr:10.15.26.195:51946
  INFO root [2019-09-21 09:54:23,556] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:54:23,556] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:54:23,559] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:54:23,662] - Components::findComponents: found dbmgr, addr:10.15.26.195:51947
  INFO root [2019-09-21 09:54:23,663] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:54:23,664] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:54:23,670] - Components::findComponents: found dbmgr, addr:10.15.26.195:51947
  WARN root [2019-09-21 09:54:24,671] - Forwarding logs to logger[10.15.26.195:51946/0/0/0]...
 ERROR root [2019-09-21 09:56:00,286] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473897330823, lastReceivedTime=473749879049, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 09:56:00,296] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:56:00,297] - ==> [2019-09-21 09:56:00 285] TCPPacketReceiver::processPendingEvents(10.15.26.195:51946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:56:00,297] - ==> [2019-09-21 09:56:00 287] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473897330823, lastReceivedTime=473749879049, inactivityExceptionPeriod=599499745)
  WARN root [2019-09-21 09:56:00,377] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51947): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:56:00,378] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473898250980, lastReceivedTime=473750517077, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 09:56:00,386] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 09:56:00,388] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:56:00,389] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 09:56:00,389] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 09:56:02,119] - 
  INFO root [2019-09-21 09:56:02,120] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:56:02,121] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:56:02,121] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:56:02,121] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:56:02,135] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52017 )
  INFO root [2019-09-21 09:56:02,136] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52017, SOMAXCONN=5.
  INFO root [2019-09-21 09:56:02,136] - server-configs:
  INFO root [2019-09-21 09:56:02,136] - 	internalTcpAddr : 10.15.26.195:52017
  INFO root [2019-09-21 09:56:02,136] - 	componentID : 6000
  WARN root [2019-09-21 09:56:02,139] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-21 09:56:02,478] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20931, errorno=10048
  INFO root [2019-09-21 09:56:02,482] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 5892 ----
  INFO root [2019-09-21 09:56:02,483] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:56:02,483] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:56:02,483] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:56:02,941] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:56:02,951] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:56:10,123] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:56:10,197] - Components::findComponents: found logger, addr:10.15.26.195:52015
  INFO root [2019-09-21 09:56:10,198] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:56:10,198] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:56:10,199] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:56:10,302] - Components::findComponents: found dbmgr, addr:10.15.26.195:52013
  INFO root [2019-09-21 09:56:10,302] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:56:10,302] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:56:10,303] - Components::findComponents: found dbmgr, addr:10.15.26.195:52013
  WARN root [2019-09-21 09:56:11,304] - Forwarding logs to logger[10.15.26.195:52015/0/0/0]...
 ERROR root [2019-09-21 09:57:59,388] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475088346499, lastReceivedTime=474815474567, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:57:59,393] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:57:59,393] - ==> [2019-09-21 09:57:59 386] TCPPacketReceiver::processPendingEvents(10.15.26.195:52015): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:57:59,394] - ==> [2019-09-21 09:57:59 389] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475088346499, lastReceivedTime=474815474567, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 09:57:59,479] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52013): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:57:59,481] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475089274249, lastReceivedTime=474814635193, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:57:59,486] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 09:57:59,488] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:57:59,489] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 09:57:59,489] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 09:58:01,195] - 
  INFO root [2019-09-21 09:58:01,198] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:58:01,199] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:58:01,199] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:58:01,199] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:58:01,231] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52076 )
  INFO root [2019-09-21 09:58:01,231] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52076, SOMAXCONN=5.
  INFO root [2019-09-21 09:58:01,231] - server-configs:
  INFO root [2019-09-21 09:58:01,231] - 	internalTcpAddr : 10.15.26.195:52076
  INFO root [2019-09-21 09:58:01,231] - 	componentID : 6000
  WARN root [2019-09-21 09:58:01,232] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-21 09:58:01,628] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20626, errorno=10048
  INFO root [2019-09-21 09:58:01,632] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 13340 ----
  INFO root [2019-09-21 09:58:01,632] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:58:01,632] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:58:01,633] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:58:02,038] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 09:58:02,038] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:58:08,166] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52091): Throwing REASON_GENERAL_NETWORK - WSAECONNABORTED
  INFO root [2019-09-21 09:58:09,174] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:58:09,194] - Components::findComponents: found logger, addr:10.15.26.195:52074
  INFO root [2019-09-21 09:58:09,194] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:58:09,194] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:58:09,195] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:58:09,299] - Components::findComponents: found dbmgr, addr:10.15.26.195:52070
  INFO root [2019-09-21 09:58:09,299] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:58:09,299] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:58:09,299] - Components::findComponents: found dbmgr, addr:10.15.26.195:52070
  WARN root [2019-09-21 09:58:10,299] - Forwarding logs to logger[10.15.26.195:52074/0/0/0]...
 ERROR root [2019-09-21 09:59:51,503] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476209492699, lastReceivedTime=476006454220, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 09:59:51,506] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:59:51,506] - ==> [2019-09-21 09:59:51 500] TCPPacketReceiver::processPendingEvents(10.15.26.195:52074): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:59:51,506] - ==> [2019-09-21 09:59:51 503] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476209492699, lastReceivedTime=476006454220, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 09:59:51,601] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52070): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:59:51,603] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476210501821, lastReceivedTime=476006154473, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 09:59:51,614] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 09:59:51,629] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:59:51,629] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 09:59:51,629] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 10:01:45,546] - 
  INFO root [2019-09-21 10:01:45,546] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:01:45,547] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:01:45,548] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:01:45,548] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:01:45,559] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52156 )
  INFO root [2019-09-21 10:01:45,559] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52156, SOMAXCONN=5.
  INFO root [2019-09-21 10:01:45,560] - server-configs:
  INFO root [2019-09-21 10:01:45,560] - 	internalTcpAddr : 10.15.26.195:52156
  INFO root [2019-09-21 10:01:45,560] - 	componentID : 6000
  WARN root [2019-09-21 10:01:45,562] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:01:47,068] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 9896 ----
  INFO root [2019-09-21 10:01:47,069] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:01:47,069] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:01:47,070] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:01:47,467] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 10:01:47,468] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 10:01:54,611] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 10:01:54,636] - Components::findComponents: found logger, addr:10.15.26.195:52158
  INFO root [2019-09-21 10:01:54,636] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:01:54,636] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:01:54,638] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 10:01:54,742] - Components::findComponents: found dbmgr, addr:10.15.26.195:52159
  INFO root [2019-09-21 10:01:54,743] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:01:54,743] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:01:54,749] - Components::findComponents: found dbmgr, addr:10.15.26.195:52159
  WARN root [2019-09-21 10:01:55,750] - Forwarding logs to logger[10.15.26.195:52158/0/0/0]...
 ERROR root [2019-09-21 10:05:33,652] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479630992538, lastReceivedTime=479450319876, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 10:05:33,658] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:05:33,659] - ==> [2019-09-21 10:05:33 650] TCPPacketReceiver::processPendingEvents(10.15.26.195:52158): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:05:33,659] - ==> [2019-09-21 10:05:33 653] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479630992538, lastReceivedTime=479450319876, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 10:05:33,797] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52159): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:05:33,803] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479632491668, lastReceivedTime=479450399351, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 10:05:33,819] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 10:05:33,833] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:05:33,833] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 10:05:33,833] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 10:05:34,133] - ThreadPool::destroy(): waiting for thread(2)[0x7cd0b8,0x7cd1f0,], try=1
  INFO root [2019-09-21 10:06:38,578] - 
  INFO root [2019-09-21 10:06:38,581] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:06:38,582] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:06:38,582] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:06:38,583] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:06:38,598] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52225 )
  INFO root [2019-09-21 10:06:38,598] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52225, SOMAXCONN=5.
  INFO root [2019-09-21 10:06:38,598] - server-configs:
  INFO root [2019-09-21 10:06:38,598] - 	internalTcpAddr : 10.15.26.195:52225
  INFO root [2019-09-21 10:06:38,598] - 	componentID : 6000
  WARN root [2019-09-21 10:06:38,599] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:06:40,105] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 13396 ----
  INFO root [2019-09-21 10:06:40,106] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:06:40,107] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:06:40,107] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:06:40,522] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 10:06:40,522] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 10:06:47,687] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 10:06:47,695] - Components::findComponents: found logger, addr:10.15.26.195:52222
  INFO root [2019-09-21 10:06:47,695] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:06:47,695] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:06:47,697] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 10:06:47,801] - Components::findComponents: found dbmgr, addr:10.15.26.195:52223
  INFO root [2019-09-21 10:06:47,801] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:06:47,801] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:06:47,801] - Components::findComponents: found dbmgr, addr:10.15.26.195:52223
  WARN root [2019-09-21 10:06:48,801] - Forwarding logs to logger[10.15.26.195:52222/0/0/0]...
 ERROR root [2019-09-21 10:27:24,720] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492741670091, lastReceivedTime=492579516059, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 10:27:24,726] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:27:24,726] - ==> [2019-09-21 10:27:24 719] TCPPacketReceiver::processPendingEvents(10.15.26.195:52222): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:27:24,727] - ==> [2019-09-21 10:27:24 721] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492741670091, lastReceivedTime=492579516059, inactivityExceptionPeriod=599500064)
  WARN root [2019-09-21 10:27:24,806] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52223): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:27:24,808] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492742542541, lastReceivedTime=492579858457, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 10:27:24,812] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 10:27:24,813] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:27:24,813] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 10:27:24,814] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 10:52:47,009] - 
  INFO root [2019-09-21 10:52:47,016] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:52:47,021] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:52:47,021] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:52:47,021] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:52:47,052] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52801 )
  INFO root [2019-09-21 10:52:47,053] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52801, SOMAXCONN=5.
  INFO root [2019-09-21 10:52:47,053] - server-configs:
  INFO root [2019-09-21 10:52:47,053] - 	internalTcpAddr : 10.15.26.195:52801
  INFO root [2019-09-21 10:52:47,053] - 	componentID : 6000
  WARN root [2019-09-21 10:52:47,053] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:52:48,559] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 11576 ----
  INFO root [2019-09-21 10:52:48,560] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:52:48,576] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:52:48,577] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:52:48,991] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 10:52:48,992] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 10:52:56,158] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 10:52:56,225] - Components::findComponents: found logger, addr:10.15.26.195:52800
  INFO root [2019-09-21 10:52:56,226] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:52:56,226] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:52:56,227] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 10:52:56,331] - Components::findComponents: found dbmgr, addr:10.15.26.195:52804
  INFO root [2019-09-21 10:52:56,331] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:52:56,331] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:52:56,331] - Components::findComponents: found dbmgr, addr:10.15.26.195:52804
  WARN root [2019-09-21 10:52:57,332] - Forwarding logs to logger[10.15.26.195:52800/0/0/0]...
 ERROR root [2019-09-21 10:54:19,520] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508889671918, lastReceivedTime=508864547721, inactivityExceptionPeriod=599496995)
  INFO root [2019-09-21 10:54:19,522] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:54:19,522] - ==> [2019-09-21 10:54:19 515] TCPPacketReceiver::processPendingEvents(10.15.26.195:52800): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:54:19,523] - ==> [2019-09-21 10:54:19 521] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508889671918, lastReceivedTime=508864547721, inactivityExceptionPeriod=599496995)
  WARN root [2019-09-21 10:54:19,621] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52804): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:54:19,622] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508890688405, lastReceivedTime=508865139211, inactivityExceptionPeriod=599496995)
  INFO root [2019-09-21 10:54:19,640] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 10:54:19,644] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:54:19,644] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 10:54:19,645] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 10:54:21,413] - 
  INFO root [2019-09-21 10:54:21,414] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:54:21,415] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:54:21,415] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:54:21,415] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:54:21,424] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52881 )
  INFO root [2019-09-21 10:54:21,424] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52881, SOMAXCONN=5.
  INFO root [2019-09-21 10:54:21,424] - server-configs:
  INFO root [2019-09-21 10:54:21,425] - 	internalTcpAddr : 10.15.26.195:52881
  INFO root [2019-09-21 10:54:21,425] - 	componentID : 6000
  WARN root [2019-09-21 10:54:21,425] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:54:22,931] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 12948 ----
  INFO root [2019-09-21 10:54:22,935] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:54:22,936] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:54:22,937] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:54:23,397] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 10:54:23,398] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 10:54:30,578] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 10:54:30,604] - Components::findComponents: found logger, addr:10.15.26.195:52880
  INFO root [2019-09-21 10:54:30,605] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:54:30,605] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:54:30,606] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 10:54:30,709] - Components::findComponents: found dbmgr, addr:10.15.26.195:52882
  INFO root [2019-09-21 10:54:30,709] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:54:30,709] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:54:30,710] - Components::findComponents: found dbmgr, addr:10.15.26.195:52882
  WARN root [2019-09-21 10:54:31,711] - Forwarding logs to logger[10.15.26.195:52880/0/0/0]...
 ERROR root [2019-09-21 11:09:42,240] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518116864326, lastReceivedTime=517908115079, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 11:09:42,243] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:09:42,244] - ==> [2019-09-21 11:09:42 239] TCPPacketReceiver::processPendingEvents(10.15.26.195:52880): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:09:42,244] - ==> [2019-09-21 11:09:42 241] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518116864326, lastReceivedTime=517908115079, inactivityExceptionPeriod=599500192)
  WARN root [2019-09-21 11:09:42,342] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52882): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:09:42,347] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518117944708, lastReceivedTime=517909704675, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 11:09:42,379] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 11:09:42,381] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:09:42,381] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 11:09:42,381] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 11:10:44,828] - 
  INFO root [2019-09-21 11:10:44,829] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:10:44,830] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:10:44,831] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:10:44,831] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:10:44,848] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53006 )
  INFO root [2019-09-21 11:10:44,848] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53006, SOMAXCONN=5.
  INFO root [2019-09-21 11:10:44,848] - server-configs:
  INFO root [2019-09-21 11:10:44,848] - 	internalTcpAddr : 10.15.26.195:53006
  INFO root [2019-09-21 11:10:44,848] - 	componentID : 6000
  WARN root [2019-09-21 11:10:44,853] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:10:46,359] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 14800 ----
  INFO root [2019-09-21 11:10:46,359] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:10:46,359] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:10:46,360] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:10:46,754] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 11:10:46,754] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 11:10:53,901] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 11:10:53,957] - Components::findComponents: found logger, addr:10.15.26.195:53004
  INFO root [2019-09-21 11:10:53,957] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:10:53,957] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:10:53,958] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 11:10:54,065] - Components::findComponents: found dbmgr, addr:10.15.26.195:53003
  INFO root [2019-09-21 11:10:54,066] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:10:54,066] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:10:54,066] - Components::findComponents: found dbmgr, addr:10.15.26.195:53003
  WARN root [2019-09-21 11:10:55,069] - Forwarding logs to logger[10.15.26.195:53004/0/0/0]...
 ERROR root [2019-09-21 11:13:18,264] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520277108601, lastReceivedTime=520242451217, inactivityExceptionPeriod=599500320)
  INFO root [2019-09-21 11:13:18,271] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:13:18,271] - ==> [2019-09-21 11:13:18 261] TCPPacketReceiver::processPendingEvents(10.15.26.195:53004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:13:18,272] - ==> [2019-09-21 11:13:18 265] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520277108601, lastReceivedTime=520242451217, inactivityExceptionPeriod=599500320)
  WARN root [2019-09-21 11:13:18,361] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53003): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:13:18,363] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520278098657, lastReceivedTime=520242411615, inactivityExceptionPeriod=599500320)
  INFO root [2019-09-21 11:13:18,396] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 11:13:18,397] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:13:18,397] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 11:13:18,398] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 11:13:20,080] - 
  INFO root [2019-09-21 11:13:20,083] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:13:20,084] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:13:20,084] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:13:20,084] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:13:20,118] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53065 )
  INFO root [2019-09-21 11:13:20,119] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53065, SOMAXCONN=5.
  INFO root [2019-09-21 11:13:20,119] - server-configs:
  INFO root [2019-09-21 11:13:20,119] - 	internalTcpAddr : 10.15.26.195:53065
  INFO root [2019-09-21 11:13:20,119] - 	componentID : 6000
  WARN root [2019-09-21 11:13:20,122] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:13:21,643] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 9556 ----
  INFO root [2019-09-21 11:13:21,644] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:13:21,644] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:13:21,644] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:13:22,074] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 11:13:22,075] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 11:13:29,205] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 11:13:29,280] - Components::findComponents: found logger, addr:10.15.26.195:53069
  INFO root [2019-09-21 11:13:29,280] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:13:29,280] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:13:29,281] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 11:13:29,384] - Components::findComponents: found dbmgr, addr:10.15.26.195:53063
  INFO root [2019-09-21 11:13:29,384] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:13:29,384] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:13:29,385] - Components::findComponents: found dbmgr, addr:10.15.26.195:53063
  WARN root [2019-09-21 11:13:30,385] - Forwarding logs to logger[10.15.26.195:53069/0/0/0]...
 ERROR root [2019-09-21 11:16:26,651] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522160979655, lastReceivedTime=522096294206, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 11:16:26,659] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:16:26,659] - ==> [2019-09-21 11:16:26 648] TCPPacketReceiver::processPendingEvents(10.15.26.195:53069): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:16:26,659] - ==> [2019-09-21 11:16:26 652] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522160979655, lastReceivedTime=522096294206, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 11:16:26,750] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:16:26,750] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522161967831, lastReceivedTime=522094876638, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 11:16:26,757] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 11:16:26,758] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:16:26,759] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 11:16:26,759] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 11:16:31,187] - 
  INFO root [2019-09-21 11:16:31,187] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:16:31,189] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:16:31,190] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:16:31,190] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:16:31,203] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53119 )
  INFO root [2019-09-21 11:16:31,203] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53119, SOMAXCONN=5.
  INFO root [2019-09-21 11:16:31,203] - server-configs:
  INFO root [2019-09-21 11:16:31,203] - 	internalTcpAddr : 10.15.26.195:53119
  INFO root [2019-09-21 11:16:31,204] - 	componentID : 6000
  WARN root [2019-09-21 11:16:31,204] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:16:32,709] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 6196 ----
  INFO root [2019-09-21 11:16:32,709] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:16:32,710] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:16:32,710] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:16:33,200] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 11:16:33,201] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 11:16:40,371] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 11:16:40,427] - Components::findComponents: found logger, addr:10.15.26.195:53118
  INFO root [2019-09-21 11:16:40,428] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:16:40,428] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:16:40,429] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 11:16:40,533] - Components::findComponents: found dbmgr, addr:10.15.26.195:53122
  INFO root [2019-09-21 11:16:40,534] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:16:40,534] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:16:40,540] - Components::findComponents: found dbmgr, addr:10.15.26.195:53122
  WARN root [2019-09-21 11:16:41,540] - Forwarding logs to logger[10.15.26.195:53118/0/0/0]...
 ERROR root [2019-09-21 11:17:01,826] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522512722541, lastReceivedTime=522506265876, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 11:17:01,831] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:17:01,831] - ==> [2019-09-21 11:17:01 824] TCPPacketReceiver::processPendingEvents(10.15.26.195:53118): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:17:01,831] - ==> [2019-09-21 11:17:01 826] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522512722541, lastReceivedTime=522506265876, inactivityExceptionPeriod=599500192)
  WARN root [2019-09-21 11:17:01,913] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53122): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:17:01,917] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522513638813, lastReceivedTime=522508012784, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 11:17:01,925] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 11:17:01,926] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:17:01,926] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 11:17:01,926] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 11:17:03,532] - 
  INFO root [2019-09-21 11:17:03,533] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:17:03,534] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:17:03,534] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:17:03,535] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:17:03,543] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53154 )
  INFO root [2019-09-21 11:17:03,544] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53154, SOMAXCONN=5.
  INFO root [2019-09-21 11:17:03,544] - server-configs:
  INFO root [2019-09-21 11:17:03,544] - 	internalTcpAddr : 10.15.26.195:53154
  INFO root [2019-09-21 11:17:03,544] - 	componentID : 6000
  WARN root [2019-09-21 11:17:03,545] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:17:05,051] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 14700 ----
  INFO root [2019-09-21 11:17:05,051] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:17:05,052] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:17:05,052] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:17:05,487] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 11:17:05,508] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 11:17:12,693] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 11:17:12,703] - Components::findComponents: found logger, addr:10.15.26.195:53153
  INFO root [2019-09-21 11:17:12,704] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:17:12,704] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:17:12,705] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 11:17:12,808] - Components::findComponents: found dbmgr, addr:10.15.26.195:53158
  INFO root [2019-09-21 11:17:12,808] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:17:12,808] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:17:12,808] - Components::findComponents: found dbmgr, addr:10.15.26.195:53158
  WARN root [2019-09-21 11:17:13,809] - Forwarding logs to logger[10.15.26.195:53153/0/0/0]...
 ERROR root [2019-09-21 11:20:54,430] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524838772201, lastReceivedTime=524629253427, inactivityExceptionPeriod=599498594)
  INFO root [2019-09-21 11:20:54,437] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:20:54,437] - ==> [2019-09-21 11:20:54 428] TCPPacketReceiver::processPendingEvents(10.15.26.195:53153): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:20:54,438] - ==> [2019-09-21 11:20:54 431] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524838772201, lastReceivedTime=524629253427, inactivityExceptionPeriod=599498594)
  WARN root [2019-09-21 11:20:54,528] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53158): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:20:54,532] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524839782170, lastReceivedTime=524631084417, inactivityExceptionPeriod=599498594)
  INFO root [2019-09-21 11:20:54,560] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 11:20:54,560] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:20:54,560] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 11:20:54,561] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 14:44:23,566] - 
  INFO root [2019-09-21 14:44:23,612] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 14:44:23,613] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 14:44:23,613] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 14:44:23,614] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 14:44:23,627] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54429 )
  INFO root [2019-09-21 14:44:23,628] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54429, SOMAXCONN=5.
  INFO root [2019-09-21 14:44:23,628] - server-configs:
  INFO root [2019-09-21 14:44:23,628] - 	internalTcpAddr : 10.15.26.195:54429
  INFO root [2019-09-21 14:44:23,629] - 	componentID : 6000
  WARN root [2019-09-21 14:44:23,629] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 14:44:25,134] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 11756 ----
  INFO root [2019-09-21 14:44:25,137] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 14:44:25,137] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 14:44:25,138] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 14:44:25,620] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 14:44:25,657] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 14:44:32,771] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 14:44:32,839] - Components::findComponents: found logger, addr:10.15.26.195:54427
  INFO root [2019-09-21 14:44:32,839] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 14:44:32,840] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 14:44:32,841] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 14:44:32,945] - Components::findComponents: found dbmgr, addr:10.15.26.195:54424
  INFO root [2019-09-21 14:44:32,945] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 14:44:32,945] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 14:44:32,946] - Components::findComponents: found dbmgr, addr:10.15.26.195:54424
  WARN root [2019-09-21 14:44:33,946] - Forwarding logs to logger[10.15.26.195:54427/0/0/0]...
 ERROR root [2019-09-21 14:54:59,595] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653385842505, lastReceivedTime=653324852116, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 14:54:59,604] - The following logs sent to logger failed:
  WARN root [2019-09-21 14:54:59,604] - ==> [2019-09-21 14:54:59 594] TCPPacketReceiver::processPendingEvents(10.15.26.195:54427): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 14:54:59,605] - ==> [2019-09-21 14:54:59 596] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653385842505, lastReceivedTime=653324852116, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 14:54:59,708] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54424): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 14:54:59,709] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653386986170, lastReceivedTime=653322499302, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 14:54:59,729] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 14:54:59,731] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 14:54:59,731] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 14:54:59,731] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 15:02:27,031] - 
  INFO root [2019-09-21 15:02:27,034] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:02:27,035] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:02:27,035] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:02:27,035] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:02:27,044] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54611 )
  INFO root [2019-09-21 15:02:27,044] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54611, SOMAXCONN=5.
  INFO root [2019-09-21 15:02:27,044] - server-configs:
  INFO root [2019-09-21 15:02:27,045] - 	internalTcpAddr : 10.15.26.195:54611
  INFO root [2019-09-21 15:02:27,045] - 	componentID : 6000
  WARN root [2019-09-21 15:02:27,045] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:02:28,552] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 1444 ----
  INFO root [2019-09-21 15:02:28,552] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:02:28,553] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:02:28,553] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:02:28,970] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 15:02:28,970] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 15:02:36,156] - Components::findComponents: find logger(1)...
  WARN root [2019-09-21 15:02:36,495] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20303, errorno=10048
  INFO root [2019-09-21 15:02:37,516] - Components::findComponents: find logger(2)...
  INFO root [2019-09-21 15:02:37,591] - Components::findComponents: found logger, addr:10.15.26.195:54614
  INFO root [2019-09-21 15:02:37,591] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:02:37,591] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:02:37,593] - Components::findComponents: find dbmgr(3)...
  INFO root [2019-09-21 15:02:37,695] - Components::findComponents: found dbmgr, addr:10.15.26.195:54610
  INFO root [2019-09-21 15:02:37,695] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:02:37,695] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:02:37,695] - Components::findComponents: found dbmgr, addr:10.15.26.195:54610
  WARN root [2019-09-21 15:02:38,696] - Forwarding logs to logger[10.15.26.195:54614/0/0/0]...
 ERROR root [2019-09-21 15:11:42,115] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411037754, lastReceivedTime=663260762122, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 15:11:42,119] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:11:42,120] - ==> [2019-09-21 15:11:42 112] TCPPacketReceiver::processPendingEvents(10.15.26.195:54614): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:11:42,120] - ==> [2019-09-21 15:11:42 115] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411037754, lastReceivedTime=663260762122, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 15:11:42,202] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54610): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:11:42,203] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411929742, lastReceivedTime=663259934016, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 15:11:42,205] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 15:11:42,206] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:11:42,206] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 15:11:42,207] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 15:11:43,896] - 
  INFO root [2019-09-21 15:11:43,902] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:11:43,903] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:11:43,903] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:11:43,903] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:11:43,920] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54725 )
  INFO root [2019-09-21 15:11:43,920] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54725, SOMAXCONN=5.
  INFO root [2019-09-21 15:11:43,920] - server-configs:
  INFO root [2019-09-21 15:11:43,921] - 	internalTcpAddr : 10.15.26.195:54725
  INFO root [2019-09-21 15:11:43,921] - 	componentID : 6000
  WARN root [2019-09-21 15:11:43,925] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:11:45,436] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 4540 ----
  INFO root [2019-09-21 15:11:45,436] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:11:45,436] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:11:45,437] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:11:45,862] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 15:11:45,863] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 15:11:53,005] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 15:11:53,102] - Components::findComponents: found logger, addr:10.15.26.195:54721
  INFO root [2019-09-21 15:11:53,102] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:11:53,102] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:11:53,103] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 15:11:53,206] - Components::findComponents: found dbmgr, addr:10.15.26.195:54719
  INFO root [2019-09-21 15:11:53,206] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:11:53,207] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:11:53,207] - Components::findComponents: found dbmgr, addr:10.15.26.195:54719
  WARN root [2019-09-21 15:11:54,208] - Forwarding logs to logger[10.15.26.195:54721/0/0/0]...
 ERROR root [2019-09-21 15:22:59,160] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670181489809, lastReceivedTime=670027389571, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 15:22:59,162] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:22:59,162] - ==> [2019-09-21 15:22:59 159] TCPPacketReceiver::processPendingEvents(10.15.26.195:54721): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:22:59,163] - ==> [2019-09-21 15:22:59 160] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670181489809, lastReceivedTime=670027389571, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 15:22:59,239] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:22:59,241] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670182300743, lastReceivedTime=670026841731, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 15:22:59,246] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 15:22:59,247] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:22:59,247] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 15:22:59,248] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 15:35:45,409] - 
  INFO root [2019-09-21 15:35:45,410] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:35:45,411] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:35:45,412] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:35:45,412] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:35:45,423] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:55692 )
  INFO root [2019-09-21 15:35:45,424] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:55692, SOMAXCONN=5.
  INFO root [2019-09-21 15:35:45,424] - server-configs:
  INFO root [2019-09-21 15:35:45,424] - 	internalTcpAddr : 10.15.26.195:55692
  INFO root [2019-09-21 15:35:45,424] - 	componentID : 6000
  WARN root [2019-09-21 15:35:45,424] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:35:46,929] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 6708 ----
  INFO root [2019-09-21 15:35:46,929] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:35:46,930] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:35:46,930] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:35:47,318] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 15:35:47,319] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 15:35:54,451] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 15:35:54,540] - Components::findComponents: found logger, addr:10.15.26.195:55689
  INFO root [2019-09-21 15:35:54,540] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:35:54,540] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:35:54,541] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 15:35:54,546] - Components::findComponents: found logger, addr:10.15.26.195:55689
  INFO root [2019-09-21 15:35:54,548] - Components::findComponents: found dbmgr, addr:10.15.26.195:55691
  INFO root [2019-09-21 15:35:54,548] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:35:54,548] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:35:54,650] - Components::findComponents: found dbmgr, addr:10.15.26.195:55691
  WARN root [2019-09-21 15:35:55,652] - Forwarding logs to logger[10.15.26.195:55689/0/0/0]...
 ERROR root [2019-09-21 15:39:58,338] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680373274200, lastReceivedTime=680243412198, inactivityExceptionPeriod=599499169)
  INFO root [2019-09-21 15:39:58,347] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:39:58,347] - ==> [2019-09-21 15:39:58 334] TCPPacketReceiver::processPendingEvents(10.15.26.195:55689): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:39:58,348] - ==> [2019-09-21 15:39:58 340] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680373274200, lastReceivedTime=680243412198, inactivityExceptionPeriod=599499169)
  WARN root [2019-09-21 15:39:58,431] - TCPPacketReceiver::processPendingEvents(10.15.26.195:55691): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:39:58,433] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680374224602, lastReceivedTime=680243921900, inactivityExceptionPeriod=599499169)
  INFO root [2019-09-21 15:39:58,440] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 15:39:58,445] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:39:58,446] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 15:39:58,446] - ThreadPool::destroy(): starting size 2.
  INFO root [2019-09-21 15:40:00,196] - 
  INFO root [2019-09-21 15:40:00,250] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:40:00,252] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:40:00,253] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:40:00,254] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:40:00,384] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:55786 )
  INFO root [2019-09-21 15:40:00,384] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:55786, SOMAXCONN=5.
  INFO root [2019-09-21 15:40:00,384] - server-configs:
  INFO root [2019-09-21 15:40:00,385] - 	internalTcpAddr : 10.15.26.195:55786
  INFO root [2019-09-21 15:40:00,385] - 	componentID : 6000
  WARN root [2019-09-21 15:40:00,398] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:40:01,903] - ---- cellappmgr Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: AFC10615FCF531D416E7A56B687CCF1A. Config: Debug X86. Built: 09:54:16 May  8 2019. AppID: 6000. UID: 41181. PID: 15200 ----
  INFO root [2019-09-21 15:40:01,919] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:40:01,919] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:40:01,920] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:40:02,333] - ---- cellappmgr is running ----
 DEBUG root [2019-09-21 15:40:02,333] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 15:40:09,502] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 15:40:09,541] - Components::findComponents: found logger, addr:10.15.26.195:55781
  INFO root [2019-09-21 15:40:09,541] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:40:09,541] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:40:09,542] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 15:40:09,543] - Components::findComponents: found logger, addr:10.15.26.195:55781
  INFO root [2019-09-21 15:40:09,550] - Components::findComponents: found dbmgr, addr:10.15.26.195:55780
  INFO root [2019-09-21 15:40:09,550] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:40:09,550] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:40:09,654] - Components::findComponents: found dbmgr, addr:10.15.26.195:55780
  WARN root [2019-09-21 15:40:10,655] - Forwarding logs to logger[10.15.26.195:55781/0/0/0]...
 ERROR root [2019-09-21 15:55:18,419] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689574086875, lastReceivedTime=689391129853, inactivityExceptionPeriod=599498466)
  INFO root [2019-09-21 15:55:18,420] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:55:18,420] - ==> [2019-09-21 15:55:18 419] TCPPacketReceiver::processPendingEvents(10.15.26.195:55781): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:55:18,421] - ==> [2019-09-21 15:55:18 420] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689574086875, lastReceivedTime=689391129853, inactivityExceptionPeriod=599498466)
  WARN root [2019-09-21 15:55:18,585] - TCPPacketReceiver::processPendingEvents(10.15.26.195:55780): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:55:18,586] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689575760633, lastReceivedTime=689391245162, inactivityExceptionPeriod=599498466)
  INFO root [2019-09-21 15:55:18,662] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
  INFO root [2019-09-21 15:55:18,664] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:55:18,665] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2019-09-21 15:55:18,666] - ThreadPool::destroy(): starting size 2.
