  INFO root [2019-09-21 09:28:05,418] - 
  INFO root [2019-09-21 09:28:05,419] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:28:05,420] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:28:05,420] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:28:05,420] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:28:05,431] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:28:05,431] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:28:05,435] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51537 )
  INFO root [2019-09-21 09:28:05,435] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51537, SOMAXCONN=128.
  INFO root [2019-09-21 09:28:05,435] - server-configs:
  INFO root [2019-09-21 09:28:05,435] - 	internalTcpAddr : 10.15.26.195:51537
  INFO root [2019-09-21 09:28:05,435] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:28:05,435] - 	componentID : 9000
  WARN root [2019-09-21 09:28:05,602] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:28:07,107] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 11160 ----
  INFO root [2019-09-21 09:28:07,108] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:28:07,108] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:28:07,109] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:28:07,304] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:28:07,304] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:28:07,315] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:28:07,316] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:28:07,733] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:28:07,734] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:28:14,896] - Components::findComponents: find logger(1)...
 ERROR root [2019-09-21 09:28:16,398] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:16,399] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:28:16,400] - Components::findComponents: not found logger!
  INFO root [2019-09-21 09:28:17,416] - Components::findComponents: find dbmgr(1)...
 ERROR root [2019-09-21 09:28:18,918] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:18,919] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:19,922] - Components::findComponents: find dbmgr(2)...
 ERROR root [2019-09-21 09:28:21,423] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:21,423] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:22,437] - Components::findComponents: find dbmgr(3)...
 ERROR root [2019-09-21 09:28:23,938] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:23,939] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:24,957] - Components::findComponents: find dbmgr(4)...
 ERROR root [2019-09-21 09:28:26,458] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:26,460] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:27,476] - Components::findComponents: find dbmgr(5)...
 ERROR root [2019-09-21 09:28:28,977] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:28,979] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:29,996] - Components::findComponents: find dbmgr(6)...
 ERROR root [2019-09-21 09:28:31,498] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:31,500] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:32,517] - Components::findComponents: find dbmgr(7)...
 ERROR root [2019-09-21 09:28:34,018] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:34,020] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:35,037] - Components::findComponents: find dbmgr(8)...
 ERROR root [2019-09-21 09:28:36,539] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:36,539] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:37,557] - Components::findComponents: find dbmgr(9)...
 ERROR root [2019-09-21 09:28:39,058] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:39,059] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:40,076] - Components::findComponents: find dbmgr(10)...
 ERROR root [2019-09-21 09:28:41,577] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:41,581] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:42,596] - Components::findComponents: find dbmgr(11)...
 ERROR root [2019-09-21 09:28:44,097] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:44,099] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:45,116] - Components::findComponents: find dbmgr(12)...
 ERROR root [2019-09-21 09:28:46,618] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:46,619] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:47,622] - Components::findComponents: find dbmgr(13)...
 ERROR root [2019-09-21 09:28:49,124] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:49,127] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:50,136] - Components::findComponents: find dbmgr(14)...
 ERROR root [2019-09-21 09:28:51,637] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:51,639] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:52,656] - Components::findComponents: find dbmgr(15)...
 ERROR root [2019-09-21 09:28:54,157] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:54,161] - Components::findComponents: receive error!
  INFO root [2019-09-21 09:28:55,176] - Components::findComponents: find dbmgr(16)...
 ERROR root [2019-09-21 09:28:56,678] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:56,680] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:28:57,696] - Components::findComponents: find dbmgr(17)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:28:59,201] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:28:59,203] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:00,216] - Components::findComponents: find dbmgr(18)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:01,718] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:01,721] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:02,736] - Components::findComponents: find dbmgr(19)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:04,239] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:04,241] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:05,256] - Components::findComponents: find dbmgr(20)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:06,760] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:06,762] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:07,776] - Components::findComponents: find dbmgr(21)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:09,280] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:09,282] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:10,296] - Components::findComponents: find dbmgr(22)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:11,800] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:11,801] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:12,816] - Components::findComponents: find dbmgr(23)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:14,319] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:14,321] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:15,336] - Components::findComponents: find dbmgr(24)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:16,838] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:16,840] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:17,856] - Components::findComponents: find dbmgr(25)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:19,360] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:19,361] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:20,376] - Components::findComponents: find dbmgr(26)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:21,880] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:21,882] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:22,896] - Components::findComponents: find dbmgr(27)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:24,400] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:24,402] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:25,416] - Components::findComponents: find dbmgr(28)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:26,918] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:26,920] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:27,936] - Components::findComponents: find dbmgr(29)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:29,439] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:29,441] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:30,456] - Components::findComponents: find dbmgr(30)...
delay time is too long, please check the dbmgr logs!
 ERROR root [2019-09-21 09:29:31,959] - BundleBroadcast::receive: failed! It can be caused by the firewall, the broadcastaddr, etc.Maybe broadcastaddr is not a LAN ADDR, or the Machine process is not running.
 ERROR root [2019-09-21 09:29:31,961] - Components::findComponents: receive error!
  WARN root [2019-09-21 09:29:32,976] - Components::findComponents: find dbmgr(31)...
delay time is too long, please check the dbmgr logs!
  INFO root [2019-09-21 09:29:34,541] - 
  INFO root [2019-09-21 09:29:34,541] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:29:34,543] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:29:34,543] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:29:34,543] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:29:34,566] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:29:34,566] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:29:34,569] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51569 )
  INFO root [2019-09-21 09:29:34,570] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51569, SOMAXCONN=128.
  INFO root [2019-09-21 09:29:34,570] - server-configs:
  INFO root [2019-09-21 09:29:34,570] - 	internalTcpAddr : 10.15.26.195:51569
  INFO root [2019-09-21 09:29:34,571] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:29:34,571] - 	componentID : 9000
  WARN root [2019-09-21 09:29:34,728] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:29:34,818] - Components::findLogger: found logger, addr:10.15.26.195:51565
  INFO root [2019-09-21 09:29:34,819] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:29:34,819] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:29:34,823] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 4224 ----
  INFO root [2019-09-21 09:29:34,824] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:29:34,824] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:29:34,824] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:29:35,059] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:29:35,059] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:29:35,071] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:29:35,071] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:29:35,452] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:29:35,452] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:29:41,573] - Forwarding logs to logger[10.15.26.195:51565/0/0/0]...
  INFO root [2019-09-21 09:38:53,617] - EventDispatcher()::~EventDispatcher: Num timers = 1
  INFO root [2019-09-21 09:40:36,978] - 
  INFO root [2019-09-21 09:40:36,979] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:40:36,980] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:40:36,980] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:40:36,980] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:40:37,000] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:40:37,001] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:40:37,005] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51761 )
  INFO root [2019-09-21 09:40:37,005] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51761, SOMAXCONN=128.
  INFO root [2019-09-21 09:40:37,005] - server-configs:
  INFO root [2019-09-21 09:40:37,005] - 	internalTcpAddr : 10.15.26.195:51761
  INFO root [2019-09-21 09:40:37,006] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:40:37,006] - 	componentID : 9000
  WARN root [2019-09-21 09:40:37,177] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:40:37,422] - Components::findLogger: found logger, addr:10.15.26.195:51754
  INFO root [2019-09-21 09:40:37,423] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:40:37,423] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:40:37,428] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 14208 ----
  INFO root [2019-09-21 09:40:37,428] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:40:37,429] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:40:37,429] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:40:37,632] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:40:37,632] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:40:37,644] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:40:37,644] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:40:38,052] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:40:38,053] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:40:44,180] - Forwarding logs to logger[10.15.26.195:51754/0/0/0]...
 ERROR root [2019-09-21 09:45:33,913] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467633601964, lastReceivedTime=467362721554, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 09:45:33,915] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:45:33,915] - ==> [2019-09-21 09:45:33 913] TCPPacketReceiver::processPendingEvents(10.15.26.195:51754): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:45:33,915] - ==> [2019-09-21 09:45:33 914] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467633601964, lastReceivedTime=467362721554, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 09:45:34,014] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51759): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:45:34,016] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=467634623012, lastReceivedTime=467364197939, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 09:45:34,025] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 09:45:34,028] - onLoginAppShutDown()
  INFO root [2019-09-21 09:45:34,029] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:45:34,029] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 09:45:34,046] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 09:45:34,046] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 09:45:34,347] - ThreadPool::destroy(): waiting for thread(2)[0x2039d98,0x203a008,], try=1
  INFO root [2019-09-21 09:48:09,609] - 
  INFO root [2019-09-21 09:48:09,612] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:48:09,613] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:48:09,613] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:48:09,614] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:48:09,630] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:48:09,630] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:48:09,634] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51847 )
  INFO root [2019-09-21 09:48:09,635] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51847, SOMAXCONN=128.
  INFO root [2019-09-21 09:48:09,635] - server-configs:
  INFO root [2019-09-21 09:48:09,635] - 	internalTcpAddr : 10.15.26.195:51847
  INFO root [2019-09-21 09:48:09,635] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:48:09,635] - 	componentID : 9000
  WARN root [2019-09-21 09:48:09,796] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:48:11,301] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12364 ----
  INFO root [2019-09-21 09:48:11,308] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:48:11,309] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:48:11,309] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:48:11,731] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:48:11,731] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:48:11,745] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:48:11,745] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:48:12,216] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:48:12,216] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:48:18,348] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51857): Throwing REASON_GENERAL_NETWORK - WSAECONNABORTED
  INFO root [2019-09-21 09:48:19,365] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:48:19,462] - Components::findComponents: found logger, addr:10.15.26.195:51845
  INFO root [2019-09-21 09:48:19,462] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:48:19,462] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:48:19,463] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:48:19,567] - Components::findComponents: found dbmgr, addr:10.15.26.195:51846
  INFO root [2019-09-21 09:48:19,567] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:48:19,567] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:48:19,567] - Components::findComponents: found dbmgr, addr:10.15.26.195:51846
  WARN root [2019-09-21 09:48:20,569] - Forwarding logs to logger[10.15.26.195:51845/0/0/0]...
 ERROR root [2019-09-21 09:52:20,732] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471701786024, lastReceivedTime=471590631426, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 09:52:20,733] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:52:20,734] - ==> [2019-09-21 09:52:20 730] TCPPacketReceiver::processPendingEvents(10.15.26.195:51845): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:52:20,734] - ==> [2019-09-21 09:52:20 733] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471701786024, lastReceivedTime=471590631426, inactivityExceptionPeriod=599500192)
  WARN root [2019-09-21 09:52:20,831] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51846): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:52:20,833] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=471702797439, lastReceivedTime=471590612788, inactivityExceptionPeriod=599500192)
  INFO root [2019-09-21 09:52:20,850] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 09:52:20,862] - onLoginAppShutDown()
  INFO root [2019-09-21 09:52:20,863] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:52:20,863] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 09:52:20,881] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 09:52:20,882] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 09:52:21,183] - ThreadPool::destroy(): waiting for thread(2)[0x1f05db8,0x1f05328,], try=1
  INFO root [2019-09-21 09:54:15,376] - 
  INFO root [2019-09-21 09:54:15,377] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:54:15,378] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:54:15,378] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:54:15,378] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:54:15,389] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:54:15,389] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:54:15,393] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:51943 )
  INFO root [2019-09-21 09:54:15,394] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:51943, SOMAXCONN=128.
  INFO root [2019-09-21 09:54:15,394] - server-configs:
  INFO root [2019-09-21 09:54:15,394] - 	internalTcpAddr : 10.15.26.195:51943
  INFO root [2019-09-21 09:54:15,394] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:54:15,394] - 	componentID : 9000
  WARN root [2019-09-21 09:54:15,603] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  WARN root [2019-09-21 09:54:15,981] - BundleBroadcast::BundleBroadcast: Cannot bind to port 20493, errorno=10048
  INFO root [2019-09-21 09:54:15,985] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 10364 ----
  INFO root [2019-09-21 09:54:15,985] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:54:15,985] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:54:15,987] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:54:16,210] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:54:16,211] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:54:16,223] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:54:16,223] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:54:16,658] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:54:16,659] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 09:54:23,802] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:54:23,885] - Components::findComponents: found logger, addr:10.15.26.195:51946
  INFO root [2019-09-21 09:54:23,885] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:54:23,885] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:54:23,886] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:54:23,990] - Components::findComponents: found dbmgr, addr:10.15.26.195:51947
  INFO root [2019-09-21 09:54:23,990] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:54:23,990] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:54:23,991] - Components::findComponents: found dbmgr, addr:10.15.26.195:51947
  WARN root [2019-09-21 09:54:24,992] - Forwarding logs to logger[10.15.26.195:51946/0/0/0]...
 ERROR root [2019-09-21 09:56:00,285] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473897324639, lastReceivedTime=473749885070, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 09:56:00,289] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:56:00,289] - ==> [2019-09-21 09:56:00 285] TCPPacketReceiver::processPendingEvents(10.15.26.195:51946): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:56:00,289] - ==> [2019-09-21 09:56:00 287] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473897324639, lastReceivedTime=473749885070, inactivityExceptionPeriod=599500064)
  WARN root [2019-09-21 09:56:00,376] - TCPPacketReceiver::processPendingEvents(10.15.26.195:51947): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:56:00,378] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=473898244243, lastReceivedTime=473750520304, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 09:56:00,385] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 09:56:00,389] - onLoginAppShutDown()
  INFO root [2019-09-21 09:56:00,389] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:56:00,389] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 09:56:00,404] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 09:56:00,404] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 09:56:00,705] - ThreadPool::destroy(): waiting for thread(2)[0x1b57db8,0x1b57e88,], try=1
  INFO root [2019-09-21 09:56:02,245] - 
  INFO root [2019-09-21 09:56:02,275] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:56:02,276] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:56:02,276] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:56:02,276] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:56:02,294] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:56:02,294] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:56:02,298] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52020 )
  INFO root [2019-09-21 09:56:02,298] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52020, SOMAXCONN=128.
  INFO root [2019-09-21 09:56:02,298] - server-configs:
  INFO root [2019-09-21 09:56:02,298] - 	internalTcpAddr : 10.15.26.195:52020
  INFO root [2019-09-21 09:56:02,298] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:56:02,298] - 	componentID : 9000
  WARN root [2019-09-21 09:56:02,476] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:56:02,604] - Components::findLogger: found logger, addr:10.15.26.195:52015
  INFO root [2019-09-21 09:56:02,604] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:56:02,605] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:56:02,615] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 11064 ----
  INFO root [2019-09-21 09:56:02,616] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:56:02,616] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:56:02,617] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:56:02,972] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:56:02,973] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:56:02,987] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:56:02,988] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:56:03,429] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:56:03,429] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:56:09,543] - Forwarding logs to logger[10.15.26.195:52015/0/0/0]...
 ERROR root [2019-09-21 09:57:59,388] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475088348243, lastReceivedTime=474815477876, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 09:57:59,394] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:57:59,395] - ==> [2019-09-21 09:57:59 386] TCPPacketReceiver::processPendingEvents(10.15.26.195:52015): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:57:59,395] - ==> [2019-09-21 09:57:59 389] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475088348243, lastReceivedTime=474815477876, inactivityExceptionPeriod=599499745)
  WARN root [2019-09-21 09:57:59,480] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52013): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:57:59,481] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=475089278259, lastReceivedTime=474924449202, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 09:57:59,488] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 09:57:59,499] - onLoginAppShutDown()
  INFO root [2019-09-21 09:57:59,499] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:57:59,499] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 09:57:59,514] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 09:57:59,514] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 09:57:59,815] - ThreadPool::destroy(): waiting for thread(2)[0xb862d0,0xb86748,], try=1
  INFO root [2019-09-21 09:58:01,186] - 
  INFO root [2019-09-21 09:58:01,191] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 09:58:01,193] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 09:58:01,193] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 09:58:01,194] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 09:58:01,224] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 09:58:01,225] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 09:58:01,228] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52077 )
  INFO root [2019-09-21 09:58:01,229] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52077, SOMAXCONN=128.
  INFO root [2019-09-21 09:58:01,229] - server-configs:
  INFO root [2019-09-21 09:58:01,229] - 	internalTcpAddr : 10.15.26.195:52077
  INFO root [2019-09-21 09:58:01,229] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 09:58:01,229] - 	componentID : 9000
  WARN root [2019-09-21 09:58:01,407] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 09:58:02,912] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 9428 ----
  INFO root [2019-09-21 09:58:02,913] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 09:58:02,913] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 09:58:02,913] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 09:58:03,196] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 09:58:03,196] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 09:58:03,208] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 09:58:03,208] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 09:58:03,653] - ---- loginapp is running ----
 DEBUG root [2019-09-21 09:58:03,653] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 09:58:09,774] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52086): Throwing REASON_GENERAL_NETWORK - WSAECONNABORTED
  INFO root [2019-09-21 09:58:10,789] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 09:58:10,828] - Components::findComponents: found logger, addr:10.15.26.195:52074
  INFO root [2019-09-21 09:58:10,828] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:58:10,828] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:58:10,830] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 09:58:10,835] - Components::findComponents: found logger, addr:10.15.26.195:52074
  INFO root [2019-09-21 09:58:10,837] - Components::findComponents: found dbmgr, addr:10.15.26.195:52070
  INFO root [2019-09-21 09:58:10,838] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 09:58:10,838] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 09:58:10,937] - Components::findComponents: found dbmgr, addr:10.15.26.195:52070
  WARN root [2019-09-21 09:58:11,939] - Forwarding logs to logger[10.15.26.195:52074/0/0/0]...
 ERROR root [2019-09-21 09:59:51,504] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476209499113, lastReceivedTime=476006458554, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:59:51,513] - The following logs sent to logger failed:
  WARN root [2019-09-21 09:59:51,513] - ==> [2019-09-21 09:59:51 500] TCPPacketReceiver::processPendingEvents(10.15.26.195:52074): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:59:51,513] - ==> [2019-09-21 09:59:51 504] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476209499113, lastReceivedTime=476006458554, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 09:59:51,601] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52070): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 09:59:51,604] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=476210507214, lastReceivedTime=476006156585, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 09:59:51,618] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 09:59:51,628] - onLoginAppShutDown()
  INFO root [2019-09-21 09:59:51,628] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 09:59:51,628] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 09:59:51,645] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 09:59:51,646] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 09:59:51,947] - ThreadPool::destroy(): waiting for thread(2)[0x8a8b40,0x8a8db0,], try=1
  INFO root [2019-09-21 10:01:45,668] - 
  INFO root [2019-09-21 10:01:45,674] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:01:45,676] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:01:45,676] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:01:45,676] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:01:45,685] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 10:01:45,686] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 10:01:45,689] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52163 )
  INFO root [2019-09-21 10:01:45,690] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52163, SOMAXCONN=128.
  INFO root [2019-09-21 10:01:45,690] - server-configs:
  INFO root [2019-09-21 10:01:45,690] - 	internalTcpAddr : 10.15.26.195:52163
  INFO root [2019-09-21 10:01:45,690] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 10:01:45,690] - 	componentID : 9000
  WARN root [2019-09-21 10:01:45,878] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:01:46,076] - Components::findLogger: found logger, addr:10.15.26.195:52158
  INFO root [2019-09-21 10:01:46,076] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:01:46,076] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:01:46,081] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12584 ----
  INFO root [2019-09-21 10:01:46,082] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:01:46,082] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:01:46,083] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:01:46,282] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 10:01:46,282] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 10:01:46,293] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 10:01:46,294] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 10:01:46,690] - ---- loginapp is running ----
 DEBUG root [2019-09-21 10:01:46,690] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 10:01:52,813] - Forwarding logs to logger[10.15.26.195:52158/0/0/0]...
 ERROR root [2019-09-21 10:05:33,654] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479631009254, lastReceivedTime=479450323190, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 10:05:33,662] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:05:33,662] - ==> [2019-09-21 10:05:33 651] TCPPacketReceiver::processPendingEvents(10.15.26.195:52158): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:05:33,662] - ==> [2019-09-21 10:05:33 656] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479631009254, lastReceivedTime=479450323190, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 10:05:33,797] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52159): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:05:33,804] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=479632507706, lastReceivedTime=479450410756, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 10:05:33,830] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 10:05:33,835] - onLoginAppShutDown()
  INFO root [2019-09-21 10:05:33,836] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:05:33,837] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 10:05:33,855] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 10:05:33,855] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 10:05:34,155] - ThreadPool::destroy(): waiting for thread(2)[0x1f9bb60,0x1f9b6e8,], try=1
 DEBUG root [2019-09-21 10:05:34,562] - TPThread::~TPThread(): 0x1f9bb60
 DEBUG root [2019-09-21 10:05:34,563] - TPThread::~TPThread(): 0x1f9b6e8
 DEBUG root [2019-09-21 10:05:34,566] - ThreadPool::destroy(): successfully!
 DEBUG root [2019-09-21 10:05:34,587] - Bundle::destroyObjPool(): size 20.
 DEBUG root [2019-09-21 10:05:34,587] - Channel::destroyObjPool(): size 15.
 DEBUG root [2019-09-21 10:05:34,587] - TCPPacket::destroyObjPool(): size 3.
 DEBUG root [2019-09-21 10:05:34,587] - UDPPacket::destroyObjPool(): size 2.
 DEBUG root [2019-09-21 10:05:34,587] - EndPoint::destroyObjPool(): size 14.
 DEBUG root [2019-09-21 10:05:34,587] - Address::destroyObjPool(): size 0.
 DEBUG root [2019-09-21 10:05:34,588] - TCPPacketReceiver::destroyObjPool(): size 0.
 DEBUG root [2019-09-21 10:05:34,588] - UDPPacketReceiver::destroyObjPool(): size 0.
  INFO root [2019-09-21 10:05:34,588] - loginapp(9000) has shut down.
  INFO root [2019-09-21 10:06:38,585] - 
  INFO root [2019-09-21 10:06:38,586] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:06:38,587] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:06:38,587] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:06:38,587] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:06:38,603] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 10:06:38,604] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 10:06:38,607] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52227 )
  INFO root [2019-09-21 10:06:38,607] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52227, SOMAXCONN=128.
  INFO root [2019-09-21 10:06:38,608] - server-configs:
  INFO root [2019-09-21 10:06:38,608] - 	internalTcpAddr : 10.15.26.195:52227
  INFO root [2019-09-21 10:06:38,608] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 10:06:38,609] - 	componentID : 9000
  WARN root [2019-09-21 10:06:38,786] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:06:39,100] - Components::findLogger: found logger, addr:10.15.26.195:52222
  INFO root [2019-09-21 10:06:39,100] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:06:39,101] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:06:39,106] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 8252 ----
  INFO root [2019-09-21 10:06:39,107] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:06:39,107] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:06:39,108] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:06:39,314] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 10:06:39,314] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 10:06:39,325] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 10:06:39,325] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 10:06:39,764] - ---- loginapp is running ----
 DEBUG root [2019-09-21 10:06:39,764] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 10:06:45,896] - Forwarding logs to logger[10.15.26.195:52222/0/0/0]...
 ERROR root [2019-09-21 10:27:24,719] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492741659830, lastReceivedTime=492579519936, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 10:27:24,725] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:27:24,725] - ==> [2019-09-21 10:27:24 719] TCPPacketReceiver::processPendingEvents(10.15.26.195:52222): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:27:24,725] - ==> [2019-09-21 10:27:24 720] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492741659830, lastReceivedTime=492579519936, inactivityExceptionPeriod=599499745)
  WARN root [2019-09-21 10:27:24,805] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52223): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:27:24,808] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=492742540529, lastReceivedTime=492579862320, inactivityExceptionPeriod=599499745)
  INFO root [2019-09-21 10:27:24,813] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 10:27:24,814] - onLoginAppShutDown()
  INFO root [2019-09-21 10:27:24,814] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:27:24,814] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 10:27:24,824] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 10:27:24,824] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 10:27:25,125] - ThreadPool::destroy(): waiting for thread(2)[0x1bf81d0,0x1bf8100,], try=1
  INFO root [2019-09-21 10:52:47,020] - 
  INFO root [2019-09-21 10:52:47,022] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:52:47,023] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:52:47,023] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:52:47,024] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:52:47,057] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 10:52:47,057] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 10:52:47,067] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52806 )
  INFO root [2019-09-21 10:52:47,067] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52806, SOMAXCONN=128.
  INFO root [2019-09-21 10:52:47,067] - server-configs:
  INFO root [2019-09-21 10:52:47,067] - 	internalTcpAddr : 10.15.26.195:52806
  INFO root [2019-09-21 10:52:47,067] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 10:52:47,067] - 	componentID : 9000
  WARN root [2019-09-21 10:52:47,238] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:52:47,619] - Components::findLogger: found logger, addr:10.15.26.195:52800
  INFO root [2019-09-21 10:52:47,620] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:52:47,620] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:52:47,625] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 13432 ----
  INFO root [2019-09-21 10:52:47,628] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:52:47,653] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:52:47,653] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:52:47,917] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 10:52:47,917] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 10:52:47,928] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 10:52:47,929] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 10:52:48,445] - ---- loginapp is running ----
 DEBUG root [2019-09-21 10:52:48,448] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 10:52:54,587] - Forwarding logs to logger[10.15.26.195:52800/0/0/0]...
 ERROR root [2019-09-21 10:54:19,521] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508889680674, lastReceivedTime=508864551274, inactivityExceptionPeriod=599497826)
  INFO root [2019-09-21 10:54:19,524] - The following logs sent to logger failed:
  WARN root [2019-09-21 10:54:19,525] - ==> [2019-09-21 10:54:19 515] TCPPacketReceiver::processPendingEvents(10.15.26.195:52800): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:54:19,525] - ==> [2019-09-21 10:54:19 522] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508889680674, lastReceivedTime=508864551274, inactivityExceptionPeriod=599497826)
  WARN root [2019-09-21 10:54:19,621] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52804): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 10:54:19,623] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=508890699892, lastReceivedTime=508865148013, inactivityExceptionPeriod=599497826)
  INFO root [2019-09-21 10:54:19,641] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 10:54:19,646] - onLoginAppShutDown()
  INFO root [2019-09-21 10:54:19,646] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 10:54:19,646] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 10:54:19,663] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 10:54:19,663] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 10:54:19,965] - ThreadPool::destroy(): waiting for thread(2)[0x8e70b0,0x8e6d08,], try=1
  INFO root [2019-09-21 10:54:21,708] - 
  INFO root [2019-09-21 10:54:21,718] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 10:54:21,719] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 10:54:21,720] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 10:54:21,721] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 10:54:21,822] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 10:54:21,822] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 10:54:21,826] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:52887 )
  INFO root [2019-09-21 10:54:21,826] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:52887, SOMAXCONN=128.
  INFO root [2019-09-21 10:54:21,826] - server-configs:
  INFO root [2019-09-21 10:54:21,826] - 	internalTcpAddr : 10.15.26.195:52887
  INFO root [2019-09-21 10:54:21,826] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 10:54:21,826] - 	componentID : 9000
  WARN root [2019-09-21 10:54:22,005] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 10:54:22,191] - Components::findLogger: found logger, addr:10.15.26.195:52880
  INFO root [2019-09-21 10:54:22,191] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 10:54:22,191] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 10:54:22,198] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 7632 ----
  INFO root [2019-09-21 10:54:22,199] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 10:54:22,199] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 10:54:22,199] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 10:54:22,405] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 10:54:22,406] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 10:54:22,417] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 10:54:22,418] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 10:54:22,843] - ---- loginapp is running ----
 DEBUG root [2019-09-21 10:54:22,843] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 10:54:28,990] - Forwarding logs to logger[10.15.26.195:52880/0/0/0]...
 ERROR root [2019-09-21 11:09:42,243] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518116893366, lastReceivedTime=517908118503, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:09:42,249] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:09:42,249] - ==> [2019-09-21 11:09:42 239] TCPPacketReceiver::processPendingEvents(10.15.26.195:52880): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:09:42,249] - ==> [2019-09-21 11:09:42 244] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518116893366, lastReceivedTime=517908118503, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 11:09:42,342] - TCPPacketReceiver::processPendingEvents(10.15.26.195:52882): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:09:42,348] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=518117946467, lastReceivedTime=517909708421, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:09:42,358] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 11:09:42,361] - onLoginAppShutDown()
  INFO root [2019-09-21 11:09:42,362] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:09:42,362] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 11:09:42,376] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 11:09:42,377] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 11:09:42,678] - ThreadPool::destroy(): waiting for thread(2)[0x5f71c0,0x5f7228,], try=1
  INFO root [2019-09-21 11:10:44,833] - 
  INFO root [2019-09-21 11:10:44,835] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:10:44,836] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:10:44,836] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:10:44,836] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:10:44,859] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 11:10:44,859] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 11:10:44,863] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53008 )
  INFO root [2019-09-21 11:10:44,863] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53008, SOMAXCONN=128.
  INFO root [2019-09-21 11:10:44,864] - server-configs:
  INFO root [2019-09-21 11:10:44,864] - 	internalTcpAddr : 10.15.26.195:53008
  INFO root [2019-09-21 11:10:44,864] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 11:10:44,864] - 	componentID : 9000
  WARN root [2019-09-21 11:10:45,029] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:10:45,294] - Components::findLogger: found logger, addr:10.15.26.195:53004
  INFO root [2019-09-21 11:10:45,295] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:10:45,295] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:10:45,300] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 2928 ----
  INFO root [2019-09-21 11:10:45,300] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:10:45,301] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:10:45,301] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:10:45,494] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 11:10:45,494] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 11:10:45,505] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 11:10:45,506] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 11:10:45,894] - ---- loginapp is running ----
 DEBUG root [2019-09-21 11:10:45,895] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 11:10:52,016] - Forwarding logs to logger[10.15.26.195:53004/0/0/0]...
 ERROR root [2019-09-21 11:13:18,265] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520277113431, lastReceivedTime=520242456472, inactivityExceptionPeriod=599497123)
  INFO root [2019-09-21 11:13:18,272] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:13:18,272] - ==> [2019-09-21 11:13:18 262] TCPPacketReceiver::processPendingEvents(10.15.26.195:53004): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:13:18,272] - ==> [2019-09-21 11:13:18 266] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520277113431, lastReceivedTime=520242456472, inactivityExceptionPeriod=599497123)
  WARN root [2019-09-21 11:13:18,361] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53003): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:13:18,362] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=520278092115, lastReceivedTime=520242414182, inactivityExceptionPeriod=599497123)
  INFO root [2019-09-21 11:13:18,365] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 11:13:18,367] - onLoginAppShutDown()
  INFO root [2019-09-21 11:13:18,368] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:13:18,368] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 11:13:18,381] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 11:13:18,381] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 11:13:18,683] - ThreadPool::destroy(): waiting for thread(2)[0x1c29288,0x1c28e10,], try=1
  INFO root [2019-09-21 11:13:20,178] - 
  INFO root [2019-09-21 11:13:20,179] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:13:20,180] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:13:20,181] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:13:20,181] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:13:20,201] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 11:13:20,201] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 11:13:20,205] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53070 )
  INFO root [2019-09-21 11:13:20,206] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53070, SOMAXCONN=128.
  INFO root [2019-09-21 11:13:20,206] - server-configs:
  INFO root [2019-09-21 11:13:20,206] - 	internalTcpAddr : 10.15.26.195:53070
  INFO root [2019-09-21 11:13:20,206] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 11:13:20,206] - 	componentID : 9000
  WARN root [2019-09-21 11:13:20,372] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:13:21,897] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 15512 ----
  INFO root [2019-09-21 11:13:21,898] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:13:21,898] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:13:21,898] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:13:22,217] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 11:13:22,217] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 11:13:22,228] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 11:13:22,228] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 11:13:22,665] - ---- loginapp is running ----
 DEBUG root [2019-09-21 11:13:22,665] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 11:13:29,809] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 11:13:29,898] - Components::findComponents: found logger, addr:10.15.26.195:53069
  INFO root [2019-09-21 11:13:29,899] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:13:29,899] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:13:29,900] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 11:13:29,904] - Components::findComponents: found dbmgr, addr:10.15.26.195:53063
  INFO root [2019-09-21 11:13:29,904] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:13:29,905] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:13:30,007] - Components::findComponents: found dbmgr, addr:10.15.26.195:53063
  WARN root [2019-09-21 11:13:31,008] - Forwarding logs to logger[10.15.26.195:53069/0/0/0]...
 ERROR root [2019-09-21 11:16:26,652] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522160990541, lastReceivedTime=522096297543, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:16:26,659] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:16:26,659] - ==> [2019-09-21 11:16:26 647] TCPPacketReceiver::processPendingEvents(10.15.26.195:53069): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:16:26,660] - ==> [2019-09-21 11:16:26 653] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522160990541, lastReceivedTime=522096297543, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 11:16:26,750] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53063): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:16:26,755] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522162017698, lastReceivedTime=522094879939, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:16:26,772] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 11:16:26,783] - onLoginAppShutDown()
  INFO root [2019-09-21 11:16:26,783] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:16:26,783] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 11:16:26,798] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 11:16:26,800] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 11:16:27,100] - ThreadPool::destroy(): waiting for thread(2)[0x9b80d8,0x9b81a8,], try=1
  INFO root [2019-09-21 11:16:31,321] - 
  INFO root [2019-09-21 11:16:31,330] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:16:31,331] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:16:31,331] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:16:31,331] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:16:31,357] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 11:16:31,357] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 11:16:31,361] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53125 )
  INFO root [2019-09-21 11:16:31,361] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53125, SOMAXCONN=128.
  INFO root [2019-09-21 11:16:31,362] - server-configs:
  INFO root [2019-09-21 11:16:31,362] - 	internalTcpAddr : 10.15.26.195:53125
  INFO root [2019-09-21 11:16:31,362] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 11:16:31,362] - 	componentID : 9000
  WARN root [2019-09-21 11:16:31,571] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:16:31,870] - Components::findLogger: found logger, addr:10.15.26.195:53118
  INFO root [2019-09-21 11:16:31,870] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:16:31,870] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:16:31,876] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 13136 ----
  INFO root [2019-09-21 11:16:31,876] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:16:31,876] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:16:31,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:16:32,082] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 11:16:32,082] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 11:16:32,096] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 11:16:32,097] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 11:16:32,551] - ---- loginapp is running ----
 DEBUG root [2019-09-21 11:16:32,573] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 11:16:38,722] - Forwarding logs to logger[10.15.26.195:53118/0/0/0]...
 ERROR root [2019-09-21 11:17:01,825] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522512714956, lastReceivedTime=522506270584, inactivityExceptionPeriod=599499489)
  INFO root [2019-09-21 11:17:01,828] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:17:01,828] - ==> [2019-09-21 11:17:01 823] TCPPacketReceiver::processPendingEvents(10.15.26.195:53118): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:17:01,828] - ==> [2019-09-21 11:17:01 826] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522512714956, lastReceivedTime=522506270584, inactivityExceptionPeriod=599499489)
  WARN root [2019-09-21 11:17:01,912] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53122): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:17:01,913] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=522513605085, lastReceivedTime=522508016087, inactivityExceptionPeriod=599499489)
  INFO root [2019-09-21 11:17:01,917] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 11:17:01,920] - onLoginAppShutDown()
  INFO root [2019-09-21 11:17:01,920] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:17:01,920] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 11:17:01,929] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 11:17:01,929] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 11:17:02,231] - ThreadPool::destroy(): waiting for thread(2)[0x6298a8,0x629c50,], try=1
  INFO root [2019-09-21 11:17:03,636] - 
  INFO root [2019-09-21 11:17:03,647] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 11:17:03,648] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 11:17:03,649] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 11:17:03,650] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 11:17:03,665] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 11:17:03,665] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 11:17:03,669] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:53159 )
  INFO root [2019-09-21 11:17:03,670] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:53159, SOMAXCONN=128.
  INFO root [2019-09-21 11:17:03,670] - server-configs:
  INFO root [2019-09-21 11:17:03,670] - 	internalTcpAddr : 10.15.26.195:53159
  INFO root [2019-09-21 11:17:03,670] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 11:17:03,670] - 	componentID : 9000
  WARN root [2019-09-21 11:17:03,867] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 11:17:04,180] - Components::findLogger: found logger, addr:10.15.26.195:53153
  INFO root [2019-09-21 11:17:04,180] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 11:17:04,180] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 11:17:04,185] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 15236 ----
  INFO root [2019-09-21 11:17:04,186] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 11:17:04,186] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 11:17:04,186] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 11:17:04,393] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 11:17:04,393] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 11:17:04,405] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 11:17:04,405] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 11:17:04,812] - ---- loginapp is running ----
 DEBUG root [2019-09-21 11:17:04,812] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 11:17:10,956] - Forwarding logs to logger[10.15.26.195:53153/0/0/0]...
 ERROR root [2019-09-21 11:20:54,428] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524838751300, lastReceivedTime=524629263959, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:20:54,430] - The following logs sent to logger failed:
  WARN root [2019-09-21 11:20:54,430] - ==> [2019-09-21 11:20:54 428] TCPPacketReceiver::processPendingEvents(10.15.26.195:53153): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:20:54,431] - ==> [2019-09-21 11:20:54 429] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524838751300, lastReceivedTime=524629263959, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 11:20:54,528] - TCPPacketReceiver::processPendingEvents(10.15.26.195:53158): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 11:20:54,530] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=524839767610, lastReceivedTime=524631087160, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 11:20:54,535] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 11:20:54,538] - onLoginAppShutDown()
  INFO root [2019-09-21 11:20:54,539] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 11:20:54,539] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 11:20:54,550] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 11:20:54,551] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 11:20:54,852] - ThreadPool::destroy(): waiting for thread(2)[0x86a908,0x86a970,], try=1
  INFO root [2019-09-21 14:44:23,173] - 
  INFO root [2019-09-21 14:44:23,208] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 14:44:23,210] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 14:44:23,210] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 14:44:23,210] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 14:44:23,220] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 14:44:23,220] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 14:44:23,224] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54422 )
  INFO root [2019-09-21 14:44:23,224] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54422, SOMAXCONN=128.
  INFO root [2019-09-21 14:44:23,225] - server-configs:
  INFO root [2019-09-21 14:44:23,225] - 	internalTcpAddr : 10.15.26.195:54422
  INFO root [2019-09-21 14:44:23,225] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 14:44:23,225] - 	componentID : 9000
  WARN root [2019-09-21 14:44:23,380] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 14:44:24,885] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 16316 ----
  INFO root [2019-09-21 14:44:24,886] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 14:44:24,886] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 14:44:24,886] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 14:44:25,080] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 14:44:25,080] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 14:44:25,090] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 14:44:25,091] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 14:44:25,555] - ---- loginapp is running ----
 DEBUG root [2019-09-21 14:44:25,569] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 14:44:32,711] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 14:44:32,727] - Components::findComponents: found logger, addr:10.15.26.195:54427
  INFO root [2019-09-21 14:44:32,727] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 14:44:32,728] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 14:44:32,729] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 14:44:32,734] - Components::findComponents: found dbmgr, addr:10.15.26.195:54424
  INFO root [2019-09-21 14:44:32,734] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 14:44:32,734] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 14:44:32,836] - Components::findComponents: found dbmgr, addr:10.15.26.195:54424
  WARN root [2019-09-21 14:44:33,837] - Forwarding logs to logger[10.15.26.195:54427/0/0/0]...
 ERROR root [2019-09-21 14:54:59,595] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653385844193, lastReceivedTime=653324856951, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 14:54:59,602] - The following logs sent to logger failed:
  WARN root [2019-09-21 14:54:59,603] - ==> [2019-09-21 14:54:59 594] TCPPacketReceiver::processPendingEvents(10.15.26.195:54427): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 14:54:59,603] - ==> [2019-09-21 14:54:59 596] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653385844193, lastReceivedTime=653324856951, inactivityExceptionPeriod=599500064)
  WARN root [2019-09-21 14:54:59,708] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54424): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 14:54:59,708] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=653386982019, lastReceivedTime=653322504548, inactivityExceptionPeriod=599500064)
  INFO root [2019-09-21 14:54:59,728] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 14:54:59,730] - onLoginAppShutDown()
  INFO root [2019-09-21 14:54:59,730] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 14:54:59,730] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 14:54:59,745] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 14:54:59,745] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 14:55:00,046] - ThreadPool::destroy(): waiting for thread(2)[0x19a9068,0x19a8ec8,], try=1
  INFO root [2019-09-21 15:02:27,126] - 
  INFO root [2019-09-21 15:02:27,127] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:02:27,128] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:02:27,128] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:02:27,128] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:02:27,138] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 15:02:27,139] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 15:02:27,142] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54615 )
  INFO root [2019-09-21 15:02:27,142] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54615, SOMAXCONN=128.
  INFO root [2019-09-21 15:02:27,142] - server-configs:
  INFO root [2019-09-21 15:02:27,142] - 	internalTcpAddr : 10.15.26.195:54615
  INFO root [2019-09-21 15:02:27,142] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 15:02:27,143] - 	componentID : 9000
  WARN root [2019-09-21 15:02:27,313] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:02:28,818] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 7736 ----
  INFO root [2019-09-21 15:02:28,819] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:02:28,819] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:02:28,819] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:02:29,089] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 15:02:29,089] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 15:02:29,101] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 15:02:29,101] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 15:02:29,543] - ---- loginapp is running ----
 DEBUG root [2019-09-21 15:02:29,543] - Components::process(): Request for the process of identity...
  INFO root [2019-09-21 15:02:36,702] - Components::findComponents: find logger(1)...
  INFO root [2019-09-21 15:02:36,763] - Components::findComponents: found logger, addr:10.15.26.195:54614
  INFO root [2019-09-21 15:02:36,763] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:02:36,764] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:02:36,765] - Components::findComponents: find dbmgr(2)...
  INFO root [2019-09-21 15:02:36,868] - Components::findComponents: found dbmgr, addr:10.15.26.195:54610
  INFO root [2019-09-21 15:02:36,868] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:02:36,868] - Components::addComponent[dbmgr], uid=41181, componentID=4000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:02:36,874] - Components::findComponents: found dbmgr, addr:10.15.26.195:54610
  WARN root [2019-09-21 15:02:37,875] - Forwarding logs to logger[10.15.26.195:54614/0/0/0]...
 ERROR root [2019-09-21 15:11:42,112] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411015872, lastReceivedTime=663260766886, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 15:11:42,115] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:11:42,115] - ==> [2019-09-21 15:11:42 112] TCPPacketReceiver::processPendingEvents(10.15.26.195:54614): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:11:42,115] - ==> [2019-09-21 15:11:42 113] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411015872, lastReceivedTime=663260766886, inactivityExceptionPeriod=599499873)
  WARN root [2019-09-21 15:11:42,202] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54610): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:11:42,204] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=663411942693, lastReceivedTime=663259937085, inactivityExceptionPeriod=599499873)
  INFO root [2019-09-21 15:11:42,209] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 15:11:42,210] - onLoginAppShutDown()
  INFO root [2019-09-21 15:11:42,210] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:11:42,210] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 15:11:42,219] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 15:11:42,220] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 15:11:42,521] - ThreadPool::destroy(): waiting for thread(2)[0x13ffcd0,0x14007c8,], try=1
  INFO root [2019-09-21 15:11:43,881] - 
  INFO root [2019-09-21 15:11:43,882] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:11:43,883] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:11:43,883] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:11:43,883] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:11:43,897] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 15:11:43,897] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 15:11:43,901] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:54724 )
  INFO root [2019-09-21 15:11:43,902] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:54724, SOMAXCONN=128.
  INFO root [2019-09-21 15:11:43,902] - server-configs:
  INFO root [2019-09-21 15:11:43,902] - 	internalTcpAddr : 10.15.26.195:54724
  INFO root [2019-09-21 15:11:43,902] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 15:11:43,902] - 	componentID : 9000
  WARN root [2019-09-21 15:11:44,087] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:11:44,434] - Components::findLogger: found logger, addr:10.15.26.195:54721
  INFO root [2019-09-21 15:11:44,435] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:11:44,435] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:11:44,440] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 5864 ----
  INFO root [2019-09-21 15:11:44,440] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:11:44,440] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:11:44,440] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:11:44,636] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 15:11:44,636] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 15:11:44,649] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 15:11:44,649] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 15:11:45,055] - ---- loginapp is running ----
 DEBUG root [2019-09-21 15:11:45,055] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 15:11:51,175] - Forwarding logs to logger[10.15.26.195:54721/0/0/0]...
 ERROR root [2019-09-21 15:22:59,161] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670181507222, lastReceivedTime=670027393402, inactivityExceptionPeriod=599500320)
  INFO root [2019-09-21 15:22:59,164] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:22:59,165] - ==> [2019-09-21 15:22:59 159] TCPPacketReceiver::processPendingEvents(10.15.26.195:54721): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:22:59,165] - ==> [2019-09-21 15:22:59 162] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670181507222, lastReceivedTime=670027393402, inactivityExceptionPeriod=599500320)
  WARN root [2019-09-21 15:22:59,238] - TCPPacketReceiver::processPendingEvents(10.15.26.195:54719): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:22:59,241] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=670182296837, lastReceivedTime=670026846572, inactivityExceptionPeriod=599500320)
  INFO root [2019-09-21 15:22:59,246] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 15:22:59,247] - onLoginAppShutDown()
  INFO root [2019-09-21 15:22:59,247] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:22:59,247] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 15:22:59,256] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 15:22:59,257] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 15:22:59,557] - ThreadPool::destroy(): waiting for thread(2)[0x190bdb0,0x190bfb8,], try=1
  INFO root [2019-09-21 15:35:45,574] - 
  INFO root [2019-09-21 15:35:45,574] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:35:45,574] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:35:45,574] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:35:45,575] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:35:45,584] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 15:35:45,585] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 15:35:45,589] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:55695 )
  INFO root [2019-09-21 15:35:45,589] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:55695, SOMAXCONN=128.
  INFO root [2019-09-21 15:35:45,589] - server-configs:
  INFO root [2019-09-21 15:35:45,589] - 	internalTcpAddr : 10.15.26.195:55695
  INFO root [2019-09-21 15:35:45,589] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 15:35:45,590] - 	componentID : 9000
  WARN root [2019-09-21 15:35:45,755] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:35:45,870] - Components::findLogger: found logger, addr:10.15.26.195:55689
  INFO root [2019-09-21 15:35:45,870] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:35:45,871] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:35:45,875] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 10832 ----
  INFO root [2019-09-21 15:35:45,876] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:35:45,876] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:35:45,876] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:35:46,068] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 15:35:46,069] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 15:35:46,079] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 15:35:46,080] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 15:35:46,471] - ---- loginapp is running ----
 DEBUG root [2019-09-21 15:35:46,472] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 15:35:52,582] - Forwarding logs to logger[10.15.26.195:55689/0/0/0]...
 ERROR root [2019-09-21 15:39:58,336] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680373255700, lastReceivedTime=680243420945, inactivityExceptionPeriod=599499169)
  INFO root [2019-09-21 15:39:58,341] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:39:58,342] - ==> [2019-09-21 15:39:58 334] TCPPacketReceiver::processPendingEvents(10.15.26.195:55689): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:39:58,343] - ==> [2019-09-21 15:39:58 337] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680373255700, lastReceivedTime=680243420945, inactivityExceptionPeriod=599499169)
  WARN root [2019-09-21 15:39:58,432] - TCPPacketReceiver::processPendingEvents(10.15.26.195:55691): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:39:58,433] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=680374231765, lastReceivedTime=680243932237, inactivityExceptionPeriod=599499169)
  INFO root [2019-09-21 15:39:58,445] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 15:39:58,451] - onLoginAppShutDown()
  INFO root [2019-09-21 15:39:58,451] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:39:58,451] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 15:39:58,470] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 15:39:58,471] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 15:39:58,772] - ThreadPool::destroy(): waiting for thread(2)[0x16e8778,0x16e8980,], try=1
  INFO root [2019-09-21 15:40:00,268] - 
  INFO root [2019-09-21 15:40:00,307] - -----------------------------------------------------------------------------------------


  INFO root [2019-09-21 15:40:00,309] - Resmgr::initialize: KBE_ROOT=D:/kbengine/
  INFO root [2019-09-21 15:40:00,309] - Resmgr::initialize: KBE_RES_PATH=D:/kbengine/kbe/res/;D:/kbengine/BattleOfBalls_assets/;D:/kbengine/BattleOfBalls_assets/scripts/;D:/kbengine/BattleOfBalls_assets/res/
  INFO root [2019-09-21 15:40:00,310] - Resmgr::initialize: KBE_BIN_PATH=D:/kbengine/kbe/bin/server/
  INFO root [2019-09-21 15:40:00,414] - NetworkInterface::initialize(EXTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:20013 )
  INFO root [2019-09-21 15:40:00,415] - NetworkInterface::initialize(EXTERNAL-TCP): address 10.15.26.195:20013, SOMAXCONN=128.
  INFO root [2019-09-21 15:40:00,418] - NetworkInterface::initialize(INTERNAL-TCP): bound to all interfaces with default route interface on 10.15.26.195 ( 10.15.26.195:55787 )
  INFO root [2019-09-21 15:40:00,418] - NetworkInterface::initialize(INTERNAL-TCP): address 10.15.26.195:55787, SOMAXCONN=128.
  INFO root [2019-09-21 15:40:00,419] - server-configs:
  INFO root [2019-09-21 15:40:00,419] - 	internalTcpAddr : 10.15.26.195:55787
  INFO root [2019-09-21 15:40:00,419] - 	externalTcpAddr : 10.15.26.195:20013
  INFO root [2019-09-21 15:40:00,419] - 	componentID : 9000
  WARN root [2019-09-21 15:40:00,725] - invalid UID(0) <= 0, please check UID for environment! automatically set to 41181.
  INFO root [2019-09-21 15:40:01,083] - Components::findLogger: found logger, addr:10.15.26.195:55781
  INFO root [2019-09-21 15:40:01,083] - Components::addComponent: reset orderLog, uid=41181!
  INFO root [2019-09-21 15:40:01,084] - Components::addComponent[logger], uid=41181, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2019-09-21 15:40:01,090] - ---- loginapp Version: 2.4.5. ScriptVersion: 0.1.0. Pythoncore: 3.7.3. Protocol: CE9FF53F4E85387EE4455C7191269324. Config: Debug X86. Built: 09:58:16 May  8 2019. AppID: 9000. UID: 41181. PID: 12464 ----
  INFO root [2019-09-21 15:40:01,094] - Server error_name: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz with 2097151kB RAM
  INFO root [2019-09-21 15:40:01,095] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2019-09-21 15:40:01,095] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
  INFO root [2019-09-21 15:40:01,291] - Script::install(): is successfully, Python=(3.7.3 (default, May  8 2019, 09:53:38) [MSC v.1916 32 bit (Intel)])!
  INFO root [2019-09-21 15:40:01,292] - Script::install(): KBExtra is successfully!
S_INFO root [2019-09-21 15:40:01,302] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2019-09-21 15:40:01,302] - TelnetServer server is running on port 31000
  INFO root [2019-09-21 15:40:01,743] - ---- loginapp is running ----
 DEBUG root [2019-09-21 15:40:01,744] - Components::process(): Request for the process of identity...
  WARN root [2019-09-21 15:40:07,892] - Forwarding logs to logger[10.15.26.195:55781/0/0/0]...
 ERROR root [2019-09-21 15:55:18,422] - Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689574112787, lastReceivedTime=689391132862, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 15:55:18,435] - The following logs sent to logger failed:
  WARN root [2019-09-21 15:55:18,436] - ==> [2019-09-21 15:55:18 418] TCPPacketReceiver::processPendingEvents(10.15.26.195:55781): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:55:18,436] - ==> [2019-09-21 15:55:18 423] Components::removeComponentByChannel: logger : 2000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689574112787, lastReceivedTime=689391132862, inactivityExceptionPeriod=599500000)
  WARN root [2019-09-21 15:55:18,586] - TCPPacketReceiver::processPendingEvents(10.15.26.195:55780): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2019-09-21 15:55:18,586] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit(reason=TCPPacketReceiver::processRecv(): error=10054
)! Channel(timestamp=689575761616, lastReceivedTime=689391248886, inactivityExceptionPeriod=599500000)
  INFO root [2019-09-21 15:55:18,621] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2019-09-21 15:55:18,622] - onLoginAppShutDown()
  INFO root [2019-09-21 15:55:18,622] - Shutdowner::onShutdown: shutting down
  INFO root [2019-09-21 15:55:18,622] - Shutdowner::onShutdownEnd: shutting down
  INFO root [2019-09-21 15:55:18,639] - Script::uninstall(): is successfully!
 DEBUG root [2019-09-21 15:55:18,639] - ThreadPool::destroy(): starting size 2.
  WARN root [2019-09-21 15:55:18,941] - ThreadPool::destroy(): waiting for thread(2)[0x147a3b0,0x147a0d8,], try=1
